New css base compound study html
Princeton-LSI-ResearchComputing/tracebase pull request #102
Opened 2021-06-02 17:21 UTC by fkang-pu

## Summary Change Description

- downloaded Bootstrap CSS and JS version 5.0.1

- added a new base template (base_1.html) including navbar and sidebar

- added hyperlink for dashboard to home.html (easy to navigate during test)

- replaced function-based views for Compound with class-based views (CBV)
   notes:   
new html files for list and detail views in templates/DataRepo/ (Django default location for an app)
      keep old templates/compound_list.html and  templates/compound_detail.html (for function_based views) for evaluating FBV vs. CBV.

- added list and detail views and templates for Study using CBV

- ran SuperLinter locally, the main errors were associated with downloaded Bootstrap CSS and JS. Don't feel we should edit Bootstrap files. Would like to take suggestions on how to handle such issues and pass linting.

## Affected Issue Numbers

- Resolves #49
- Resolves #75

## Code Review Notes

- choose to use downloaded Bootstrap CSS and JS ; alternatively we could  use [ jsDelivr link](https://getbootstrap.com/docs/5.0/getting-started/introduction/). 
- use bootstrap.min.css in base_1.html as suggested by Bootstrap, same as bootstrap.css but without spacing. The latter is easy to read.

## Checklist

- [x ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-06-03 13:49 UTC, jcmatese requested changes
I think this is a good launch/continuation point.  I made a couple comments, but my only concern/change might be the comment Http404 function, if I understand it correctly.

2021-06-03 13:49 UTC, jcmatese commented on DataRepo/templates/DataRepo/study_detail.html
> +    <h4>Study Name: <a href="{% url 'study_detail' study.id %}">{{study.name}}</a></h4>
Is this just a self-referential link? (links to same page user is already viewing?)

2021-06-03 13:49 UTC, jcmatese commented on DataRepo/urls.py
> +    # path("compound/<int:cpd_id>/", views.compound_detail, name="compound_detail"
Saving for later (or an alternative idea), or can be deleted?

2021-06-03 13:49 UTC, jcmatese commented on DataRepo/views.py
> +# from django.http import Http404
It would seem you should not comment this, if Http404 might be raised in line 29?

2021-06-03 13:58 UTC, fkang-pu commented on DataRepo/views.py
> +# from django.http import Http404
I use Class based view (CBV), so Http404 should be raised automatically by the view. But we may need it later if adding function based views. If I don't comment out (or delete) the line, linting would raise an error (or warning?).

2021-06-03 14:12 UTC, jcmatese commented on DataRepo/views.py
> +# from django.http import Http404
was raised in Zoom call that the line I was concerned about was also in a comment block, so I guess it is not an issue, as least not the one I thought 
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/28c66369b65e080002b88f3d6a637e7a871796a5/DataRepo/views.py#L12-L27

2021-06-03 14:13 UTC, jcmatese approved these changes

2021-06-03 15:24 UTC, lparsons approved these changes
LGTM (Looks Good To Me)! Just a couple of places I would remove commented out code. Also, if you notice any other places where there is unused code/files, please remove those too.

2021-06-03 15:24 UTC, lparsons commented on DataRepo/templates/base.html
> +        <!--script src=>"{% static 'js/sidebar.js' %}"</script-->
NB: Removed commented code

2021-06-03 15:24 UTC, lparsons commented on DataRepo/views.py
> +
NB: Removed commented code

2021-06-03 15:24 UTC, lparsons commented on DataRepo/views.py
> +"""
NB: Removed commented code

2021-06-03 18:41 UTC, hepcat72 approved these changes
Looks good Fan.  Great work!

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/templates/navbar.html
> +                Download Data</a>
NB.
```suggestion
                  Download Data
                </a>
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/templates/navbar.html
> +                Help</a>
NB.
```suggestion
                  Help
                </a>
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/templates/navbar.html
> +            <input class="form-control me-2" type="search" placeholder="Text Search" aria-label="Search">
NB.
```suggestion
            <input class="form-control me-2" type="search" placeholder="Text Search" aria-label="Search" />
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/templates/sidebar.html
> +        <a href="#" class="list-group-item list-group-item-action bg-light">Peak Data</a>
NB. So that necessary edits are easy to find later on and we don't end up with any missed changes, I suggest adding TODO comments.
```suggestion
        <!-- TODO -->
        <a href="#" class="list-group-item list-group-item-action bg-light">Protocols</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Animals</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Samples</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">MS Runs</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Peak Groups</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Peak Data</a>
        <!-- /TODO -->
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +    context_object_name = "compound_list"
NB. This is [automatically vivified by `ListView`](https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/#making-friendly-template-contexts) and is unnecessary.
```suggestion
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_list.html"
NB.  Likewise, [this is automatically generated](https://docs.djangoproject.com/en/3.2/topics/class-based-views/generic-display/#generic-views-of-objects) as well.
```suggestion
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +    template_name = "DataRepo/study_list.html"
NB. See above.
```suggestion
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +    template_name = "DataRepo/study_detail.html"
NB. See above.
```suggestion
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_detail.html"
NB. See above.
```suggestion
```

2021-06-03 18:41 UTC, hepcat72 commented on DataRepo/views.py
> +"""
```suggestion
"""
For reference, by default:
    the template name for each ListView and DetailView is <lower-case model name>_<list or detail, respectively>.html
    the context variable name in each list and detail template is <lower-case model name>_list and <lower-case model name>, repectively
"""
```

2021-06-03 22:58 UTC, lparsons commented on DataRepo/templates/home.html
> +        <br>
@hepcat72 Did you test the rendering of that change? I'm not opposed to it, just wary of changing HTML without looking at the result.

2021-06-04 15:05 UTC, fkang-pu commented on DataRepo/templates/DataRepo/study_detail.html
> +    <h4>Study Name: <a href="{% url 'study_detail' study.id %}">{{study.name}}</a></h4>
Made the change as suggested. Thanks.

2021-06-04 15:06 UTC, hepcat72 commented on DataRepo/templates/home.html
> +        <br>
No.  It's just a suggestion.  My understanding of the review process is that the author decides whether to implement the change and works it out, but I take your point.  Perhaps in future issues, I'll describe the suggestion if I haven't tested, instead of proposing a commit.

2021-06-04 15:06 UTC, fkang-pu commented on DataRepo/urls.py
> +    # path("compound/<int:cpd_id>/", views.compound_detail, name="compound_detail"
deleted now. will push a commit soon.

2021-06-04 15:08 UTC, fkang-pu commented on DataRepo/templates/base.html
> +        <!--script src=>"{% static 'js/sidebar.js' %}"</script-->
will delete line 53.

2021-06-04 15:10 UTC, fkang-pu commented on DataRepo/templates/DataRepo/compound_list.html
> +            <td><a href="{{ compound.hmdb_url}}" target="_blank">{{ compound.hmdb_id }}</a></td>
made the change. Thanks.

2021-06-04 15:11 UTC, fkang-pu commented on DataRepo/templates/DataRepo/study_list.html
> +{% block title %}Studies{% endblock %}
title block used to override the page title listed in base.html.

2021-06-04 15:15 UTC, hepcat72 commented on DataRepo/templates/DataRepo/study_list.html
> +{% block title %}Studies{% endblock %}
Ah, neat.

2021-06-04 15:18 UTC, fkang-pu commented on DataRepo/templates/home.html
> +        <br>
I won't make any change for this PR, since we will design and make a big change for home page later.  I resized the image in my new local branch, and will include that change when adding views and templates for other models ( a new PR early next week).

2021-06-04 15:22 UTC, fkang-pu commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_list.html"
We may want to make a group decision on this (if it's default, should we list it ?). I can make changes for all views in next PR.

2021-06-04 15:26 UTC, hepcat72 commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_list.html"
It does make the code easier to follow, if someone is unaware the template_name and context_object_name automatically exist.  So I would be OK with setting these variables, though in that case, I think it should be done in all the generic classes, including the detail classes.  Either way is fine with me.

2021-06-04 15:35 UTC, lparsons commented on DataRepo/templates/home.html
> +        <br>
@hepcat72 I agree that it's up to the author to decide to accept changes. And yes, I feel like a suggested commit should be "safe" to accept by the author, otherwise, just described. If you want to suggest larger changes, I think a separate PR to the authors branch is acceptable.

2021-06-04 16:00 UTC, lparsons commented on DataRepo/views.py
> +# from django.http import Http404
Noted in #109, resolving.

2021-06-04 16:04 UTC, lparsons commented on DataRepo/views.py
> +    context_object_name = "compound_list"
Noted above and in #109.

2021-06-04 16:04 UTC, lparsons commented on DataRepo/views.py
> +    template_name = "DataRepo/study_list.html"
Noted above and in #109.

2021-06-04 16:04 UTC, lparsons commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_detail.html"
Noted above and in #109.

2021-06-04 16:05 UTC, lparsons commented on DataRepo/views.py
> +"""
Noted in #109.

2021-06-04 16:05 UTC, lparsons commented on DataRepo/views.py
> +    template_name = "DataRepo/study_detail.html"
Noted above and in #109.

2021-06-04 16:05 UTC, lparsons commented on DataRepo/views.py
> +    template_name = "DataRepo/compound_list.html"
Noted in #109.

2021-06-04 17:29 UTC, lparsons commented on DataRepo/views.py
> +# from django.http import Http404
Going to go ahead and fix this and a few other minor things, and leave the rest in #109 to be fixed later.

2021-06-04 17:48 UTC, merged