Load animal treatment
Princeton-LSI-ResearchComputing/tracebase pull request #120
Opened 2021-06-14 15:26 UTC by jcmatese

## Summary Change Description

add new example file containing animal treatments source from Michael Neinast
serum_lactate_timecourse_treatment header and data tweaks
tests now load serum_lactate_timecourse_treatment
tests tweaked to account for additional samples, animals, and study
utils SampleTableLoader now casts tracer_labeled_count as an int
utils SampleTableLoader now casts time_collected as a float
added eol last line of serum_lactate_timecourse_treatment.tsv
removed default category from Protocol model
moved retrieve_protocol method logic from Accucor loader to a class method in Protocol
added treatment to obob_sample_table_headers.yaml
sample loader now creates treatment protocols, if column is defined

## Affected Issue Numbers

- Resolves #94

## Code Review Notes

Describe any areas of concern that code reviewers should pay particular
attention to.  E.g. There are significant logic changes in function X.

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-06-14 15:53 UTC, hepcat72 commented
Given no checkmark in the checklist for the issue requirements, are there specific requirements in the issue that weren't implemented that I can keep in mind during review?

2021-06-14 16:35 UTC, hepcat72 approved these changes
Looks good John.  I had a few knits only.

2021-06-14 16:35 UTC, hepcat72 commented on DataRepo/models.py
> +        print(f"Finding or inserting {category} protocol for '{protocol_input}'...")
NB. I'm not sure what would happen if the expected args aren't supplied, but assuming it would be an exception, and seeing that there's no check before using the argument values on line 109, it would be nice to both mention the exceptions that can be thrown in the above comment and catch (in the call to this method below) the specific error that can be raised if the required arguments were not supplied.

2021-06-14 16:35 UTC, hepcat72 commented on DataRepo/models.py
> +    def Retrieve_protocol(cls, **kwargs):
NB.  There is already a method below (in `utils.py`) named `retrieve_protocol`.  While they don't technically collide, it would be nice if the only name difference wasn't WRT case, which could lead to coder mistakes in the future.

2021-06-14 16:35 UTC, hepcat72 commented on DataRepo/models.py
> +                    description = kwargs.get("provisional_description")
NB. I think debugging in the future would be aided by declaring and initializing all input arguments at the top of the method, such as this `provisional_description` argument.

2021-06-14 16:35 UTC, hepcat72 commented on DataRepo/models.py
> +            int(data)
NB. I'm not sure if casting to an integer is the best strategy.  I'm not certain, but it might silently indicate that `1.5` is an integer.  I would advocate using `isinstance(i, int)` instead. And if we use that, we probably wouldn't need a separate method.  Or, @lparsons may know a better method.

2021-06-14 16:35 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        self.assertEqual(Study.objects.all().count(), self.ALL_STUDIES_COUNT)
C. This is a great improvement.  Makes adding tests/data much easier by reducing the need to edit other tests.

2021-06-14 17:03 UTC, jcmatese commented
> Given no checkmark in the checklist for the issue requirements, are there specific requirements in the issue that weren't implemented that I can keep in mind during review?

I believe the first 4 bullet points were implemented in this PR.
The last 2 (test-related) were implemented by @lparsons in an earlier PR, I believe.

Possibly the only thing  missing would be "deleting a protocol while an animal is associated with it" test?

2021-06-14 17:10 UTC, jcmatese commented on DataRepo/models.py
> +        print(f"Finding or inserting {category} protocol for '{protocol_input}'...")
I guess I can move that line into the try block, just in case. I think I did try to pass empty values, and I think that line was fine, but it threw an exception later with the database queries.  I did spend a little time searching for the best way to check a required set-list of `kwargs`, but I could not really find a good example.  If you or Lance had a pattern or re-useable `CheckRequiredArgs` that the codebase could employ, we could utilize that here.

2021-06-14 17:18 UTC, jcmatese commented on DataRepo/models.py
> +    def Retrieve_protocol(cls, **kwargs):
The `utils.py` `retrieve_protocol ` was the original instance method for the Accucor loader code.  It now passes its instance data (attributes-values) to the `Protocol` class method of similar name `Retrieve_protocol`.  I am not wed to _any_ of these names, if anyone has better ideas or more clear naming.  Essentially, they all call `get_or_create` `Protocol` with either intrinsic attr-values or args, with the _exception_ that if the primary input/name is an integer, it _assumes_ the user only want to try`get` (as db identifier).

2021-06-14 17:20 UTC, jcmatese commented on DataRepo/models.py
> +                    description = kwargs.get("provisional_description")
I could probably move that up top, if you prefer.  I just put it there because it _only_ comes into play if the protocol was just inserted/created.

2021-06-14 17:22 UTC, jcmatese commented on DataRepo/models.py
> +            int(data)
Happy to substitute a better solution, if proposed. Not really happy that with that `is_integer` method sort of floating around, for lack of a better place to put it or a built-in python equivalent that I could not find.

2021-06-14 17:27 UTC, lparsons commented on DataRepo/models.py
> +            int(data)
I believe you have a string here, so you need to cast to an `int`. However, I wouldn't both with the extra method, it doesn't really do anything. I'd just put the cast where you want it and catch the `ValueError` exception.

2021-06-14 17:35 UTC, jcmatese commented on DataRepo/models.py
> +            int(data)
It was really just a means to an ends to get the logic to behave as I envisioned (`get` vs `get_or_create` dependent on input).   I sort of prefer it the way it reads (as-is), but if people want it gone, I can convert it.
https://stackoverflow.com/questions/1265665/how-can-i-check-if-a-string-represents-an-int-without-using-try-except

2021-06-14 18:16 UTC, lparsons requested changes
This works, but I have a few blocking issues and some other more minor notes:

Blocking:

* The arguments for `Retrieve_protocol` would be easier to understand if they were spelled out in the function definition instead of using the variable keyword argument expansion.

* There are no tests for the `Retrieve_protocol` method. I wrote some tests for the main cases I can see, and submitted them as a PR to this branch.

There are a few other comments in-line in the code.

2021-06-14 18:25 UTC, lparsons commented on DataRepo/models.py
> +            int(data)
I would keep the try/except as that is pretty common in Python, in my experience. You can either do the cast and catch the exception or just perform the filter on id with the whatever the string is, and you can catch the exception then (which might even be cleaner).
```python
try:
    p = Protocol.objects.filter(id=protocol_input)
except ValueError:
    (p, created) = Protocol.objects.get_or_create(name=protocol_input)
```

2021-06-14 19:53 UTC, hepcat72 commented on DataRepo/models.py
> +            int(data)
Ah, right.  Strong typing.  I forgot.  So would we expect a value error on `int("1.5")` then, or does it silently convert it to `1`?

2021-06-14 19:55 UTC, lparsons commented on DataRepo/models.py
> +            int(data)
```python
$ python manage.py shell
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: int("1")
Out[1]: 1

In [2]: int("a")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-d9136db7b558> in <module>
----> 1 int("a")

ValueError: invalid literal for int() with base 10: 'a'

In [3]: int("1.5")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-aece86d34916> in <module>
----> 1 int("1.5")

ValueError: invalid literal for int() with base 10: '1.5'
```

2021-06-14 20:29 UTC, fkang-pu commented on DataRepo/example_data/obob_sample_table_headers.yaml
>  ANIMAL_STATE:
@jcmatese do we plan to remove `state` from `Animal`? not sure if it will be addressed later, but mentioned here since it's also related to sample loading format and script.

2021-06-15 15:12 UTC, jcmatese commented on DataRepo/example_data/obob_sample_table_headers.yaml
>  ANIMAL_STATE:
Addressed later.  Distinct issue.

2021-06-16 13:11 UTC, jcmatese commented on DataRepo/models.py
> +        print(f"Finding or inserting {category} protocol for '{protocol_input}'...")
ended up changing the args encoding and moving the printed feedback to the caller

2021-06-16 13:11 UTC, jcmatese commented on DataRepo/models.py
> +    def Retrieve_protocol(cls, **kwargs):
methods names changed

2021-06-16 13:12 UTC, jcmatese commented on DataRepo/models.py
> +                    description = kwargs.get("provisional_description")
args encoding changed

2021-06-16 13:13 UTC, jcmatese commented on DataRepo/models.py
> +            int(data)
re-coded to try a bunch of `try` `except` conditions

2021-06-16 13:14 UTC, jcmatese commented on DataRepo/models.py
> +            f"{action} {category} protocol {protocol.id} '{protocol.name}' '{protocol.description}'"
tried this

2021-06-16 13:14 UTC, jcmatese commented on DataRepo/models.py
> +
tried this

2021-06-16 13:19 UTC, jcmatese commented on DataRepo/models.py
> +    def Retrieve_protocol(cls, **kwargs):
re-written.  The reason for the original implementation was to visually indicate it was a class method (a ucfirst convention I have usually followed from perl days) and employed keyword-args because it allows arbitrary order and easy extension in the future (for example, adding a protocol designer or a extensive list of protocols parameter-value pairs).

2021-06-16 15:42 UTC, lparsons commented on DataRepo/example_data/obob_sample_table_headers.yaml
> +ANIMAL_TREATMENT: "Animal Treatment"
NB: Reusing the `obob_sample_table_headers.yaml` for another experiment could be confusing. One option would be to rename this file to be more generic. Another option would be to create a second file that is used for the serum lactate timecourse dataset. I lean a bit toward renaming to be more generic, but I could be swayed.

2021-06-16 15:44 UTC, lparsons commented on DataRepo/models.py
> +        cls, protocol_input, category, provisional_description
NB: I believe that `provisional_description` and `category` could both be made optional with a default of `None`. If the protocol id is specified, neither is used. It seems like all of the places where this called actually specify a category and description, but the logic below treats them as optional (can be `None`) yet they are required to be specified.
```python
    def retrieve_or_create_protocol(
        cls, protocol_input, category=None, provisional_description=None
    ):

2021-06-16 15:45 UTC, lparsons commented on DataRepo/tests/test_models.py
> +        )
NB: If `category` and `description` are made optional, they could be dropped here.

2021-06-16 15:48 UTC, lparsons commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
NB: As written, there could be a number of key errors caught here. I think this is intended to catch the case of there being no `ANIMAL_TREATMENT` column in the file, since that is optional. If so, moving the `except` up to right after line `160` would ensure this is the only exception caught. Also, the message "No recorded treatment" could be interpreted as "A treatment was found in the file, but not recorded (due to some error)", which I do not believe is the intent. Using a message like "No animal treatment found" might be less likely to be misinterpreted. *e.g.*
```python
                # Animal Treatments are optional protocols
                try:
                    protocol_input = row[self.headers.ANIMAL_TREATMENT]
                except KeyError:
                    print("No animal treatment found")
```

2021-06-16 16:02 UTC, jcmatese commented on DataRepo/example_data/obob_sample_table_headers.yaml
> +ANIMAL_TREATMENT: "Animal Treatment"
I would probably prefer a generic name/template, if other are agreeable.

2021-06-16 16:03 UTC, hepcat72 approved these changes
Again, looks good to me.  Only knits.

2021-06-16 16:03 UTC, hepcat72 commented on DataRepo/models.py
> +            print(f"Protocol ID {protocol_input} does not exist.")
NB. It's probably better to set the message in the exception object and raise that without printing.  Then the caller can/should decide what to do with it.  Here's one way of doing that:
```
except Protocol.DoesNotExist as e:
    raise Protocol.DoesNotExist(f"Protocol ID {protocol_input} does not exist.) from e
```
I'm still learning the best practices WRT exception handling though, so I'm not sure if this is the best way to do it.

2021-06-16 16:13 UTC, jcmatese commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
Presumably there is also some other added conditional/logic/line that prevents the `retrieve_or_create_protocol` from being called without a `protocol_input` as the if condition continues on?

2021-06-16 16:19 UTC, jcmatese commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
guess I will add an `else`

2021-06-16 16:29 UTC, jcmatese commented on DataRepo/models.py
> +            print(f"Protocol ID {protocol_input} does not exist.")
I don't know any better; I made the change, but don't see any difference in stdout running tests.

2021-06-16 16:31 UTC, lparsons commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
Oops. I see there is already a `if self.headers.ANIMAL_TREATMENT:` up above. Could you help me understand why we are catching the `KeyError` and moving on?

2021-06-16 16:32 UTC, lparsons commented on DataRepo/models.py
> +            print(f"Protocol ID {protocol_input} does not exist.")
The difference is that the caller has a choice of what to do with the Exception. They may or may not want to print a warning, error, etc.

2021-06-16 17:03 UTC, jcmatese commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
I think it could be in the header (i.e. column exists), but the value might still be undefined/`None` ?

2021-06-16 17:13 UTC, jcmatese commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
This _might_ also be tied up with the yaml file definition/naming (having a generic file, or specific yaml files) concern and the defaults set in the loader class initiation.

2021-06-16 17:18 UTC, hepcat72 commented on DataRepo/models.py
> +            print(f"Protocol ID {protocol_input} does not exist.")
Yeah, the change is in design, not behavior of the current code.  Anyone else who writes a call to this method can now decide how verbose it should be about this error.

2021-06-16 17:40 UTC, lparsons commented on DataRepo/utils.py
> +                    print("No recorded treatment.")
> I think it could be in the header (i.e. column exists), but the value might still be undefined/`None` ? (or maybe I was misinterpetting the error)

I don't believe so, since a KeyError means the key (header) doesn't exist. I don't know that we actually test for the case where the user provides a column with invalid values. However, in that case we should not load the data and thus throw an exception (and I believe that is the case here as the protocol would fail to be saved.

> This _might_ also be tied up with the yaml file definition/naming (having a generic file, or specific yaml files) concern and the defaults set in the loader class initiation. (i.e. prehaps, I may have made the initial addition/change, it broke the tests based on the non-treatment file, and I added a condition that worked around it? )

The new code clearly catches the case where the header doesn't exist in the data file and just skips it, which seems correct to me. Thanks for making the intention of the code clearer.

2021-06-16 18:52 UTC, jcmatese commented on DataRepo/example_data/obob_sample_table_headers.yaml
> +ANIMAL_TREATMENT: "Animal Treatment"
@lparsons so just "sample_table_headers.yaml" ? (alt. preference?)

2021-06-16 19:42 UTC, jcmatese commented on DataRepo/example_data/obob_sample_table_headers.yaml
> +ANIMAL_TREATMENT: "Animal Treatment"
Ok, I will move that, edit 3 usages in tests, and [usage on the wiki](https://nplcadmindocs.princeton.edu/index.php/TraceBase)

```
DataRepo/tests/test_views.py:            sample_table_headers="DataRepo/example_data/obob_sample_table_headers.yaml",
DataRepo/tests/test_models.py:            sample_table_headers="DataRepo/example_data/obob_sample_table_headers.yaml",
DataRepo/tests/test_models.py:            sample_table_headers="DataRepo/example_data/obob_sample_table_headers.yaml",
```

2021-06-16 20:11 UTC, merged