Modified `PeakAnnotation[File]sLoader`s to resolve peak group conflicts
Princeton-LSI-ResearchComputing/tracebase pull request #1225
Opened 2024-09-26 00:10 UTC by hepcat72

## Summary Change Description

Modified the peak annotations loader (and the peak annotation files loader) to be able to resolve peak group conflicts using researcher selected files from which specific peakgroups should be loaded.

Details:

- Created new exception classes:
  - ReplacingPeakGroupRepresentation
  - DuplicatePeakGroupResolutions
- Skipped a couple of legacy test classes whose setup data fails the new unique constraint for peak groups:
  - DataLoadingTests
  - PropertyTests
- Added the ability to count deleted stats in TableLoader
- Added row numbers to the peak group conflict information, so that errors about conflicting peak group conflict resolutions can reference the conflicting rows that need fixed.
- Removed the sequence from the peak group multiple representation check method
- Updated the delete overrides in MaintainedModel and HierCachedModel to return the values returned by the superclass method (because it contains a counts dict of all the deleted related model records).
- Added the ability to handle when self.df is None in PeakGroupConflicts.  This fixed an exception raised when there exist no conflicts.
- Added is_selected_peak_group method to the PeakAnnotationsLoader to skip and/or delete unselected representations and return a bool that indicates that a PeakGroup is OK to load (because it's either selected or has no conflict).
- Fixed a couple of inaccurate skip counts and added some comments about label observations stats.

## Affected Issues/Pull Requests

- Resolves #1211
- Merges into PR #1209

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2024-09-26 00:14 UTC, hepcat72 commented on DataRepo/data/tests/multiple_representations/resolution_handling/conflicting_resolutions.tsv
> +Peak Group Conflict	Selected Peak Annotation File	Common Sample Count	Example Samples	Common Samples
C. Added a few test files for testing the selecting of Peak Groups based on the Peak Group Conflicts sheet.

2024-09-26 00:15 UTC, hepcat72 commented on DataRepo/loaders/base/table_loader.py
>          method).
C. `TableLoader` now tracks a new stat: deleted records.

2024-09-26 00:19 UTC, hepcat72 commented on DataRepo/loaders/peak_annotation_files_loader.py
>      PeakAnnotationsLoader,
C. This loader's changes just involve passing 3 new parameters to the `PeakAnnotationsLoader` for each peak annotation file in the `Peak Annotation Files` sheet.

2024-09-26 00:26 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
>      AggregatedErrors,
C. This file is where the most important changes are.  It takes the same 3 new parameters that the `PeakAnnotationFilesLoader` that I mentioned above does, but this class acts on them.  In creates a member instance of `PeakGroupConflicts` using those 3 parameters and retrieves the resolutions, which is checks during loading of `PeakGroup`s.

2024-09-26 00:28 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
> +        )
C. Here is where it creates an instance of `PeakGroupConflicts` and retrieves its `peak_group_selections`.  We are in the constructor here.

2024-09-26 00:28 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
> +                self.skipped(PeakGroupLabel.__name__)
C. This was a minor bug I noticed while scrutinizing the new stats.

2024-09-26 00:29 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
> +            return None, False
C. If this is a skipped `PeakGroup`, return None.

2024-09-26 00:30 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
C. This is the meat of the whole PR.  All other changes in this PR simply support this code.

2024-09-26 00:30 UTC, hepcat72 commented on DataRepo/loaders/peak_group_conflicts.py
> +                header="Peak Annotation File",
C. Changed to avoid circular import issues.

2024-09-26 00:31 UTC, hepcat72 commented on DataRepo/loaders/peak_group_conflicts.py
> +            return selected_representations
C. Bug in the parent PR.  There being no conflicts sheet just had to be accounted for.

2024-09-26 00:32 UTC, hepcat72 commented on DataRepo/loaders/peak_group_conflicts.py
> +                    ]
C. I added the ability for the selected peak groups to reference the rows where the selection was made so that errors could reference them.

2024-09-26 00:32 UTC, hepcat72 commented on DataRepo/loaders/peak_group_conflicts.py
> -                            ),
C. Created a specific exception so I could catch it.

2024-09-26 00:33 UTC, hepcat72 commented on DataRepo/loaders/peak_group_conflicts.py
> -                    )
C. Moved to the new exception class.

2024-09-26 00:33 UTC, hepcat72 commented on DataRepo/management/commands/load_peak_annotation_files.py
C. Both of the load scripts were modified to simple take the new arguments/options.

2024-09-26 00:34 UTC, hepcat72 commented on DataRepo/management/commands/load_table.py
>      def report_status(self):
C. As with `TableLoader`, this script now supports deleted stats.

2024-09-26 00:35 UTC, hepcat72 commented on DataRepo/models/hier_cached_model.py
>          """
C. Both `HierCachedModel` and `MaintainedModel`'s `delete` methods needed to be able to pass back the return from the superclass's delete method so that I could use the returned dict to update the deleted stats of the cascaded model deletions.

2024-09-26 00:36 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> -            msrun_sample__msrun_sequence__pk=self.msrun_sample.msrun_sequence.pk,
C. This is the change in the unique constraint to remove sequence.

2024-09-26 00:37 UTC, hepcat72 commented on DataRepo/tests/loaders/base/test_table_loader.py
>                  self.TestModel.__name__: {
C. From here to the `exceptions.py` file, all of the updates are either related to the new deleted stat or the tests I added for ensuring that conflict resolutions happen correctly.

2024-09-26 00:38 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotation_files_loader.py
C. New test for conflicting resolutions.

2024-09-26 00:39 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotations_loader.py
C. Similar test, but in a different context.

2024-09-26 00:40 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotations_loader.py
> +
C. Test of the deletion of previously loaded PeakGroups that were not selected in the resolution.

2024-09-26 00:40 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_group_conflicts.py
>  from DataRepo.loaders.peak_group_conflicts import PeakGroupConflicts
C. Updated tests for the added rownum in the conflict data.

2024-09-26 00:41 UTC, hepcat72 commented on DataRepo/tests/test_models.py
C. Had to skip some legacy tests because the data they used had peak groups for the same compound belonging to different sequences (which is no longer allowed).

2024-09-26 00:42 UTC, hepcat72 commented on DataRepo/utils/exceptions.py
> +            loc_str += f"row [{rownum}] "
C. I added support for `rownum` to be a list.  This was a quick way to make the raising of `DuplicatePeakGroupResolutions`, simple.

2024-09-26 21:07 UTC, hepcat72 commented on DataRepo/data/tests/multiple_representations/resolution_handling/conflicting_resolutions.tsv
> +Peak Group Conflict	Selected Peak Annotation File	Common Sample Count	Example Samples	Common Samples
I know this PR looks big, but I think that if you orient yourself using my comments, it should be fairly straightforward...

2024-09-30 20:12 UTC, lparsons requested changes
This PR contains various bug fixes, loading stats updates, the ability to read peak annotation conflicts sheet,  changes the peak annotation "constraint", and implements the logic to skip/delete conflicting peak groups. It's an excellent step forward.

However, given the complexity, I feel the skipped tests should actually be fixed so that they run. It seems the most straightforward to do so by removing the offending duplicate peak groups from the test data.

2024-09-30 20:12 UTC, lparsons commented on DataRepo/loaders/peak_annotations_loader.py
> +                ).exclude(peak_annotation_file=peak_annot_file)
C: Could this query be done before the `if` statement and the results used if needed? It appears to be the same comment and query in the `if` and also the `else` section.

2024-09-30 21:33 UTC, hepcat72 commented on DataRepo/utils/exceptions.py
> +        self.conflicting = conflicting
It's an error when it's "conflicting" and a warning when it's "equivalent" (which is decided by the calling code), but either way, it's an exception in order to transmit the information to the user.  The usage of exceptions as a conveyance of a mix of warnings and errors makes the buffering of multiple exceptions simpler and the handling more consistent IMO, but it is non-standard, so I agree it should be documented in some way.  There is some documentation in both the `MultiLoadStatus` and `AggregatedErrors` classes, so perhaps exception classes that seem like warnings should reference them.  But their doc strings could probably be fleshed a bit more as well.

2024-10-01 15:07 UTC, hepcat72 commented
@lparsons - OK, see what you think now.  New commit.

2024-10-01 20:56 UTC, lparsons commented on DataRepo/tests/test_models.py
Q: I understand that the updated constraints in the PR cause a number of tests to break since there are MultiplePeakGroupRepresentation exceptions in some of the setUpTestData methods. Would it be reasonable to remove the offending samples from the test data and get those tests to run again? Naively, that seems better than leaving them broken or skipping them, but I could be missing some detail.

2024-10-02 01:53 UTC, hepcat72 commented on DataRepo/tests/test_models.py
I deleted some tests that are for features we no longer have, but I skipped some tests that still need to be converted to the new structure (i.e. use the new loaders).

There are actually quite a few tests that need yet to be refactored so that we can delete the legacy code. A number of tests are commented out (before this PR) which also need to be refactored. I think it makes sense to do all those conversions in a concerted effort, because they all deserve (and in my opinion, require) significant time and thought.

The tests I left as skipped use problematic data. For example, one of the skipped tests assures that calculations work when some of the data sums to zero. And I think that having the data used in that test when that test is converted, can help when refactoring that test. It will take some time to do that thoughtfully. However, I don't think that it's currently a pressing issue. We haven't touched any of that code since v2, which was part of the reason I felt OK putting off those other test conversions awhile back.

I think that a lot of those prior commented tests were in those PRs that weren't reviewed. It's that work that I'm suggesting we tackle with these particular tests, holistically/together, but that would be a significant delay.

I'm open to taking that time now, even if we don't do it holistically and just tackle these tests, but when I weigh it against what I'd like to get done before the lab presentation in November, I'm leaning toward putting it off.

Personally, I don't like that I'm arguing to put testing off, but we made kind of a strategic decision to do manual testing in order to speed up development, but my hope is that when I do the test refactors to delete the legacy code, I fill in all these missing tests.

2024-10-02 13:49 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotation_files_loader.py
> +    def test_PeakAnnotationFilesLoader_conflicting_peak_group_resolutions(self):
_[Somehow, I don't remember seeing this comment on my first pass of your review... anyway...]_

You're really good at being succinct.  Could you suggest a re-wording? I can't make the test name not make sense in my head.  It is testing the case of "conflicting peak group resolutions" - that they are detected and raised as an error.  The user has chosen 2 **different** (i.e. "conflicting") resolutions (selected peak annotation files) for the same case (same compound and same set of samples) multiple times, (which can arise due to manual manipulation of the file such as copying and pasting in additional rows in the `Peak Group Conflicts` sheet).

2024-10-02 14:06 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotations_loader.py
> +
Sorry, this comment should have been on line 1035.  I'm adding some docstrings now.

2024-10-02 14:31 UTC, hepcat72 commented on DataRepo/loaders/peak_annotations_loader.py
> +                ).exclude(peak_annotation_file=peak_annot_file)
_[I think I know why I missed some of your comments on the first pass.  I just searched the page for your name and hadn't expanded the "load more" sections...]_

They are definitely _similar_ comments, but they are intentionally different.  The queries are also different: one **includes** the selected peak annotation file and the other **excludes** the selected peak annotation file.  I could break the query into 2(/3) parts: one including the common filter elements above the conditional and a filter/exclude in each portion of the conditional, but either way has pros/cons.  I feel like each query being complete and self-contained makes it more readable, but given that wasn't the case here... I guess it is relative to the reader.  I'm not sure whether having 2 queries as opposed to one is less efficient in this case.  But IDK, maybe having only the different parts in the conditional would make it more readable?

2024-10-02 14:33 UTC, hepcat72 commented on DataRepo/tests/loaders/test_peak_annotations_loader.py
> +
After push: line 1044.

2024-10-04 21:42 UTC, merged