Peakdata adv search
Princeton-LSI-ResearchComputing/tracebase pull request #137
Opened 2021-07-10 00:25 UTC by hepcat72

## Summary Change Description

I added a surrounding form element to support multiple output formats/hierarchies.

## Affected Issue Numbers

- Resolves #129
- Resolves #129

## Code Review Notes

This supplants PR #127.  I implemented some of the fixes from that review in this PR.

- Known minor issue 1: If you submit a search of 1 output format and on the results page, switch output formats, the form shows a red error.  It is harmless.  I tried many things to prevent that error, but have not as yet, figured it out.
- Known minor issue 2: The management form is arbitrarily generated from 1 of the 2 form classes.  It is fully functional, but feels like a kludge.

Everything else seems to otherwise work correctly.  However, (related to "known issue 2") the 1 overall design aspect I don't like is the fact that multiple different form types are wrapped in the same HTML form tag.  This is the only way I could figure out how to submit all form data in a single submission (in order to retain the user's entries before they changed the selected output format).  There are what feel like hacky kludges to validate only the forms of the selected output format form type.  I am open to suggested cleaner designs, though keep in mind, I already tried numerous more "proper" ways to do it.  It may just be a square peg / round hole issue.  Django is not designed to accept form submissions of multiplke different formsets in a single form.  I managed to get it to work in the most elegant way I could, but I posted on stack to ask if there's a better way to accomplish the same goal...

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-07-12 16:23 UTC, hepcat72 commented on DataRepo/views.py
> +        if format not in search["searches"]:
NB. Add comment.
```suggestion
        # If this format has not yet been initialized
        if format not in search["searches"]:
```

2021-07-12 16:23 UTC, hepcat72 commented on DataRepo/views.py
> +def pathStepToPosGroupType(spot):
NB.
- [ ] Add function doc comment.

2021-07-12 16:23 UTC, hepcat72 commented on DataRepo/views.py
> +def rootToFormatInfo(rootInfo):
NB.
- [ ] Add function doc comment.

2021-07-12 16:23 UTC, hepcat72 commented on static/js/hierarchical_formsets.js
>  //   idx - The hierarchical node index, relative to the parent's child node array.
NB.
- [ ] Add selectedformat to comment's arg list

2021-07-12 19:08 UTC, lparsons requested changes
Generally this code looks pretty good and get's us a very flexible search. Nice work!

There are a few comments in the code that could be addressed if desired. 

The one breaking issue I found was with the results returned. When I select "PeakData", I seem to get the results I expect, which is to say PeakData rows that match my search criteria. However, when I select "PeakGroups", there is a column "Atom:Label" that shows the PeakData level labeling. This means that each PeakGroup is presented multiple times, once for each labeling in that group. However, a PeakGroup represents all of the labeling combinations for a given compound (i.e. C:0, C:1, C:2, C:3, C:4, C:5, and C:6).

![image](https://user-images.githubusercontent.com/645128/125342069-605c7f80-e322-11eb-98ea-ed3409dbf8e0.png)

Finally, I admit I wasn't able to follow all of the code in detail. Not that there was any issue with the code, but there was a lot included. In the future it might be nice to break up things like this into smaller pieces. One idea would be to have one PR that included just a JavaScript form that submitted an appropriate data structure and included some tests to see that it functioned as expected. A subsequent PR could be some code to process that submission and create a proper queryset in Django, etc. Not a major issue, just a note. I realize that it's often difficult to break up a problem like this into pieces. Overall, job well done on a complex problem!

2021-07-12 19:43 UTC, hepcat72 commented
> a PeakGroup represents all of the labeling combinations for a given compound (i.e. C:0, C:1, C:2, C:3, C:4, C:5, and C:6).
> 
> ![image](https://user-images.githubusercontent.com/645128/125342069-605c7f80-e322-11eb-98ea-ed3409dbf8e0.png)

Yeah.  I confess I was confused about that.  It seemed there wasn't much different between the 2 output formats.  That original PeakGroups output format is the same as the [basic search PR]9https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/1060 and was based on [Caroline's tissue data](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit#gid=1721579312) - which was linked in the requirements for issue #77 as:

> - Search results page with data mimicking the [sample spreadsheet](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit#gid=1721579312)

This makes much more sense.  I will change the peakgroups rows for both the basic search output format and the advanced search output format.  I'll leave off the label values since that's what separates those rows.

2021-07-12 19:50 UTC, hepcat72 commented on DataRepo/forms.py
> +    )
Yeah... That *did* occur to me.  I was just avoiding it to focus on other things.

- [ ] Create a base class in forms.py

2021-07-12 19:51 UTC, hepcat72 commented on DataRepo/forms.py
> +    )
And regarding the overall comment...

- [ ] Remove ":Label" from the PeakGroups format

2021-07-12 19:56 UTC, hepcat72 commented on DataRepo/multiforms.py
> +    grouped_forms = {}  # type: ignore
You know, I tried `Dict[str, str]` and had gotten errors, but I apparently couldn't get the syntax right and I couldn't find a doc that made sense to me.  So, is it?:

```
    form_classes = {}  # type: Dict[str, str]
    prefixes = {}  # type: Dict[str, str]
    success_urls = {}  # type: Dict[str, str]
    grouped_forms = {}  # type: Dict[str, str]
```

...because the stack posts I saw said it was a "comment string".  I swear I tried that and the linters complained.  Or is it literally what you supplied as code?:

```
     form_classes: Dict[str, str] = {}
     prefixes: Dict[str, str] = {}
     success_urls: Dict[str, str] = {}
     grouped_forms: Dict[str, str] = {}
```

2021-07-12 19:59 UTC, lparsons commented on DataRepo/multiforms.py
> +    grouped_forms = {}  # type: ignore
The second example you listed looks more like it to me, but you can refer to the [type hints cheat sheet from mypy](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html). Also, you can see what I used in the neuron simulator project: 

https://github.com/Princeton-LSI-ResearchComputing/neuron-simulator/blob/f85d748c93f1409426861aa7681ad2b944429313/config/settings.py#L36

2021-07-12 19:59 UTC, hepcat72 commented on DataRepo/templates/navbar.html
> +            <a role="button" class="btn btn-outline-success nobr" href="{% url 'search_advanced' %}">Advanced Search</a>
...there is another search (DataRepo/search_basic) that uses a URL path to supply parameters (currently only used for linking from records).  And I didn't know if Fan was going to implement a more basic term search - given the search box placeholder in the navbar.html header...

2021-07-12 20:01 UTC, hepcat72 commented on DataRepo/views.py
> +def pathStepToPosGroupType(spot):
- [ ] Add a test for `pathStepToPosGroupType`

2021-07-12 20:01 UTC, hepcat72 commented on DataRepo/views.py
> +def rootToFormatInfo(rootInfo):
- [ ] Add a test for `rootToFormatInfo `

2021-07-12 20:02 UTC, lparsons commented on DataRepo/templates/navbar.html
> +            <a role="button" class="btn btn-outline-success nobr" href="{% url 'search_advanced' %}">Advanced Search</a>
This seems like a good time to ask the question or perhaps discuss at our next dev meeting. @fkang-pu anything to add here?

2021-07-12 20:15 UTC, hepcat72 commented on DataRepo/templates/navbar.html
> +            <a role="button" class="btn btn-outline-success nobr" href="{% url 'search_advanced' %}">Advanced Search</a>
So, to be precise/comprehensive, the current searches (as defined by the urls code) are:

```
    path(
        "search_basic/<str:mdl>/<str:fld>/<str:cmp>/<str:val>/<str:fmt>/",
        views.search_basic,
        name="search_basic",
    ),
    path(
        "search_advanced/",
        views.AdvancedSearchView.as_view(),
        name="search_advanced",
    ),
```

`search_basic` is currently linked from the Study Detail page.  We did discuss the possibility of using the advanced search in such links/buttons, but that was before the advanced search was fully implemented.  We could remove the basic search and rename the advanced search as search and use form buttons/links.  The basic search can take only 1 field, comparator, and value, whereas the advanced can take any number.  Both also specify the output format.

If we were to keep the basic search, it would need to be updated for the new peakdata output format (or rather, we could implement a sub-template to reduce redundant code).

Neither of those searches though accomplish something akin to like a "google search" that looks for a search term regardless of the field housing the term.  The seems to be the intent of the search placeholder in navbar.html.

2021-07-12 20:49 UTC, fkang-pu reviewed
A really nice job for implementing advanced search! I must admit I only have very limited knowledge about Django form and JavaScript, it will take some time for me to understand so many lines of new code. 

a few comments after testing advanced search:

1. Lance already pointed out the issue with PeakGroup output.
2. Peakdata search worked well for me. Tried the following query strings:
	"animal is 969"
	"animal is 969" and "Tissue is Serum"
	"animal is 969" and "Sample starts with Br-xz969"
        "animal is 969" and "Presumed Output Compound is glucose"
	"study contains obob_fasted"

3. better names for "input compound" and "Presumed Output Compound"?  I would prefer "tracer"(or infusate)  and "detected compound" (or PeakGroup compound). I guess you will get feedback from the lab later.

4. Not sure if we want to share all the search features with the lab at this stage. It would be nice to have dropdown lists for a few key fields (study, animal, tissue, PeakGroupSet, compound) 

    

- top search features I would like to have with dropdown lists:

    search based on study
    search based on animal 	
    search based on PeakGroupSet (AccuCor filename) 
p.s.
    with a button for "download file "

2021-07-12 21:18 UTC, hepcat72 commented
> > a PeakGroup represents all of the labeling combinations for a given compound (i.e. C:0, C:1, C:2, C:3, C:4, C:5, and C:6).
> > ![image](https://user-images.githubusercontent.com/645128/125342069-605c7f80-e322-11eb-98ea-ed3409dbf8e0.png)
> 
> Yeah. I confess I was confused about that. It seemed there wasn't much different between the 2 output formats. That original PeakGroups output format is the same as the [basic search PR](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/106) and was based on [Caroline's tissue data](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit#gid=1721579312) - which was linked in the requirements for issue #77 as:
> 
> > * Search results page with data mimicking the [sample spreadsheet](https://docs.google.com/spreadsheets/d/1waEyLnC3VcNz43VVT1t7Sp0td8XcVf8rrzDdCuDUVcA/edit#gid=1721579312)
> 
> This makes much more sense. I will change the peakgroups rows for both the basic search output format and the advanced search output format. I'll leave off the label values since that's what separates those rows.

OK @lparsons.  Looking at the adjustment of the PeakGroup format, we need to change 2 more fields: fraction and labeled_element, both of which were from the PeakData table, as we had discussed over zoom some time back when I first implemented the basic search for the PeakGroups output format.  I think that Caroline's spreadsheet linked in issue #77 probably was intended for the PeakData output format.  Cross-referencing it with [Michael's format spreadsheet](https://docs.google.com/spreadsheets/d/1b74-f473-K4EewmCaZTv5CfVFDVglI1xyaHlKBGUAqI/edit#gid=62403243), I note that instead of fraction, it has "enrichment fraction".  And I will get the labeled_element from the Animal table.

This actually may make the PeakGroup output page a bit faster.

2021-07-12 22:13 UTC, hepcat72 commented
> 3. better names for "input compound" and "Presumed Output Compound"?  I would prefer "tracer"(or infusate)  and "detected compound" (or PeakGroup compound). I guess you will get feedback from the lab later.

There is an issue for this: #133.  That's specifically for the column names, but that applies to the select lists as well.  I will make a note of that in the issue.

> 4. Not sure if we want to share all the search features with the lab at this stage. It would be nice to have dropdown lists for a few key fields (study, animal, tissue, PeakGroupSet, compound)
> 
> * top search features I would like to have with dropdown lists:
>   search based on study
>   search based on animal
>   search based on PeakGroupSet (AccuCor filename)

These search features in this PR were requested by the lab (albeit in a different form/interface - I think this represents an improvement over what was in the mockup), so I think it's OK to push this out to the users.  Refer to the user-created docs in issue #47, under the feature inspiration section at the top - specifically the mockup.

>   p.s.
>   with a button for "download file "

Download functionality was listed as a limitation of this specific effort.  See the limitations section of issue #128.  That is next on my list however and I hope to implement it by the end of the week.

2021-07-12 22:33 UTC, hepcat72 commented on DataRepo/multiforms.py
> +    grouped_forms = {}  # type: ignore
- [x] Set the multiforms.py types.

I did all but `initial`, which is a `Dict[str, function]`, but I don't use it, so I don't know what initial takes/returns and I'd rather move on to something higher priority.  Resolving optimistically, pending manual tests.

2021-07-12 23:49 UTC, hepcat72 commented
Wow, so comparing dicts, as in `self.assertEqual(response.context["qry"], qry)` stringifies the dicts for comparison, so me creating a base class for the forms ended up changing the order of the keys in the resulting Dict, causing the tests to fail.  Anyway, it works now.  Push inbound.

2021-07-13 13:54 UTC, hepcat72 commented
OK, re-requesting review.  All (discrete) issues resolved/addressed.

2021-07-13 15:02 UTC, lparsons approved these changes
Nicely done Rob! This is a very flexible search that seems to work well in my testing. 

I think the areas mentioned for improvement (column names, dropdown labels, downloads, and basic searches) can be provided in later efforts.

@fkang-pu brings up a good point about the complexity of this search and the desire for some other simple searches. Let's leave this as "Advanced Search" for now and define some things we want to do for the "Basic Search" next.

Well done!

2021-07-13 15:07 UTC, hepcat72 commented
Thanks.

> @fkang-pu brings up a good point about the complexity of this search and the desire for some other simple searches. Let's leave this as "Advanced Search" for now and define some things we want to do for the "Basic Search" next.

I did think about the complexity issue a bit.  It's a valid concern and it could be addressed by applying a hierarchy depth limit - which trusted users could override.  I also think that this can be effectively mitigated by saving the search parameters *with* the downloaded data.  I am in the middle of writing up an issue for adding a download button ATM.

2021-07-13 17:01 UTC, fkang-pu approved these changes
The advanced search worked for me. I will need time to learn and understand Rob's code, can't  really comment on details right now.  But I think the code should be merged into the main branch ASAP.

2021-07-13 19:55 UTC, jcmatese approved these changes
I say go for it and get this in researchers' hands so we can move forward iteratively.

2021-07-13 20:40 UTC, merged