Create model for Compound
Princeton-LSI-ResearchComputing/tracebase pull request #14
Opened 2021-03-12 22:56 UTC by hepcat72

I worked on issue #10 and once I thought I was done, I realized the issue calls for tests as well - which I have not yet done.  Still learning how to do this stuff.

I inserted the CSS from the class files, though I removed the javascript.  I also created some placeholder images for header and logo.  I fully expect them to be replaced.

2021-03-12 22:57 UTC, hepcat72 commented
And of course, there are immediately linting issues.  Ugh.  I guess I know where to start on Monday.

2021-03-12 23:00 UTC, hepcat72 commented
Oh yeah, also, I forgot, I was going to link out to HMDB using the IDs...

- [ ] Get linting to pass
- [ ] Link out to HMDB

2021-03-15 15:19 UTC, jcmatese approved these changes
I think this is a good start, and I don't want to "block" it, as you can't break what doesn't exist.  That being said, going forward I think the compound model's name-conventions might need to be tweaked (unless we are resolving to just use the lab's 'Name', and they **all** must use the same names), and possibly use a "update-or-create" methodology (though that could be a separate script in the future).

2021-03-15 15:19 UTC, jcmatese commented on DataRepo/management/commands/load_compound_data.py
> +            cpd.save()
Not blocking (because I am no Django expert, and I don't want to slow down the project introduction). BUT, in the future, I imagine deleting the data and reloading should probably be a last resort because we will be making foreign keys from data tables which we would not necessarily want to regenerate.  We should investigate [update_or_create](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#update-or-create)

2021-03-15 15:19 UTC, jcmatese commented on DataRepo/models.py
> +    formula = models.CharField(max_length=256)
Not blocking.  I may be in the minority here, but I see no disadvantage to storing all the HMDB attributes from their data exports.  If we want it, or ever need it, we would have it.  I suspect it would never be updated (in this project's scope), or be in need of update (formulas, structures, and masses of well studied compounds don't change).  Further, for me the bare minimum model would have to include a "systematic_name" and "preferred_name", unless we are adding a synonyms table where one of the synonyms is tagged as "this is the lab's name".  Just my opinion.

2021-03-15 15:19 UTC, jcmatese commented on DataRepo/management/commands/load_compound_data.py
> +            cpd.name    = row['Name']
Just noting/clarifying that this is the lab's 'Name', not HMDB's 'NAME' (same file, different column)

2021-03-15 19:40 UTC, fkang-pu approved these changes
It's really nice Rob has taken the lead for coding. I can't really comment on anything related to Django and Python yet, still in the learning process. Feel free to move forward. It would be helpful if we could finalize the layout of compound table. I also echo John's comments, we will need create and update functions for a compound. After loading measurement data, it would be hard to reload compound table as compound IDs were already linked to the MS data.

2021-03-15 21:32 UTC, hepcat72 commented
Not sure what to do about these pylint errors I get:
```
$ pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
************* Module commands.load_compound_data
DataRepo/management/commands/load_compound_data.py:20:11: E1101: Class 'Compound' has no 'objects' member (no-member)
************* Module DataRepo.views
DataRepo/views.py:8:11: E1101: Class 'Compound' has no 'objects' member (no-member)
DataRepo/views.py:14:14: E1101: Class 'Compound' has no 'objects' member (no-member)
DataRepo/views.py:15:11: E1101: Class 'Compound' has no 'DoesNotExist' member (no-member)
```

2021-03-15 21:53 UTC, lparsons commented
> Not sure what to do about these pylint errors I get:
> 
> ```
> $ pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
> ************* Module commands.load_compound_data
> DataRepo/management/commands/load_compound_data.py:20:11: E1101: Class 'Compound' has no 'objects' member (no-member)
> ************* Module DataRepo.views
> DataRepo/views.py:8:11: E1101: Class 'Compound' has no 'objects' member (no-member)
> DataRepo/views.py:14:14: E1101: Class 'Compound' has no 'objects' member (no-member)
> DataRepo/views.py:15:11: E1101: Class 'Compound' has no 'DoesNotExist' member (no-member)
> ```

I think you might want to add the Django plugin for pylint: https://stackoverflow.com/questions/45135263/class-has-no-objects-member#comment89431284_47343542

2021-03-15 22:15 UTC, hepcat72 commented
I still have some css and html linting errors to address, but I'm not sure where to start with the psycopg2 build errors...  And I have yet to check out the review items.

- [ ] Fix CSS linting errors
- [ ] Fix HTML linting errors
- [ ] Figure out build errors
- [ ] Address review issues
- [ ] add the Django plugin for pylint: https://stackoverflow.com/questions/45135263/class-has-no-objects-member#comment89431284_47343542

2021-03-16 12:31 UTC, jcmatese commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
Yes, my preference would actually be to use the HMDB columns as the primary systematic/reference for the compound table, with the lab's 'Name' been a preferred_name or lookup-synonym (or both).  I had forgotten about the citrate/isocitrate detection ambiguity.  My preference is to not go this route [just one "Name", the lab's], and accept this ambiguous compound naming because of instrument detection limitations...  Also see this [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5734093/) , in the section **5.3. Peak Misidentification** **5.3.1. Isomers** on ~ page 7

2021-03-16 15:18 UTC, lparsons commented on CONTRIBUTING.md
> +    python manage.py runserver &
You can run it in the background, but doesn't that just make it more difficult to stop? Not a big issue, just curious what benefit this has that I might be missing.

2021-03-16 15:18 UTC, lparsons commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
Perhaps the ignores could be set in the config files? I'll investigate.

2021-03-16 15:44 UTC, lparsons commented on CONTRIBUTING.md
> +    markdownlint --ignore .venv "*.md"
`markdownlint .` seems to suffice. It ignores directores starting with a dot `.` by default and looks for `*.md` files by default as well.

2021-03-16 15:45 UTC, lparsons commented on CONTRIBUTING.md
> +    flake8 --exclude .venv
Adding `.venv` to the `.flake8` seems to work, allowing `flake8 .` to work.
```
exclude = .venv
```

2021-03-16 15:47 UTC, lparsons commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
This seems like more of PITA, though doing this seems simpler, atm. Having this built into the editor is even better, though, imho, but that's personal preference for the developer.
```
pylint TraceBase/ DataRepo/ *.py
```

Also, just an FYI, while testing `pylint`, using the `-r y` for a full report was handy.

2021-03-16 15:53 UTC, jcmatese commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
Also, if this is actually the protocol people wish for all contributing work (FIVE distinct linters?), then we should probably have a wrapper script for all these.  My opinion is that this is overkill, on the linting front, and would prefer simpler contributing protocols that everyone could live with.

2021-03-16 16:13 UTC, lparsons commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
Yeah, it can be a pain to start out with, esp. when we haven't established formatting just yet. I will say, there is generally no reason to run them manually. I either run them in my editor, or simply have GitHub run them for the rare stuff (css, etc.) they all run in my editor. In fact, there is no need to run them locally at all, they simply enforce formatting. If one follows the formatting conventions, then there should be no issues.

`pylint` and `flake8` are pretty standard. I admit that `isort` and `black` are a bit new, but given that they fix things automatically, shouldn't be too big a deal. 

We can turn linting off for some other formats if need be, (and might have to at least disable errors for `.html`, which is a shame (htmlhint issues with Django templates)[https://github.com/htmlhint/HTMLHint/issues/223] ). That said, I think things like standard formatting of CSS and Markdown isn't too hard to do and we can let GitHub catch the issues if they come up.

2021-03-16 16:13 UTC, hepcat72 commented on CONTRIBUTING.md
> +    python manage.py runserver &
I've never had a problem using `fg`.  I just like to be able to use the terminal when the server is running.  I put it there for copy/paste convenience.  That's just my MO.  I can take it out if you'd prefer it not be there.

2021-03-16 16:15 UTC, lparsons commented
The css linting issue seems like a pain. I can see a couple of options going forward:
1. Ignore the linting errors on "downloaded" or "standard" files by adding them to an ignore list, and use the linting rules for our own custom css
2. Fixing the downloaded files 
3. Choosing another standard style that conforms more closely.

The HTML linting also might need to addressed with config. Not sure of our options, but perhaps `DISABLE_ERRORS` would work. The issue seems to be [support for the templates](https://github.com/htmlhint/HTMLHint/issues/223) (which aren't simple html files).

2021-03-16 16:27 UTC, hepcat72 commented on CONTRIBUTING.md
> +    markdownlint --ignore .venv "*.md"
- [ ] Change to `markdownlint .`

2021-03-16 16:29 UTC, hepcat72 commented on CONTRIBUTING.md
> +    flake8 --exclude .venv
- [ ] Add `.venv` to `.flake8`
- [ ] Change contrib to `flake8 .`

2021-03-16 16:31 UTC, lparsons commented on CONTRIBUTING.md
> +    python manage.py runserver &
Sure, you can use that terminal then, but why not just have more than one? I always have a bunch running. They are usually in tmux, but most terminal programs let you split things up, some are even pretty fancy about it. Anyway, no big deal, just seems like an extra bit of complication to me, but doesn't matter much. I was more curious about how it worked. Do you still get all the logging, etc.?

2021-03-16 16:32 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
I agree with the wrapper suggestion, though I believe there is a real measurable benefit from linting that I believe you are discounting.

2021-03-16 16:35 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
> ```
> pylint TraceBase/ DataRepo/ *.py
> ```

This suggestion leaves out the check on `DataRepo/management/commands/load_compound_data.py`

2021-03-16 16:37 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
And considering where scripts might be added, it seems better to be comprehensive.  While I don't like having to use `*/*/*/*.py */*/*.py */*.py *.py` to achieve that comprehensiveness, I'd be fine with the change as long as we're aware of the manual effort to get the linting we want.

2021-03-16 16:49 UTC, hepcat72 commented on DataRepo/management/commands/load_compound_data.py
> +            cpd.save()
I'm not sure how much effort we should put into `load_compound_data.py`, as I consider it a one-off, and potentially useful to keep as starting point for a script we end up with, but I like the suggestion.  Since none of us are experts in Django here, I should point out that this script was grabbed from the linkedin tutorial's class materials and modified for use in this case, and I primarily used it to help aid the implementation of the interface with real data.  Given that fact, perhaps the script should either be removed or put into another directory whose name indicates its impermanence?

2021-03-16 16:55 UTC, hepcat72 commented
> I think this is a good start, and I don't want to "block" it, as you can't break what doesn't exist. That being said, going forward I think the compound model's name-conventions might need to be tweaked (unless we are resolving to just use the lab's 'Name', and they **all** must use the same names), and possibly use a "update-or-create" methodology (though that could be a separate script in the future).

I'm unclear what you're referring to here.  Are you referring to the field names, the class name ("Compound"), or the site name ("TraceBase")?  And what do you mean by "they **all** must use the same names"?  Are you referring to the column name row when they create a tsv?  If that's the case, I don't know that this is a script we would expect them to use.  I stated this in another comment, but I'm not sure of the order in which you will read them, so I consider it a one-off.  It was just to aid development of the other components.

2021-03-16 16:58 UTC, hepcat72 commented on DataRepo/models.py
> +    formula = models.CharField(max_length=256)
This is out of scope for the issue this PR resolves.  Please refer to the issue: #10.  That said, it's a good discussion to have, so I think we should discuss it, though I'm not sure if that should be in an issue, in a meeting, or just hold off all together until a refevent issue gets created.  We can discuss in the meeting.

2021-03-16 17:04 UTC, hepcat72 commented on DataRepo/management/commands/load_compound_data.py
> +            cpd.name    = row['Name']
The column in the file has compound names: "Valine", "Leucine", etc.  I think that that's inferred from the issue description (#10).  And this code is parsing that file.  `cpd.name` is the field I created in the database, as indicated in the issue.  I don't think that the issue was intended to establish the final field names in the database.  We can easily change it.  Note, I did not mean to make decisions on what the database fields would be called.

2021-03-16 17:04 UTC, jcmatese commented
> > I think this is a good start, and I don't want to "block" it, as you can't break what doesn't exist. That being said, going forward I think the compound model's name-conventions might need to be tweaked (unless we are resolving to just use the lab's 'Name', and they **all** must use the same names), and possibly use a "update-or-create" methodology (though that could be a separate script in the future).
> 
> I'm unclear what you're referring to here. Are you referring to the field names, the class name ("Compound"), or the site name ("TraceBase")? 

The compound class' solitary Name attribute, with no provision for other names (either systematic or synonymous).

>And what do you mean by "they **all** must use the same names"? 

Because there is not provision for other names in the database model, currently **all lab members** must use the Name defined and loaded initially in this script.

>Are you referring to the column name row when they create a tsv? 

Yes, 'Name' vs 'NAME' vs any other possible synonym that might describe a metabolite.

>If that's the case, I don't know that this is a script we would expect them to use. I stated this in another comment, but I'm not sure of the order in which you will read them, so I consider it a one-off. It was just to aid development of the other components.

Yes, I understand that the loading script is a one-off, but the solitary compound.name attribute (as currently modeled) will require that all subsequently data loaded must match that initial and sole compound.name.

2021-03-16 17:09 UTC, hepcat72 commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
I think this PR code review demonstrates the need for implementing issue templates that would clarify the purpose of the issue/PR, because I think we're getting out of context on this review.  These are all necessary conversations to have, albeit out of the scope of this PR.  I will create an issue for creating issue/PR templates.

- [ ] Create an issue for issue/PR templates

2021-03-16 17:29 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
> Yeah, it can be a pain to start out with, esp. when we haven't established formatting just yet. I will say, there is generally no reason to run them manually. I either run them in my editor, or simply have GitHub run them for the rare stuff (css, etc.) they all run in my editor. In fact, there is no need to run them locally at all, they simply enforce formatting. If one follows the formatting conventions, then there should be no issues.
> 
> `pylint` and `flake8` are pretty standard. I admit that `isort` and `black` are a bit new, but given that they fix things automatically, shouldn't be too big a deal.
> 
> We can turn linting off for some other formats if need be, (and might have to at least disable errors for `.html`, which is a shame (htmlhint issues with Django templates)[https://github.com/[htmlhint/HTMLHint/issues/223](https://github.com/htmlhint/HTMLHint/issues/223)] ). That said, I think things like standard formatting of CSS and Markdown isn't too hard to do and we can let GitHub catch the issues if they come up.

If I don't need to run them, why do I have linting errors on the PR?  What do you suggest I need to fix?

2021-03-16 19:58 UTC, jcmatese requested changes
data update to match compound is 1 entity/accession of model

2021-03-16 19:58 UTC, jcmatese commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
```suggestion
citrate 	 C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
isocitrate	C6H8O7	191.01973	13.98	HMDB0000193	Isocitric acid	C6H8O7	192.1235	192.02700261	OC(C(CC(O)=O)C(O)=O)C(O)=O	ODBLHEXUDAPZAU-UHFFFAOYSA-N
```

2021-03-16 20:20 UTC, hepcat72 commented
> > Not sure what to do about these pylint errors I get:
> > ```
> > $ pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
> > ************* Module commands.load_compound_data
> > DataRepo/management/commands/load_compound_data.py:20:11: E1101: Class 'Compound' has no 'objects' member (no-member)
> > ************* Module DataRepo.views
> > DataRepo/views.py:8:11: E1101: Class 'Compound' has no 'objects' member (no-member)
> > DataRepo/views.py:14:14: E1101: Class 'Compound' has no 'objects' member (no-member)
> > DataRepo/views.py:15:11: E1101: Class 'Compound' has no 'DoesNotExist' member (no-member)
> > ```
> 
> I think you might want to add the Django plugin for pylint: https://stackoverflow.com/questions/45135263/class-has-no-objects-member#comment89431284_47343542

I don't get the errors if I do:

```
pylint --generated-members=objects,DoesNotExist --ignore .venv */*/*/*.py */*/*.py */*.py *.py
```

We could add this to .pylintrc:

```
# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E1101 when accessed. Python regular
# expressions are accepted.
generated-members=objects,DoesNotExist
```

2021-03-16 21:45 UTC, hepcat72 commented on CONTRIBUTING.md
> +    python manage.py runserver &
- [ ] Remove the ampersand from the documentation

It's funny, to me *not* having the ampersand is the extra bit of complication.  But I admit it seems unclean, doc-wise, so I will remove it.

2021-03-16 21:51 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
I changed it to `pylint TraceBase/ DataRepo/ DataRepo/management/commands/ *.py` so as to include all of the python scripts.

2021-03-16 21:52 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
Resolve if that's OK.

2021-03-16 22:01 UTC, hepcat72 commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
Did we get the tsv from the lab and has it been modified after we received it?  This data was just for me to test the code I was writing.  Perhaps I should take this file out of the PR and make sure to *not* end up with data in the database as a side-effect of this effort/PR, because I don't think this is a decision/change that is something that should affect the database development.  However, even if this is a part of this PR, I don't expect the data entered to persist or to be the basis for the coming schema development.  We can just wipe all this out when we get there.  So unless there is any objection, I'll just leave the file and the fields in the load script as they are. If they get changed, that should happen in another issue/PR.  What might have helped with this review was if we'd had an issue/work approval process, so this would have been addressed before this work was done.

2021-03-16 22:07 UTC, hepcat72 commented
Regarding the build errors, for some reason, I thought there *hadn't* been a build error?  But I see this in the github actions TraceBase Tests under the psycopg2 section of the build:

```
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libpython2.7 amd64 2.7.18-1~20.04
27  404  Not Found [IP: 52.154.174.208 80]
28 Err:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libpython2.7-dev amd64 2.7.18-1~20.04
29  404  Not Found [IP: 52.154.174.208 80]
30 Get:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libpython2-dev amd64 2.7.17-2ubuntu4 [7140 B]
31 Get:4 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python-is-python2 all 2.7.17-4 [2496 B]
32 Err:5 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python2.7-dev amd64 2.7.18-1~20.04
33   404  Not Found [IP: 52.154.174.208 80]
34 Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python2-dev amd64 2.7.17-2ubuntu4 [1268 B]
35 Get:7 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python-dev-is-python2 all 2.7.17-4 [1396 B]
36 Fetched 12.3 kB in 0s (34.4 kB/s)
37 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
38 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-dev_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
39 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-dev_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
40 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
41 Error: Process completed with exit code 100.
```

2021-03-16 22:26 UTC, lparsons commented
Probably try a rerun. Azure had downtime yesterday (see issues with Outlook).

Lance Parsons
Research Software Engineer
Lewis-Sigler Institute for Integrative Genomics
Princeton University
________________________________
From: Robert Leach ***@***.***>
Sent: Tuesday, March 16, 2021 6:07:23 PM
To: Princeton-LSI-ResearchComputing/tracebase ***@***.***>
Cc: Lance R. Parsons ***@***.***>; Review requested ***@***.***>
Subject: Re: [Princeton-LSI-ResearchComputing/tracebase] [WIP] Create model for Compound (#14)


Regarding the build errors, for some reason, I thought there hadn't been a build error? But I see this in the github actions TraceBase Tests under the psycopg2 section of the build:

Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libpython2.7 amd64 2.7.18-1~20.04
27  404  Not Found [IP: 52.154.174.208 80]
28 Err:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libpython2.7-dev amd64 2.7.18-1~20.04
29  404  Not Found [IP: 52.154.174.208 80]
30 Get:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libpython2-dev amd64 2.7.17-2ubuntu4 [7140 B]
31 Get:4 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python-is-python2 all 2.7.17-4 [2496 B]
32 Err:5 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python2.7-dev amd64 2.7.18-1~20.04
33   404  Not Found [IP: 52.154.174.208 80]
34 Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python2-dev amd64 2.7.17-2ubuntu4 [1268 B]
35 Get:7 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 python-dev-is-python2 all 2.7.17-4 [1396 B]
36 Fetched 12.3 kB in 0s (34.4 kB/s)
37 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
38 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/libpython2.7-dev_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
39 E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/p/python2.7/python2.7-dev_2.7.18-1~20.04_amd64.deb  404  Not Found [IP: 52.154.174.208 80]
40 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
41 Error: Process completed with exit code 100.


—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/14#issuecomment-800645296>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAE5QCFC35IF6MPS5ZTSHI3TD7JBXANCNFSM4ZDDEY5A>.

2021-03-16 22:48 UTC, hepcat72 commented
> The css linting issue seems like a pain. I can see a couple of options going forward:
> 
> 1. Ignore the linting errors on "downloaded" or "standard" files by adding them to an ignore list, and use the linting rules for our own custom css
> 2. Fixing the downloaded files
> 3. Choosing another standard style that conforms more closely.
> 
> The HTML linting also might need to addressed with config. Not sure of our options, but perhaps `DISABLE_ERRORS` would work. The issue seems to be [support for the templates](https://github.com/htmlhint/HTMLHint/issues/223) (which aren't simple html files).

I've been searching for where/how to specify files to ignore and I've not yet found it...  Is there a .super-linter config file we can create or something?

2021-03-17 13:02 UTC, jcmatese commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
yes, we received a [Maven-style tsv from the users](https://drive.google.com/file/d/18Gyz4eaHSrsvU1YJlZYnzb2WDVV7u97K/view?usp=sharing) which I then tried to augment with ["official" data from HMDB](https://docs.google.com/spreadsheets/d/1hII05TaluhubwFLfrTkE6Y2QpKAFUs3OlK2UdrBIqr0/edit?usp=sharing), primarily converting the user's names to HMDB names, by eye, and copying the 30 lines over.   This was primarily to get the requested accession, but in my opinion, all the HMDB attribute should be stored.  [The original augmented/modified file](https://docs.google.com/spreadsheets/d/1tS6C1HEPA-aUQKtYVoH7t4mM7HVyEQPJ8H_TAlpglkA/edit?usp=sharing) had issues, though because the users were not actually identifying compounds, but rather labeling peaks.  For that line (24), the peak was labeled as a pair of isomers that **does not comport with our model** (they are _2 separate compounds_).  I was just trying to correct the faulty data, to make It agree with our model.  It is fine to leave it in the PR, but better for it to be accurate to the model you are loading.

2021-03-17 13:55 UTC, hepcat72 commented on TraceBase Augmented Compopund List from jcm.tsv
> +citrate/isocitrate	C6H8O7	191.01973	13.98	HMDB0000094	Citric acid	C6H8O7	192.1235	192.02700261	OC(=O)CC(O)(CC(O)=O)C(O)=O	KRKNYBCHXYNGOX-UHFFFAOYSA-N
I dispute none of what you said.  My only point is it's not relevant to the issue this PR resolves.  The issue does not say that the fields are limited to this set of 4.  In fact, it refers to it as a "basic" model, which I infer to mean that it will grow, and I think the intention here was to quickly create either undisputed fields and a table or to simply get the team familiar with the code relevant to accomplish a basic Django task and that any changes to it would be easy to address in subsequent issues/PRs.  So I am resolving this issue.  If you dispute my interpretation of the issue, or would like me to remove the tsv from the branch, please un-resolve and communicate that.

2021-03-17 15:14 UTC, jcmatese approved these changes

2021-03-17 18:02 UTC, hepcat72 commented on CONTRIBUTING.md
> +    pylint --ignore .venv */*/*/*.py */*/*.py */*.py *.py
I will resolve.  Re-open if you disagree.

2021-03-18 18:32 UTC, lparsons requested changes
Nice job Rob, quite a more to this than I'd anticipated! Tackled CSS, templates, external URLs, all on top of the model.

I did make some small tweaks and pushed them to address pylint not recursing into the `DataRepo/management` directory and also to use the Super Linter defaults for `.htmlhintrc` (though I admit I don't have good reason to use those other than someone configuring Super Linter chose them).

I have two blocking requests and one minor, non-blocking suggestion.

Blocking:

1. I'd like to make sure that with new models, we add tests. In this case, just something very simple like creating a Compound and testing that it exists and has the same name might suffice.
2. I think it would be reasonable and prudent to require a unique HMDB ID for each Compound, though perhaps I'm wrong here. @jcmatese or @fkang-pu please weigh in here if my assumptions aren't correct about this.

Non-Blocking:

1. If we move the URL generation for HMDB to the Compound model itself, it simplifies use in templates (and anywhere else we might want it).

2021-03-18 18:32 UTC, lparsons commented on DataRepo/models.py
> +    hmdb_id = models.CharField(max_length=11, blank=True)
Blocking: I think it's reasonable to allow only one row per HMDB ID to avoid possible confusion, therefor I suggest adding `unique=True`. I would also argue that we should require that an HMDB ID be set, to avoid confusion, therefore we could remove the `blank=True`.

2021-03-18 18:32 UTC, lparsons commented on DataRepo/templates/compound_detail.html
> +    {% if cpd.hmdb_id %}
If we require `hmdb_id`, then this if block isn't necessary.

2021-03-18 18:32 UTC, lparsons commented on DataRepo/templates/compound_detail.html
> +        <p><a href="{{ HMDB_CPD_URL }}/{{ cpd.hmdb_id }}" target="_blank">{{ cpd.hmdb_id }}</a></p>
Non-blocking: Adding the creation of the URL in the Compound class would simplify it's use in templates and consolidate the logic to the Compound class.

2021-03-18 18:32 UTC, lparsons commented on DataRepo/templates/home.html
> +                        <p><a href="{{ HMDB_CPD_URL }}/{{ cpd.hmdb_id }}" target="_blank">{{ cpd.hmdb_id }}</a></p>
Non-blocking: Same comment as in `compound_detail.html`, adding the creation of the URL in the Compound class would simplify it's use in templates and consolidate the logic to the Compound class.

2021-03-18 18:32 UTC, lparsons commented on DataRepo/views.py
> +        request, "home.html", {"cpds": cpds, "HMDB_CPD_URL": settings.HMDB_CPD_URL}
Non-blocking: Moving the URL generation to the Compound model would also allow us to remove `HMDB_CPD_URL` here.

2021-03-18 18:32 UTC, lparsons commented on DataRepo/views.py
> +        {"cpd": cpd, "HMDB_CPD_URL": settings.HMDB_CPD_URL},
Non-blocking: Moving the URL generation to the Compound model would also allow us to remove `HMDB_CPD_URL` here.

2021-03-18 18:42 UTC, jcmatese commented on DataRepo/models.py
> +    hmdb_id = models.CharField(max_length=11, blank=True)
Yes, I think that may be correct, if defined, but _if_ it it nullable, the rules _might_ be in odds with one another? (nullable vs. unique)  I think we could _probably_ commit to it being required, but don't feel too strongly.

2021-03-18 18:59 UTC, hepcat72 commented on DataRepo/models.py
> +    hmdb_id = models.CharField(max_length=11, blank=True)
I'm fine to change, but let me see if I can break it...

Weak argument: As we mentioned before, this table is for compounds that *exist*, as opposed to compounds that occur in the same position on a trace (e.g. citrate vs isocitrate).  If we take that (admittedly) to its finest granularity, then we break the ability to store stereo-isomers separately (which would presumably link to the same HMDB ID).

Slightly stronger argument: I usually develop code under the principle of "don't get in the way".  If someone wants to add a compound, but they don't have the HMDB ID, or they want a couple of abstract entries for an unknown compound with different attributes, in either case, they would not have an HMDB ID.

I don't have a **strong** argument.  Just trying to think this through a bit further.

2021-03-18 19:32 UTC, jcmatese commented on DataRepo/models.py
> +    hmdb_id = models.CharField(max_length=11, blank=True)
Not arguing for either direction, but I think HMDB has stereoisomers as separate accessions (although I have no way of know if they do this uniformly)
example, 5 of 9 stereoisomers of inositol:
https://hmdb.ca/metabolites/HMDB0000211
https://hmdb.ca/metabolites/HMDB0240209
https://hmdb.ca/metabolites/HMDB0006088
https://hmdb.ca/metabolites/HMDB0062138
https://hmdb.ca/metabolites/HMDB0240210

2021-03-18 21:03 UTC, hepcat72 commented on DataRepo/views.py
> +        request, "home.html", {"cpds": cpds, "HMDB_CPD_URL": settings.HMDB_CPD_URL}
- [ ] Create a Compound class variable for the hmdb URL

2021-03-18 21:03 UTC, hepcat72 commented on TraceBase/urls.py
> +    path("DataRepo/<int:cpd_id>/", views.compound_detail, name="compound_detail"),
Incidentally, I learned that (I don't think) the "name" is something users see in the GUI or page title.  It's really a shortcut was to refer to pages, hence to case change.

2021-03-18 21:11 UTC, hepcat72 commented on DataRepo/models.py
> +    hmdb_id = models.CharField(max_length=11, blank=True)
Done

2021-03-18 21:12 UTC, hepcat72 commented on DataRepo/templates/home.html
> +                        <p><a href="{{ HMDB_CPD_URL }}/{{ cpd.hmdb_id }}" target="_blank">{{ cpd.hmdb_id }}</a></p>
Done.

2021-03-18 21:28 UTC, hepcat72 commented
> Nice job Rob, quite a more to this than I'd anticipated! Tackled CSS, templates, external URLs, all on top of the model.
> 
> I did make some small tweaks and pushed them to address pylint not recursing into the `DataRepo/management` directory and also to use the Super Linter defaults for `.htmlhintrc` (though I admit I don't have good reason to use those other than someone configuring Super Linter chose them).
> 
> I have two blocking requests and one minor, non-blocking suggestion.
> 
> Blocking:
> 
> 1. I'd like to make sure that with new models, we add tests. In this case, just something very simple like creating a Compound and testing that it exists and has the same name might suffice.
> 2. I think it would be reasonable and prudent to require a unique HMDB ID for each Compound, though perhaps I'm wrong here. @jcmatese or @fkang-pu please weigh in here if my assumptions aren't correct about this.
> 
> Non-Blocking:
> 
> 1. If we move the URL generation for HMDB to the Compound model itself, it simplifies use in templates (and anywhere else we might want it).

Let me spitball and see if I am tracking what you're thinking, test-wise. You're suggesting I write something like:
```
            from DataRepo.models import Compound
            cpd = Compound()
            cpd.name = "testname"
            cpd.formula = "test formula"
            cpd.hmdb_id = "TEST0000001"
            cpd.save()
            cpd2 = Compound.objects.get(name="testname")
```
I'll have to investigate a python testing framework to evaluate the result, but is that the sort of test you're thinking of?
I could also add tests to make sure not adding a formula or hmdb_id fails - and that adding duplicate values for them fails.

- [ ] Add test(s) to confirm the model

2021-03-18 21:44 UTC, hepcat72 commented on DataRepo/views.py
> +        {"cpd": cpd, "HMDB_CPD_URL": settings.HMDB_CPD_URL},
Done, awaiting push.

2021-03-18 21:46 UTC, hepcat72 commented on DataRepo/views.py
> +        request, "home.html", {"cpds": cpds, "HMDB_CPD_URL": settings.HMDB_CPD_URL}
Done, awaiting push.

2021-03-18 21:50 UTC, hepcat72 commented
I'm going to assume it's OK to push some of the changes resulting from @lparsons's review (and before John/Fan's review).  All I have left from Lance's review is the tests, which I need to learn a bit about.  I'll probably do that tomorrow and spend the last few minutes today reviewing the status of other efforts.

2021-03-19 01:03 UTC, lparsons commented
@hepcat72 I pushed a commit that added some simple tests, moves the HMDB URL to the Compound model file, and adds a property to Compound to retrieve the url for a specific compound.

Moving the URL to the compound file consolidates the information about Compounds into one place. 

The tests are very basic, but ensure we can create and retrieve Compounds from the database. We can add more sophisticated tests as we move forward.

2021-03-19 13:22 UTC, jcmatese approved these changes
I think this looks good as a starting point.  I have some question about the a template  named `DataRepo/templates/home.html` being a list of compounds, but I am sure all this will shift over time as the project gets fleshed out.

2021-03-19 14:05 UTC, hepcat72 commented
> @hepcat72 I pushed a commit that added some simple tests, moves the HMDB URL to the Compound model file, and adds a property to Compound to retrieve the url for a specific compound.
> 
> Moving the URL to the compound file consolidates the information about Compounds into one place.
> 
> The tests are very basic, but ensure we can create and retrieve Compounds from the database. We can add more sophisticated tests as we move forward.
> 
> Also, with that commit, I believe I'm ready to approve. Totally fine if you want to comment on any changes though. I didn't mean to step on toes, but I just wanted to get my feet wet in the code a bit.

Well, my solution to this had been a compromise, but ok.  I still don't like the URL being hard-coded, but like I said initially, I'm fine either way.

2021-03-19 14:14 UTC, lparsons approved these changes
Looking good to me. I believe this PR now addresses everything in the milestone (#10, #11, #12, and #13). Generally, it would be nice to break apart model stuff from view/controller stuff, but since this is for just a small simple table, the PR isn't terribly large here. Great start to the project!

2021-03-19 14:18 UTC, hepcat72 commented
> I think this looks good as a starting point. I have some question about the a template named `DataRepo/templates/home.html` being a list of compounds, but I am sure all this will shift over time as the project gets fleshed out.

Yeah, it will certainly change.  It's essentially a placeholder at this point.  The home template was pretty much grabbed directly from the linkedin learning Django tutorial example, though I do actually like that the home page gets straight down to business and shows what it's got without having to figure out where to go to see what's in the database.  Once there's more than one type of thing to view/do, then such a browse interface would move inward, but I don't have a solid enough grasp yet, GUI-wise, of the scope of the use cases - I just haven't tried to visualize it yet.  I should spend some time with the requirements and draft a conceptual design doc.

2021-03-19 14:23 UTC, hepcat72 commented on DataRepo/tests.py
> +        )
I'm guessing the TestCase framework leaves no traces in the database.  Thanks for adding these tests.  It would have taken me some time to find and read up on the test stuff.

2021-03-19 14:25 UTC, lparsons commented
@jcmatese 
> I think this looks good as a starting point. I have some question about the a template named `DataRepo/templates/home.html` being a list of compounds, but I am sure all this will shift over time as the project gets fleshed out.

The home page being a list of compounds makes sense at the moment, since that's all the web application is right now. However, I agree that going forward we'll need some better organization. Perhaps we should start thinking about a menu at the top for main components, for example: Compounds, Samples, Experiments, Runs, Tracers.

@rleach
> Well, my solution to this had been a compromise, but ok. I still don't like the URL being hard-coded, but like I said initially, I'm fine either way.

Very true, and I'm kinda torn between the better way, but I'd be surprised if the URL changes during the lifetime of this project... ;-) Either way, great job pulling this all together Rob. I know it's a lot of new stuff. Also, in my haste last night, I neglected to point out some info on Django testing that I found useful:
* [Mozilla Django Tutorial Part 10: Testing a Django web application](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing)
* [Real Python's Testing in Django (Part 1) – Best Practices and Examples](https://realpython.com/testing-in-django-part-1-best-practices-and-examples/)

2021-03-19 14:26 UTC, lparsons commented on DataRepo/tests.py
> +        )
Sure thing. Yes, the test framework creates and entirely new database, so no side effects. I posted a couple of links that I found helpful. I meant to do that last night, but ended up having to wrap up kinda quickly and forgot.

2021-03-19 14:31 UTC, fkang-pu approved these changes
Looks good to me for the 1st round. I also have a question about DataRepo/templates/, like John commented.  I have webpage prototypes in my mind, which you may disagree.  
Example for my prototypes: home.html would have a short list (e.g. Compounds, Animals, Samples, Experiments ... with hyperlinks); then click "Compounds" would lead to compound.html ( whole list of compound names; http://127.0.0.1:8000/DataRepo/compound); click a compound name would lead to compound detail (e.g. http://127.0.0.1:8000/DataRepo/compound/1/).  right now, the compound detail URL for id=1 is http://127.0.0.1:8000/DataRepo/1.  After adding models for animal/sample, click "Animals" from home.html may lead to a list of all animals (or animals for the last 12 months), etc.

2021-03-19 14:31 UTC, fkang-pu commented on DataRepo/models.py
> +    id = models.AutoField(primary_key=True)
Just a comment, no need to change code. Although Django can create a primary key for id column automatically if you don't specify primary key for the model, I like your practice to define "id" column for primary key explicitly. I prefer we stick to same practice when adding other models.

2021-03-19 14:52 UTC, hepcat72 commented on DataRepo/models.py
> +    id = models.AutoField(primary_key=True)
There was a reason why I did the AutoField that's escaping me ATM, but thanks.  I also like the explicit field definition being there.

2021-03-19 15:13 UTC, hepcat72 commented on DataRepo/tests.py
> +        )
So let me take a wild stab: `python3 manage.py test`?

2021-03-19 15:29 UTC, lparsons commented
> Looks good to me for the 1st round. I also have a question about DataRepo/templates/, like John commented. I have webpage prototypes in my mind, which you may disagree.
> Example for my prototypes: home.html would have a short list (e.g. Compounds, Animals, Samples, Experiments ... with hyperlinks); then click "Compounds" would lead to compound.html ( whole list of compound names; http://127.0.0.1:8000/DataRepo/compound); click a compound name would lead to compound detail (e.g. http://127.0.0.1:8000/DataRepo/compound/1/). right now, the compound detail URL for id=1 is http://127.0.0.1:8000/DataRepo/1. After adding models for animal/sample, click "Animals" from home.html may lead to a list of all animals (or animals for the last 12 months), etc.

Those sound pretty good @fkang-pu! Would you want to put together some rough mockups of those? Nothing fancy, just rough layout is fine. We could then start getting some feedback from the lab about them while we work on the backend stuff.

2021-03-19 15:42 UTC, merged

2021-03-19 15:53 UTC, fkang-pu commented
> > Looks good to me for the 1st round. I also have a question about DataRepo/templates/, like John commented. I have webpage prototypes in my mind, which you may disagree.
> > Example for my prototypes: home.html would have a short list (e.g. Compounds, Animals, Samples, Experiments ... with hyperlinks); then click "Compounds" would lead to compound.html ( whole list of compound names; http://127.0.0.1:8000/DataRepo/compound); click a compound name would lead to compound detail (e.g. http://127.0.0.1:8000/DataRepo/compound/1/). right now, the compound detail URL for id=1 is http://127.0.0.1:8000/DataRepo/1. After adding models for animal/sample, click "Animals" from home.html may lead to a list of all animals (or animals for the last 12 months), etc.
> 
> Those sound pretty good @fkang-pu! Would you want to put together some rough mockups of those? Nothing fancy, just rough layout is fine. We could then start getting some feedback from the lab about them while we work on the backend stuff.

@lparsons Will work on it. Hopefully I can share some layouts early next week.