Load Sample and Animal Tables command
Princeton-LSI-ResearchComputing/tracebase pull request #144
Opened 2021-07-20 20:34 UTC by jcmatese

## Summary Change Description

Split obob_sample example file into samples and animals files
Modify header of new example files to match suggested templates
Add new YAML file corresponding to these header changes
Add new management command load_animal_and_sample_tables targeted at these 2 new example files
Utilize `pandas` `merge` to join these 2 new example files
Modify test_models to use the new command
Tweak handling of animal treatment in `utils.load_sample_table` for `pandas` data filtering

## Affected Issue Numbers

- Resolves #136 

## Code Review Notes

- I tried not to change anything in existing examples or commands, in case they are needed for "fall-back" scenarios.
- Although all old tests pass using the call command on the new command, I did not explicitly compare the old command results with the new command results by eye, or another method. [i.e. first the using with `pandas.merge`, so I hope it was used "correctly"]
- Also, `pandas` reads in the files into different objects than `csv.DictReader`, which I then had to cast into a record list, which I hope is equivalent.
- Also, `pandas` converts missing values to `NaN` or `""` , which also _might_ be different than `csv.DictReader` but it could also be that I added a "Animal Treatment" column to the example file which was entirely null, which cause a new error to bubble up in the decision to call `Protocol.retrieve_or_create_protocol`, and _may_ affect other null values in these user-supplied tables. 

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-07-20 20:38 UTC, jcmatese commented
Just noting that superlinter passed it locally.  Uncertain about the EDITORCONFIG issues....

2021-07-20 20:52 UTC, jcmatese commented
Note: I did not edit the code, but I was was wondering whether the indenting on the `created` logic might be "off"

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/78283aff0c84606f9fb26d1b15bd0b52f778c06b/DataRepo/utils.py#L129-L153

I am not entirely certain, but it appears that whether the animal was `created` or not, the code might be updating values of the instance?  Is that what we want?

2021-07-21 13:43 UTC, lparsons commented
> Just noting that superlinter passed it locally. Uncertain about the EDITORCONFIG issues....

That's odd, can you post what command/script you used to run it locally? I'm guessing a config var was different that what is set in `.github/workflows/superlinter.yaml`.

2021-07-21 13:48 UTC, jcmatese commented
> > Just noting that superlinter passed it locally. Uncertain about the EDITORCONFIG issues....
> 
> That's odd, can you post what command/script you used to run it locally? I'm guessing a config var was different that what is set in `.github/workflows/superlinter.yaml`.

I just click the "play" button in the docker dashboard.  I think the original launch was probably cribbed from the CONTRIBUTING doc.  I will check out the original launch script when I switch computers...

2021-07-21 17:16 UTC, jcmatese commented
> > > Just noting that superlinter passed it locally. Uncertain about the EDITORCONFIG issues....
> > 
> > 
> > That's odd, can you post what command/script you used to run it locally? I'm guessing a config var was different that what is set in `.github/workflows/superlinter.yaml`.
> 
> I just click the "play" button in the docker dashboard. I think the original launch was probably cribbed from the CONTRIBUTING doc. I will check out the original launch script when I switch computers...

This is the script I use to launch the initial docker image

```
$ cat ../superlinter_docker.sh 
#!/usr/bin/env sh
    docker pull github/super-linter:latest

    docker run \
        -e FILTER_REGEX_EXCLUDE="(\.pylintrc|migrations|static\/bootstrap.*)" \
        -e LINTER_RULES_PATH="/" \
        -e IGNORE_GITIGNORED_FILES=true \
        -e RUN_LOCAL=true \
        -v ~/dev/tracebase/:/tmp/lint github/super-linter
```

and then I just hit the play button in docker desktop for several weeks after that, assuming that superlinter does not change that much (perhaps that is a bad assumption)?  I just find the `docker pull` step to be a little slow repeated daily screens

2021-07-21 18:57 UTC, lparsons commented
> This is the script I use to launch the initial docker image
> 
> ```
> $ cat ../superlinter_docker.sh 
> #!/usr/bin/env sh
>     docker pull github/super-linter:latest
> 
>     docker run \
>         -e FILTER_REGEX_EXCLUDE="(\.pylintrc|migrations|static\/bootstrap.*)" \
>         -e LINTER_RULES_PATH="/" \
>         -e IGNORE_GITIGNORED_FILES=true \
>         -e RUN_LOCAL=true \
>         -v ~/dev/tracebase/:/tmp/lint github/super-linter
> ```

That looks to be correct to me. A couple of things are different though. One is that github was getting v3 of superlinter, and that pull get's the latest, which is now v4. Another difference is that GitHub checks the code as it is in the git branch, while locally, I believe it checks the working copy, which could differ. Either way, it is correct to complain about the missing new lines.

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/78283aff0c84606f9fb26d1b15bd0b52f778c06b/.github/workflows/superlinter.yml#L20-L28

> and then I just hit the play button in docker desktop for several weeks after that, assuming that superlinter does not change that much (perhaps that is a bad assumption)? I just find the `docker pull` step to be a little slow repeated daily screens

The docker pull can be a pain, though it usually doesn't occur more than once a day for me. It is pulling new images because there _are_ changes. When there are no changes, that steps just skips by quickly. 

I did discover that there is a new slim image for super linter to address that in v4. See https://github.com/github/super-linter#slim-image. Might be worth moving to that since I don't think we need any of the linters they eliminated.

2021-07-21 19:42 UTC, hepcat72 approved these changes

2021-07-21 19:42 UTC, hepcat72 commented on DataRepo/example_data/sample_and_animal_tables_headers.yaml
> +ANIMAL_DIET:
Q. Are Animal age, sex, & diet no longer needed?

2021-07-21 19:42 UTC, hepcat72 commented on DataRepo/management/commands/load_animal_and_sample_tables.py
> +        )
Q. I imagine this are fairly static from run-to-run?  I see that default data is provided below.  I think it may be useful to infrequent users to mention the existence of a default in the help text?

2021-07-21 19:45 UTC, fkang-pu approved these changes

2021-07-21 19:56 UTC, jcmatese commented on DataRepo/example_data/sample_and_animal_tables_headers.yaml
> +ANIMAL_DIET:
I would not say they are not longer needed, but rather that they were not provided in that one example, I think.

2021-07-21 19:57 UTC, jcmatese commented on DataRepo/management/commands/load_animal_and_sample_tables.py
> +        )
Probably.  I can mentioned their location as a re-use or suggested template.

2021-07-22 14:49 UTC, lparsons requested changes
Nice job John, quick and simple solution, and even learned a bit about Pandas in the process!

My one blocking issue is that we shouldn't have untested commands, so we should either add a test for `load_samples` (my preference) or remove the `load_samples` command entirely.

2021-07-22 14:49 UTC, lparsons commented on DataRepo/management/commands/load_animal_and_sample_tables.py
> +        f"Example usage : manage.py load_animal_and_sample_tables --sample-table-filename {example_samples}"
NB: To maintain consistency with the other commands, I would suggest renaming this command to `load_animals_and_samples`.

2021-07-22 14:49 UTC, lparsons commented on DataRepo/management/commands/load_animal_and_sample_tables.py
> +            keep_default_na=False,
Looks good to me, this reads missing values as they are and does not convert to `NaN`, which seems to match `DictReader`, at least in the cases I tested.

2021-07-22 14:49 UTC, lparsons commented on DataRepo/tests/test_models.py
> +            table_headers="DataRepo/example_data/sample_and_animal_tables_headers.yaml",
B: We should either test both `load_samples` and `load_animal_sample_tables` or get rid of `load_samples`. Maybe just test one with the `small_dataset` and just check that the Animal and Sample counts match expected.

2021-07-22 16:18 UTC, jcmatese commented on DataRepo/tests/test_models.py
> +            table_headers="DataRepo/example_data/sample_and_animal_tables_headers.yaml",
I am not certain this matches your requirement, but I believe load_samples remains in this test/call 
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/a8c5ab78a8717615aee45e60718d339f13616d5d/DataRepo/tests/test_models.py#L341-L350

2021-07-22 16:21 UTC, lparsons approved these changes

2021-07-22 16:37 UTC, jcmatese commented on DataRepo/management/commands/load_animal_and_sample_tables.py
> +        f"Example usage : manage.py load_animal_and_sample_tables --sample-table-filename {example_samples}"
renamed

2021-07-22 16:49 UTC, merged