Draft methods to retrieve tracer samples/peakdata
Princeton-LSI-ResearchComputing/tracebase pull request #186
Opened 2021-09-09 21:01 UTC by jcmatese

Added Sample.peak_data_queryset, with optional compound filter
Added Animal methods for serum sample(s) retrieval, and serum tracer peakdata
Added some rudimentary tests for the above

## Summary Change Description

These are methods I thought might be useful for a first-step on the road to fcirc (and related) serum data calculations.  They could probably be expanded on.

## Affected Issue Numbers

This does not resolve any issues, _per se,_ but add some methods that might be usefully employed in #43 (groundwork)

## Code Review Notes

If the naming or labeling of the methods can be improved, or you think they are not particularly useful, speak up (just a draft idea).  I just though they might be useful , prior to a subsequent calculation-based PR.

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-09-09 21:26 UTC, lparsons requested changes
I really like the idea of breaking the work into smaller chunks, it makes the code reviews and tests a lot easier to digest. A few blocking changes (missing test and misleading method name).

2021-09-09 21:26 UTC, lparsons commented on DataRepo/models.py
> +            print("Unexpected error:")
Comment: This seems unnecessary. It would simplify the code and do the same thing if we removed the try/except here.

2021-09-09 21:26 UTC, lparsons commented on DataRepo/tests/test_models.py
> +
Comment: There are quite a few assertions in the this "unit" test. If one fails, it might be a bit of work to sort out which thing is failing. While I don't think we have to have strictly one assert per test, striving towards that is makes the tests a bit easier to debug and follow, imho (reference: https://softwareengineering.stackexchange.com/a/171502/378539).

2021-09-09 21:26 UTC, lparsons commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
Blocking: This name is misleading, it doesn't actually return a queryset, but actually returns peak data objects.

2021-09-09 21:26 UTC, lparsons commented on DataRepo/models.py
> +            return None
Blocking: This condition should be tested

2021-09-09 22:29 UTC, hepcat72 approved these changes
I agree with Lance that there should be a test for the "no serum sample" case.  I am interested in the answer to the one question I asked. There may be something wrong there with the usage of `.lastest` on a duration field, but I don't know.  I don't have anything outside of what Lance created, so I will approve, pending the addressing of Lance's issues.

2021-09-09 22:29 UTC, hepcat72 commented on DataRepo/models.py
> +            )
Q. I know my comment here is not about code you wrote John and that it was just rearranged, but something strikes me as wrong here.  I cannot figure out what [`.latest`](https://docs.djangoproject.com/en/dev/ref/models/querysets/#latest) does when given a DurationField.  Does it grab the longest duration (infusion to collection)?  It's not clear to me from the docs, whose examples are dates.

2021-09-09 22:29 UTC, hepcat72 commented on DataRepo/models.py
> +            )
Also, I noted that latest can return unexpected results when the field its given can be null, as in the `time_collected` field... Maybe a filter should be used to filter out nulls.

2021-09-09 22:29 UTC, hepcat72 commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
Wait... I thought `.all()` [did return a queryset](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#all).  What am I missing?

2021-09-09 22:29 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        # soe zero length list
```suggestion
        # so zero length list
```

2021-09-10 13:57 UTC, jcmatese commented on DataRepo/models.py
> +            print("Unexpected error:")
I can remove it if you wish.  I though it would be alright to leave it as a placeholder/pattern for the unknown/unpredicted errors.

2021-09-10 13:59 UTC, hepcat72 commented on DataRepo/models.py
> +            )
Looking at this further, I found [an example](https://simpleisbetterthancomplex.com/tips/2016/10/06/django-tip-17-earliest-and-latest.html) that shows using `.filter` to eliminate null values:

```
Post.objects.filter(change_date__isnull=False).latest('change_date')
```

But I also think that maybe we need something like "max" (for the largest duration), like:

```
Book.objects.all().aggregate(Max('price'))
```

as seen in [these examples](https://docs.djangoproject.com/en/3.2/topics/db/aggregation/).

2021-09-10 14:01 UTC, lparsons commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
:facepalm: You are 100% correct, it does return a `queryset`. However, I still think the method name is confusing since using `all()` means the queryset gets evaluated and thus can no longer be filtered (via sql anyway).

2021-09-10 14:02 UTC, lparsons commented on DataRepo/models.py
> +            )
This seems outside the scope of the PR, so I created issue #188

2021-09-10 14:08 UTC, hepcat72 commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
I read that you can call `.filter()` on the return of `.all()` - it's just that the call gets delegated to Django's `get_queryset()` method, which is an inefficient way to code it, so I totally agree something should change here.

```
In [1]: from DataRepo.models import Animal

In [2]: Animal.objects.all().filter(name__icontains="x")
Out[2]: <QuerySet [<Animal: exp024c_M3>, <Animal: exp024c_M4>, <Animal: exp024c_M5>, <Animal: exp024f_M1>, <Animal: exp024f_M2>]>
```

2021-09-10 14:11 UTC, jcmatese commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
It is definitely confusing to me, because I had originally thought it returned a list of objects, and the initial works/commit actually _**had**_ everything postfixed with *`_list` instead of `_queryset`.  But then I wanted to do this somewhat arbitrary test(s) where I had thought to try an validate that retrieving the data from different methods returned the same data.

https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/5c28d72982d43bb38c2c520827ba20e9a8c42c59/DataRepo/tests/test_models.py#L433-L437

and my first naive attempt  `self.assertEqual(peakdata, peakdata2)` failed with
`AssertionError: <Quer[195 chars]: PeakData object (2167)>, <PeakData: PeakData object (2168)>]> != <Quer[195 chars]: PeakData object (2167)>, <PeakData: PeakData object (2168)>]>
`

and so then I tried `self.assertListEqual(peakdata, peakdata2)`, which failed with 
`AssertionError: First sequence is not a list: <QuerySet [<PeakData: PeakData object (2162)>, <PeakData: PeakData object (2163)>, <PeakData: PeakData object (2164)>, <PeakData: PeakData object (2165)>, <PeakData: PeakData object (2166)>, <PeakData: PeakData object (2167)>, <PeakData: PeakData object (2168)>]>`

So , I ended up with `self.assertQuerysetEqual(peakdata, peakdata2)`, and began doubting my entire naming scheme and what I thought Django was _actually_ returning (the "_**not a list**_" complaint), and I wholesale found-and-replaced everything. 

So, long-story-short I am happy to rename these methods and tests to the popular consensus, because I have personally been on both sides of the fence.

2021-09-10 14:12 UTC, hepcat72 commented on DataRepo/models.py
> +            )
100%.  Resolving.

2021-09-10 14:16 UTC, jcmatese commented on DataRepo/models.py
> +            return None
Was this not adequate (or perhaps coded incorrectly)?
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/5c28d72982d43bb38c2c520827ba20e9a8c42c59/DataRepo/tests/test_models.py#L446-L453

2021-09-10 14:45 UTC, lparsons commented on DataRepo/models.py
> +            return None
Whoops! I missed that in the test. I think if we make it a separate test it will be clearer what we are testing.

2021-09-10 14:53 UTC, lparsons commented on DataRepo/models.py
> +    def peak_data_queryset(self, compound=None):
It most certainly does return a Queryset, that was my bad. Do other many to many relationships in Django return Querysets? Maybe if we created a (cached) property "peakdataset" (or something similar that matches typical naming) the compound filtering could be done by the code that needed it? IMO, much of these design decisions  will come down to how the methods are used. Since that code isn't in this PR, I can only speculate, so I'll leave it up to you to make things as clear and logical as you can.

2021-09-14 14:05 UTC, fkang-pu approved these changes
Did a few quick tests with Django shell. The methods worked.

2021-09-14 19:53 UTC, lparsons approved these changes
lgtm

2021-09-15 20:39 UTC, hepcat72 requested changes
I'm unclear on the ordering of the DurationField  `time_collected`.

2021-09-15 21:04 UTC, jcmatese commented on DataRepo/models.py
> +            .order_by("time_collected")
Yes, we want the last serum sample collected which also happens to be the sample with the longest duration (from the start for the study). This is what `.latest()` or `.last()` probably both work for our use case.  In this method I am just sorting to get the temporal order of the sample as it was collected from the animal during the study, in case that is useful for processing or graphing.

2021-09-16 15:40 UTC, hepcat72 commented on DataRepo/models.py
> +            .order_by("time_collected")
So this is used on a query set that has already been reduced to the animal(s?) in a study?  Can't there be multiple animals in a study?  Wouldn't you want to limit it to 1 animal's worth of samples?  Can this method be called incorrectly, i.e. can it *technically* be called with an assortment of samples spanning multiple studies and/or animals?

2021-09-16 15:41 UTC, hepcat72 commented on DataRepo/models.py
> +            .order_by("time_collected")
Ah, I just noticed your edit answers my question.

2021-09-16 15:42 UTC, hepcat72 approved these changes
Thanks for the added comment. Looks good.

2021-09-16 17:11 UTC, merged