Added Animal methods/tests for serum tracer calculations
Princeton-LSI-ResearchComputing/tracebase pull request #193
Opened 2021-09-21 14:53 UTC by jcmatese

Added 2 new convenience methods: intact_tracer_peak_data, final_serum_sample_tracer_peak_group
Added 13 new methods for serum tracer calculations
Added preliminary tests for serum tracer calculations.

## Summary Change Description

Briefly describe the changes in this pull request (not intended as a full
recounting of the issue description).

## Affected Issue Numbers

- Resolves #43

## Code Review Notes

You can test (almost all of) the methods using
`manage.py test --tag=fcirc`
 
Code reviewers should pay particular attention to:

These are all new computational methods and cached values.  Unfortunately, the sample calculations [kindly provided to us](https://docs.google.com/spreadsheets/d/1b4H5rZDfzGHzvVZsmgHHUWG_u3esAhxSYF2PVgi9_zk/edit#gid=2095042101) were from animals **_not within our testing current data_**, so I tried to match the calculations by eye, and could use other developer confirmation OR we could find those data, and load them as a test files/example, if we want an independent validation. [i.e. the tests are self-referential, unfortunately]

The other concern to vet closely are that the method calcs/tests that I did match grouped up with equivalent asserts, so that _could_ be a cause for concern, or confirmation that alternative calculations are very close to one another (i.e. closely related).  I will be going over this again, but extra eyes would be helpful.  Anyway, I thought I would get these in front of more eyes, in case another direction, data, or another approach were required.

I paste the following assertion equivalent groups, for the test data I had.

**groups of "equivalent calcs"**

```
        self.assertAlmostEqual(animal.tracer_Ra_intact, 326.38, places=2)
        self.assertAlmostEqual(animal.tracer_Ra_avg, 326.38, places=2)
        self.assertAlmostEqual(animal.tracer_Fcirc_intact_per_mouse, 326.38, places=2)
        self.assertAlmostEqual(animal.tracer_Fcirc_avg_per_mouse, 326.38, places=2)

```
```
        self.assertAlmostEqual(animal.tracer_Ra_intact_g, 12.41, places=2)
        self.assertAlmostEqual(animal.tracer_Ra_avg_g, 12.41, places=2)
        self.assertAlmostEqual(animal.tracer_Fcirc_intact, 12.41, places=2)
        self.assertAlmostEqual(animal.tracer_Fcirc_avg, 12.41, places=2)

```
```
        self.assertAlmostEqual(animal.tracer_Rd_intact, 393.50, places=2)
        self.assertAlmostEqual(animal.tracer_Rd_avg, 393.50, places=2)

```

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-09-21 16:49 UTC, lparsons requested changes
This looks like a through treatment of FCirc related functions which should serve us well for the initial FCirc page. I have a few questions I put inline where I wasn't clear on things.

I had two main suggestions:
1. Make methods that require no parameters `properties` (probably `cached_properties`). This makes accessing them simpler and more consistent with other methods and provides some caching benefit.
2. Using a simple `if/else` construct for cases with null/None values. The logic is simpler and it's more specific. At a minimum, we would want to catch the specific Exception that occurs, not just a generic `Exception`, though there is a check for the message, that message could change in the future.

2021-09-21 16:49 UTC, lparsons commented on DataRepo/models.py
> +    def intact_tracer_peak_data(self):
Making this a `@cached_property` would make access simpler and consistent with other attributes/properties. It would also cache the result while this Animal object persists, which could be useful.

In addition, though outside the scope of this PR, `final_serum_sample_tracer_peak_data`, `final_serum_sample`, and `all_serum_samples` all seem to be candidates for `@cached_property`.

2021-09-21 16:49 UTC, lparsons commented on DataRepo/models.py
> +    def tracer_Rd_intact_g(self):
I'm not clear what the `_g` in the method name stands for. Could you elaborate?

2021-09-21 16:53 UTC, jcmatese commented on DataRepo/models.py
> +    def tracer_Rd_intact_g(self):
I am not certain either, but I think it means "grams in the denominator" or perhaps "per_gram"

2021-09-21 16:56 UTC, jcmatese commented on DataRepo/models.py
> +        return self.final_serum_sample_tracer_peak_data().first().peak_group
Hmmm.  Perhaps I coded `final_serum_sample_tracer_peak_data` incorrectly, then, because I had intended to get all the peak data for that sample (regardless of labelling).

2021-09-21 17:26 UTC, lparsons commented on DataRepo/models.py
> +    def tracer_Rd_intact_g(self):
I think I'd prefer some clearer naming for the properties. And also probably keep them lowercase (for consistency).

2021-09-21 18:34 UTC, hepcat72 commented on DataRepo/models.py
> +                raise (e)
NB. Same here as above.

2021-09-21 18:36 UTC, hepcat72 commented on DataRepo/models.py
> +            / self.intact_tracer_peak_data().fraction
Also on line 492

2021-09-21 19:33 UTC, lparsons commented on DataRepo/models.py
> +        return self.final_serum_sample_tracer_peak_data().first().peak_group
That's a good point. I wonder if it would make more sense to have the peak_group method do the query and then just get the peak data from that when needed?

2021-09-21 19:38 UTC, hepcat72 commented on DataRepo/models.py
> +        return self.final_serum_sample_tracer_peak_data().first().peak_group
Incidentally, `limit` would be more efficient, if you only need 1 and it doesn't matter which.

2021-09-21 19:38 UTC, jcmatese commented on DataRepo/models.py
> +        return self.final_serum_sample_tracer_peak_data().first().peak_group
I suppose we could do that (restructure the methods/querysets).  I had originally written it that way because I though the PeakData had the "important" stuff, but I had forgotten about the enrichment attribute.

2021-09-22 12:31 UTC, jcmatese commented on DataRepo/models.py
> +        (Animal:infusion_rate * Animal:infusion_concentration)
I think they were just from the [original issue feature description](https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/43#issue-862975818), copy/pasted for attempted documentation/cross-referencing.

2021-09-23 15:10 UTC, jcmatese commented
@lparsons @hepcat72 @fkang-pu I committed an alternate implementation that was an offshoot of some discussion with Lance, yesterday, which was primarily focused around focusing on a singular/primary peak_group for calculation, or returning all peak_groups and letting software and researchers deal with it.  It is not quite ready for primetime, but I thought a decision could be made on "what-to-keep-and-what-to-cut-out",  and then go from there (adding more tests, etc.).  Regarding the pylint issues, I am not quite certain how to resolve, offhand, other than telling pylint to ignore that error.

```
DataRepo/models.py:384:12: E1101: Instance of 'Animal' has no 'samples' member (no-member)
DataRepo/models.py:400:12: E1101: Instance of 'Animal' has no 'samples' member (no-member)
DataRepo/models.py:662:15: E1101: Instance of 'ForeignKey' has no 'category' member (no-member)
DataRepo/models.py:824:11: E1101: Instance of 'ForeignKey' has no 'category' member (no-member)
DataRepo/models.py:896:15: E1101: Instance of 'PeakGroup' has no 'peak_data' member (no-member)
DataRepo/models.py:936:19: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:961:48: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:967:38: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:977:19: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:985:19: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:995:15: E1101: Instance of 'ForeignKey' has no 'sample' member (no-member)
DataRepo/models.py:1006:42: E1101: Instance of 'ManyToManyField' has no 'all' member (no-member)
DataRepo/models.py:1060:26: E1101: Instance of 'PeakGroup' has no 'peak_data' member (no-member)
DataRepo/models.py:1280:42: E1101: Instance of 'ForeignKey' has no 'total_abundance' member (no-member)
```

2021-09-23 15:12 UTC, jcmatese commented on DataRepo/models.py
> +        matching the intact tracer (labeled_count filtered)
it is where `peakdata.labeled_count == animal.tracer_labeled_count` , i.e. "fully labeled", or "intact"

2021-09-23 15:13 UTC, lparsons commented
My thoughts on what to include are in: https://docs.google.com/document/d/1Z6Y9EbU3HUxi5IDL7TCl1YgI3CKDhZkb6qWKXUa6BwU/edit?usp=sharing

As for the linting, we'll have to take a closer look. Seems like some issue finding the library or something, but I never got these with PyLint on GitHub actions before (they do happen locally without the Pylint Django plugin, I believe).

2021-09-28 14:23 UTC, jcmatese commented on DataRepo/models.py
> +    def tracer_Rd_intact_g(self):
I did try and make clearer names in the PeakGroup implementation (my preferred names), and could change the Animal method names to be something other than what is defined in the issue and Michael's spreadsheet, given consensus preference.

2021-09-28 19:42 UTC, lparsons requested changes
Overall, this looks very good. There was a lot to work out both scientifically and algorithmic ally for this and you handled it well John. Your background in lab science and in scientific databases was apparent.

One blocking change request. I think having consistent naming for the same thing (*e.g.* `tracer_Rd_intact_g` and `rate_disappearance_intact_per_gram`) is important. Having the convenience methods in `Animal` seems like it may be helpful, but having different names for the same thing seems likely to lead to confusion. I much prefer the longer, more descriptive names.

One non-blocking issue (that may simply go away when the above is addressed). The method names aren't always in lowercase. For consistency within the project and between various projects I work on, I do prefer to use the [PEP 8 convention of method names being "lowercase with words separated by underscores as necessary to improve readability"]https://www.python.org/dev/peps/pep-0008/#function-and-variable-names).

2021-09-28 19:48 UTC, jcmatese commented
Happy to defer to the consensus naming decisions.  I just started with the issue names and the spreadsheet names, as a starting point.  Happy to discuss those decisions over Zoom or whatever...

2021-09-28 19:55 UTC, jcmatese commented on DataRepo/models.py
> +                raise (e)
This was removed, with an alternative implementation.

2021-09-28 19:56 UTC, jcmatese commented on DataRepo/models.py
> +                raise (e)
This was removed, with an alternative implementation.

2021-09-28 19:59 UTC, lparsons commented
> Happy to defer to the consensus naming decisions. I just started with the issue names and the spreadsheet names, as a starting point. Happy to discuss those decisions over Zoom or whatever...

I would insist that we are internally consistent with the names. I vote for the longer names used in PeakGroup.

2021-09-28 20:08 UTC, jcmatese reviewed
Things I would put on a punch list:

rename or remove methods in Animal:
Do we need **_all_** of these in Animal, or just a chosen few?

- tracer_Rd_intact_g
- tracer_Ra_intact_g
- tracer_Rd_intact
- tracer_Ra_intact
- tracer_Rd_avg_g
- tracer_Ra_avg_g
- tracer_Rd_avg
- tracer_Ra_avg

The following Animal methods were attempted to be created using the math defined in the original issue, and _may_ in fact be equivalent to various `Ra` methods.  Also, the tests I added are actually flagged as skipped (`@skip`) because there was not an explicit/independent lab-provided calculation:

- tracer_Fcirc_intact
- tracer_Fcirc_avg
- tracer_Fcirc_intact_per_mouse
- tracer_Fcirc_avg_per_mouse
- tracer_Fcirc_avg_atom

2021-09-28 20:54 UTC, lparsons commented
Looks like a good list. Rename and/or remove the first list (your call on what would be useful to have). The second list looks like it should be removed to me.

2021-09-29 13:59 UTC, jcmatese commented
> Looks like a good list. Rename and/or remove the first list (your call on what would be useful to have). The second list looks like it should be removed to me.

I will ask Michael if the Rd variants are useful for animal-centric display, or if they are primarily just used to calculate eventual Ra/Fcirc.  

Just wanted to document that the following methods (as currently coded) are mathematical equivalent

```
    @tag("fcirc")
    def test_fcirc_animal_method_equivalence(self):
        a = self.MAIN_SERUM_ANIMAL
        self.assertEqual(a.tracer_Fcirc_intact, a.tracer_Ra_intact_g)
        self.assertEqual(a.tracer_Fcirc_avg, a.tracer_Ra_avg_g)
        self.assertEqual(a.tracer_Fcirc_intact_per_mouse, a.tracer_Ra_intact)
        self.assertEqual(a.tracer_Fcirc_avg_per_mouse, a.tracer_Ra_avg)
```
and if I remove the "Fcirc" variants , I can perhaps just move those comments/docs over (in case anyone searches for that term).

The one "doing-its own-thing" is `tracer_Fcirc_avg_atom`, so I will ask Michael about that as well.  I don't think there is an equivalent, but it would be easy to add to PeakGroup (or rename in Animal), depending on its popular usage.

Regarding renaming, do people have a preference of method name equivalence to PeakGroup method?
for example 
`tracer_Ra_intact_g` becomes `rate_appearance_intact_per_gram`, (i.e. the "final serum tracer PeakGroup" aspect is implicit) 
OR,
`tracer_Ra_intact_g` becomes `final_serum_tracer_rate_appearance_intact_per_gram` (explicit, but long and different than PeakGroup method naming)

2021-09-29 15:45 UTC, lparsons commented
My thought on method naming:
* `PeakGroup.rate_appearance_intact_per_gram`
* `Animal.final_serum_tracer_rate_appearance_intact_per_gram`

2021-09-29 18:17 UTC, jcmatese commented
did most of the renaming and Fcirc deletion.  Waiting a bit to see the relative importance of "disappearance" rates in Animal class, and the atom-specific-normalization calculation (pinged Michael on Slack).

2021-09-29 18:18 UTC, lparsons approved these changes
LGTM

2021-10-04 13:22 UTC, fkang-pu commented on DataRepo/models.py
> +            return False
The method name seems to suggest the return value would be True or False, but it's actually the fraction value or False. I was wondering if the method name could have something to do with fraction (e.g. valid_fraction? ) and return a value or None(plus warning).

2021-10-04 13:34 UTC, fkang-pu commented on DataRepo/models.py
> +            return False
Same as I commented for "can_compute_average_tracer_rates", might be helpful if having a different method name (e.g. valid_enrichment_fraction or a better name? ) and returning a value or None.  Ignore my comments if they don't make sense to you.

2021-10-04 17:51 UTC, fkang-pu approved these changes

2021-10-04 19:31 UTC, merged

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
> +        matching the intact tracer (labeled_count filtered)
...though probably the users would not have added peaks of alternate compounds of a size greater than or equal to the tracer compound.  But I don't like that we rely on that user behavior to provide accurate results.

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
> +        matching the intact tracer (labeled_count filtered)
It's also interesting to note that a compound could theoretically have been metabolized and re-synthesized with the same number of labeled elements... though I'm not saying this is an actionable observation - it's just a random thought.

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
> +        Fcirc_avg_per_mouse. Ra_avg = Ra_avg_g * 'Body Weight'' in nmol/min
NB>
```suggestion
        Fcirc_avg_per_mouse. Ra_avg = Ra_avg_g * 'Body Weight' in nmol/min
```

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
>      def peak_data(self, compound=None):
NB.
```suggestion
    def peak_data(self, compound=None):
        """
         Retrieve a list of PeakData objects for a sample instance.  If an optional
         compound is passed (e.g. animal.tracer_compound), then is it used to filter
         the PeakData queryset to a specific peakgroup.
        """
 
```

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
> +        """returns True is the sample is flagged as a "serum" sample"""
NB.
```suggestion
        """returns True if the sample is flagged as a "serum" sample"""
```

2021-10-04 22:13 UTC, hepcat72 commented on DataRepo/models.py
> +        """returns True is the sample is flagged as a "serum" sample"""
Incidentally, why are there no suggest buttons?   Ohhh, this was merged?...

OK, never mind.  Just going to stop here...

2021-10-04 22:14 UTC, hepcat72 commented
Incidentally, I didn't request changes. There were no options on the review submission form.

2021-10-05 15:15 UTC, jcmatese commented on DataRepo/models.py
> +        matching the intact tracer (labeled_count filtered)
The aforementioned "matches" checks were for the PeakGroup-specific tracer functions.  Animal methods also filter/match from [here](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/f3589e84c3205a6e7b833d4c1754ddf0549d0b48/DataRepo/models.py#L432-L445), using the intrinsic associated tracer compound.

2021-10-05 15:33 UTC, hepcat72 commented on DataRepo/models.py
> +        matching the intact tracer (labeled_count filtered)
OK. I traced it back and confirmed that the specific compound is assured. Regarding my "edits"(/review issues), they are all non-blocking, so I'll leave it to you whether to implement them or not.  FFR, I would only ever suggest a follow-up issue if the review issues were blocking.

2021-10-05 17:28 UTC, jcmatese commented on DataRepo/models.py
> +        )
Perhaps?  Maybe all the `*per_gram` methods should have the  `*weight_normalized` suffix, instead, and the current `*weight_normalized` methods should just be shortened?

2021-10-05 17:35 UTC, jcmatese commented on DataRepo/models.py
> +        )
...or just leave `*per_gram` and  shorten `*weight_normalized`?

2021-10-06 18:36 UTC, jcmatese commented on DataRepo/models.py
> +        )
will replace "weight_normalized" with "per_animal" most places, and exchecng other related normalized methods to specifically reference to the existence of body_weight (in a new PR).  Will also try to get the types above in that PR.