method for formatting PeakGroup name with hyperlink(s) to compound(s)
Princeton-LSI-ResearchComputing/tracebase pull request #207
Opened 2021-10-13 17:02 UTC by fkang-pu

## Summary Change Description

- added a method "peakgroup_name_with_link" to PeakGroup in models.py
- added test code to test_models.py
- modified peakgroup_detail.html

## Affected Issue Numbers

- Resolves #150

## Code Review Notes

- added #TODO# in comment section for "peakgroup_name_with_link" method

  since data loading mishandled citrate/isocitrate case, use self.compounds.all()
would result in incorrect format of PeakGroup name with hyperlinks. So use Compound queryset as a workaround.

- can run test with tag "pg_name_with_link" 

- web test for peakgroup name with hyperlink(s):

  http://127.0.0.1:8000/DataRepo/peakgroups/11/

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-10-13 20:58 UTC, lparsons requested changes
I can see why you had to write something like this, but the problem is acually that the compounds weren't properly associated with PeakGroup to begin with (#208).

I submitted #209 to fix that issue. The template should then display something like:
```html
{peakgroup.name} - 
{% for compound in peakgroup.compound %}
    <a href="{% url 'compound_detail' compound.id %}">{{ compound.name }}</a>
{% endfor %}

2021-10-14 01:56 UTC, lparsons commented
The HTML should be in the template. So if you want a separator, maybe something like this:
```

{peakgroup.name} - 
{% for compound in peakgroup.compound %}
    <a href="{% url 'compound_detail' compound.id %}">{{ compound.name }}</a> {% if not forloop.last %} / {% endif %}
{% endfor %}
```
I'm not sure if you can use the `not`, but maybe `{% if forloop.last is False %}` would work.

2021-10-14 02:07 UTC, lparsons commented
Another way to do this would be to write a [custom template filter](https://docs.djangoproject.com/en/3.2/howto/custom-template-tags/). Here is an [example of a comma separated list of links](https://djangosnippets.org/snippets/535/).

2021-10-14 12:03 UTC, fkang-pu commented
@lparsons Thanks for the suggestions. I'll try to use "for loop" in HTML template after reloading data to my local database.

2021-10-14 17:52 UTC, fkang-pu commented
Since Rob is out today and tomorrow and this PR only has a few lines of code change, I just removed him from reviewers. Ready to merge into main if no other concerns.

2021-10-14 19:07 UTC, merged