Utilize synonyms during data loading
Princeton-LSI-ResearchComputing/tracebase pull request #258
Opened 2021-11-18 20:50 UTC by jcmatese

## Summary Change Description

Employ Compound.compound_matching_name_or_synonym within AccuCorDataLoader

## Affected Issue Numbers

- Resolves #204

## Code Review Notes

Describe any areas of concern that code reviewers should pay particular
attention to.  E.g. There are significant logic changes in function X.

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-11-18 21:47 UTC, fkang-pu approved these changes

2021-11-18 22:01 UTC, lparsons requested changes
While this appears to work correctly, I think we should create a test that actually performs a lookup by synonym (*i.e.* a test that would fail before this change and that passes after it). I would also be OK if we simply created an issue to create such a test and merged this PR once the issue was created.

2021-11-19 16:01 UTC, jcmatese commented on DataRepo/utils.py
> +from django.core.exceptions import ValidationError  # type: ignore
Can't explain.  I think I probably just copy-pasted that line from another file, but it _might_ have been a paste/insertion error, which could explain the `# type: ignore` from the previous commit.  I don't recall the presence/requirements for those comments, offhand.

2021-11-19 16:03 UTC, jcmatese commented on DataRepo/utils.py
> +from django.core.exceptions import ValidationError  # type: ignore
Currently leaning towards "insertion error" as possible provenance...

2021-11-19 16:06 UTC, jcmatese commented on DataRepo/utils.py
> +from django.core.exceptions import ValidationError  # type: ignore
> While this appears to work correctly, I think we should create a test that actually performs a lookup by synonym (_i.e._ a test that would fail before this change and that passes after it).

I added a couple test files and tests, if that is what you were envisioning.

2021-11-19 20:26 UTC, lparsons approved these changes
Thanks for adding those tests. Looks good.

2021-11-22 18:55 UTC, hepcat72 approved these changes
😎

2021-11-22 18:55 UTC, hepcat72 commented on DataRepo/utils.py
> +                        )
NB. Very minor, but holistically, a ValidationError is used for at least 2 situations.  The other type would not occur here (currently), but this does rely on an assumption that `ValidationError` is specifically about a case where multiple matching compounds were encountered.  I would think that a more specific exception class would be created and caught here that is "based" off of `ValidationError`.

2021-11-22 18:55 UTC, hepcat72 commented on DataRepo/utils.py
> +                        )
NB. Also, this prepends a string `Could not uniquely identify compound using {compound_input}.` to `{e}` which essentially says the same thing: `compound_matching_name_or_synonym retrieved multiple distinct compounds matching {name} from the database`.  I would say that if you want to `print` it, nothing really needs to be prepended.  It's redundant.

2021-11-22 19:25 UTC, jcmatese commented on DataRepo/utils.py
> +                        )
I removed the redundant error messaging.  I will defer on the error typing (`ValidationError` vs. a putative replacement), because I can never seem to thread the needle when it comes to choosing/raising errors appropriately.

2021-11-22 19:28 UTC, hepcat72 commented
Looks like the linter is unhappy...

2021-11-22 19:38 UTC, merged