Modify dataframes templates
Princeton-LSI-ResearchComputing/tracebase pull request #273
Opened 2021-11-29 20:49 UTC by fkang-pu

## Summary Change Description

- Upgraded Pandas to version 1.2.0 in order to call function "convert_dtypes" to deal with missing data.
- Made big changes to DataFrames code in utils.py to cover the following cases:

  --animals/samples without MSRun data
  --animals without tracer and/or treatment data
  --handling array data in np.array instead of pd.StringArray to avoid error when converting to JSON data in Django views
  --handling data for Date and TimeDelta in DataFrames
 
- Made changes to custom tags and templates:  format date and timedelta values and handle missing values.

## Affected Issue Numbers

- Resolves #210 
- Resolves #213
- Resolves #262

## Code Review Notes

- Did a lot of tests for missing data in string and number types in Pandas DataFrame. Seems the good practice is to use pd.NA for missing data if possible. 

- Skipped linting home.html with jscpd, too many repeated code blocks. Please suggest if you have better idea.

- Tried to load a new study to cover edge cases. Had to break the animal/sample data into three sets, in order to load them. For an animal without tracer data, the labeled_atom is loaded as C (a bug?).
- Ran Superlinter locally and passed.

- Passed test for test_utils.py and test_views.py, but got error with test_models.py when running all tests together.  Made no change to models and test_models.py. need a bit time to understand why.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-11-29 21:28 UTC, fkang-pu commented
[test log](https://github.com/Princeton-LSI-ResearchComputing/tracebase/runs/4359291219?check_suite_focus=true)
errors (line 7521 to 7547):

======================================================================
ERROR: setUpClass (DataRepo.tests.test_models.DataLoadingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/home/runner/work/tracebase/tracebase/DataRepo/tests/test_models.py", line 612, in setUpTestData
    researcher="Michael Neinast",
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 83, in handle
    self.extract_dataframes_from_accucor_xlsx(options)
  File "/home/runner/work/tracebase/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 117, in extract_dataframes_from_accucor_xlsx
    squeeze=True,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 1063, in __init__
    path=str(self._io), storage_options=storage_options
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/pandas/io/excel/_base.py", line 954, in inspect_excel_format
    raise ValueError("File is not a recognized excel file")
ValueError: File is not a recognized excel file

----------------------------------------------------------------------

2021-11-30 17:10 UTC, lparsons commented
This PR updates the version of Pandas to 1.2.0 (though I would prefer at least the latest 1.2 release, 1.2.5). It turns out that [requires at least Python 3.7.1 or higher](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.0.html#increased-minimum-version-for-python). Currently, we have 3.6 installed on tracebase-dev. I've requested an updated version be installed on tracebase-dev ([RT #47075](https://gen-help.princeton.edu/Ticket/Display.html?id=47075)).

I suspect the failing test has to do with changes related to using `openpyxl`, but I'm not certain.

2021-11-30 17:29 UTC, fkang-pu commented
I initially upgraded Pandas to 1.3.4 in my dev environment, and it didn't work. Seems version 1.2.5 didn't work neither.  I reversed back to 1.2.0. Now I just created a test project to test different versions of Pandas. Hopefully I will have a better idea this afternoon. Also need to take a closer look at [Pandas release notes ](https://pandas.pydata.org/docs/whatsnew/v1.3.4.html).

2021-11-30 17:33 UTC, lparsons commented
We should be able to get the code working in the latest Pandas, at least that would be my preference. If you get things working in some version, but it breaks in a later version, then let's try to update the code so the new version works. Feel free to publish branches and ping me, Rob, or John for help updating to a later version.

BTW, I'm going to push a PR soon that tests with Python 3.6 (since that is what we have on tracebase-dev). Once we get the server updated, we can change the version that GitHub uses to test our project. That should help catch version requirements sooner.

2021-11-30 18:22 UTC, jcmatese reviewed
Generally, I think this looks good, but had a couple small questions.  Also need to figure out the `xlsx` issue with the version bump...

2021-11-30 18:22 UTC, jcmatese commented on DataRepo/templates/DataRepo/animal_detail.html
> +    <h5><a href="{% url 'search_basic' 'Animal' 'id' 'iexact' animal.id 'fcirc' %}">View Fcirc Data</a></h5>
Q: Isn't id just an integer/sequence?  Why the switch to`iexact`?

2021-11-30 18:22 UTC, jcmatese commented on DataRepo/templates/DataRepo/study_detail.html
> +    <h5><a href="{% url 'search_basic' 'Study' 'id' 'iexact' study.id 'fcirc' %}">View Fcirc Data</a></h5>
Q: Same question as previous... (benefit to `'iexact'` for ID queries?)

2021-11-30 18:22 UTC, jcmatese commented on DataRepo/utils.py
Q: I suppose it is easier to call `convert_dtypes` that perhaps explicitly code a type for each column/header?  I wonder how good its inference is...

2021-11-30 18:27 UTC, fkang-pu commented on DataRepo/templates/DataRepo/animal_detail.html
> +    <h5><a href="{% url 'search_basic' 'Animal' 'id' 'iexact' animal.id 'fcirc' %}">View Fcirc Data</a></h5>
The change was made based on Rob's suggestion in last meeting.

2021-11-30 18:30 UTC, lparsons commented on DataRepo/templates/DataRepo/animal_detail.html
> +    <h5><a href="{% url 'search_basic' 'Animal' 'id' 'iexact' animal.id 'fcirc' %}">View Fcirc Data</a></h5>
It doesn't make sense to me for `id` (integer) queries, only for text based searches.

2021-11-30 18:31 UTC, lparsons commented on DataRepo/utils.py
Since we know what each of these columns is, it would make sense to explicitly set `dtypes` for every column.

2021-11-30 18:38 UTC, jcmatese commented on DataRepo/utils.py
I would be fine with leaving it for now, and making an issue for the future to explicitly code the dtypes.  Probably even more important for the loading code...

2021-11-30 18:45 UTC, jcmatese commented on DataRepo/utils.py
Could also just see how well it performs/infers in practice.  Perhaps it is a great way to reduce 20-30 lines into 1...

2021-11-30 18:48 UTC, fkang-pu commented on DataRepo/utils.py
I agree. I need more time to test how pandas control/convert types. Seems to me there are some inconsistencies. When I did a small test with str.cat to get output in an array with version 1.2.5, I thought output was np.array and  worked fine with to_json function. Then I got error with some data from multiple studies. Somehow it converted to StringArray type.  Based on my tests, `to_json` handled array type correctly till at least 1.2.2 version. But versions 1.2.0 and 1.2.2 raised errors with `test_modles.py` for reading excel file. (1.2.0: ValueError: File is not a recognized excel file; 1.2.2: zipfile.BadZipFile: File is not a zip file). One thing for sure, we need to be careful when upgrading Pandas.

2021-11-30 19:00 UTC, fkang-pu commented
> We should be able to get the code working in the latest Pandas, at least that would be my preference. If you get things working in some version, but it breaks in a later version, then let's try to update the code so the new version works. Feel free to publish branches and ping me, Rob, or John for help updating to a later version.
> 
> BTW, I'm going to push a PR soon that tests with Python 3.6 (since that is what we have on tracebase-dev). Once we get the server updated, we can change the version that GitHub uses to test our project. That should help catch version requirements sooner.

That's my goal too. But need more time to test and understand the issues. To get data from Pandas DataFrame to the format for rendering in Django templates, need to call `pd.to_dict` or `pd.to_json`. Got errors with newer versions of Pandas.

2021-11-30 19:25 UTC, lparsons commented
> To get data from Pandas DataFrame to the format for rendering in Django templates, need to call `pd.to_dict` or `pd.to_json`. Got errors with newer versions of Pandas.

Yeah, that's frustrating. If you can publish a branch and a way to reproduce these errors, we could help you resolve them. Ideally, a failing test, but alternatively an example file/command/link/etc.

2021-11-30 19:36 UTC, fkang-pu commented
> > To get data from Pandas DataFrame to the format for rendering in Django templates, need to call `pd.to_dict` or `pd.to_json`. Got errors with newer versions of Pandas.
> 
> Yeah, that's frustrating. If you can publish a branch and a way to reproduce these errors, we could help you resolve them. Ideally, a failing test, but alternatively an example file/command/link/etc.

That's what I am trying to pinpoint the problems. Up to now, I know version 1.2.0 and 1.2.2 worked for my branch except for the error with test_models.py. If you have a quick solution to fix the error with reading excel file,  we could at least use version 1.2.0 to move the project forward.

2021-11-30 19:38 UTC, jcmatese commented
> That's what I am trying to pinpoint the problems. Up to now, I know version 1.2.0 and 1.2.2 worked for my branch except for the error with test_models.py.

Do you know which file is being loaded that is throwing the error? (there are a number of them in that `SetUp`)

2021-11-30 19:45 UTC, jcmatese commented
> > That's what I am trying to pinpoint the problems. Up to now, I know version 1.2.0 and 1.2.2 worked for my branch except for the error with test_models.py.
> 
> Do you know which file is being loaded that is throwing the error? (there are a number of them in that `SetUp`)

Looks like it is the corrected-only csv variant `obob_maven_6eaas_inf_corrected.csv`

2021-11-30 19:47 UTC, jcmatese commented
I think they changed their error type

```
        try:
            self.extract_dataframes_from_accucor_xlsx(options)
        except InvalidFileException:
            self.extract_dataframes_from_csv(options)
```

2021-11-30 19:53 UTC, fkang-pu commented
> > > That's what I am trying to pinpoint the problems. Up to now, I know version 1.2.0 and 1.2.2 worked for my branch except for the error with test_models.py.
> > 
> > 
> > Do you know which file is being loaded that is throwing the error? (there are a number of them in that `SetUp`)
> 
> Looks like it is the corrected-only csv variant `obob_maven_6eaas_inf_corrected.csv`

I ran the test_models.py again , got this:

 `python manage.py test  DataRepo.tests.test_models`

Reading accucor file: DataRepo/example_data/obob_maven_c160_serum.xlsx

ERROR: setUpClass (DataRepo.tests.test_models.DataLoadingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/Users/fkang/dev/tracebase/DataRepo/tests/test_models.py", line 607, in setUpTestData
    call_command(
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/fkang/dev/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 83, in handle
    self.extract_dataframes_from_accucor_xlsx(options)
  File "/Users/fkang/dev/tracebase/DataRepo/management/commands/load_accucor_msruns.py", line 111, in extract_dataframes_from_accucor_xlsx
    orig_heads = pd.read_excel(
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 336, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1062, in __init__
    ext = inspect_excel_format(
  File "/Users/fkang/dev/tracebase/.venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 954, in inspect_excel_format
    raise ValueError("File is not a recognized excel file")
ValueError: File is not a recognized excel file

2021-11-30 19:53 UTC, jcmatese commented
I just pushed a commit that _might_ address the issue.

2021-12-01 13:42 UTC, fkang-pu commented
I upgraded to Pandas 1.3.4. Every part seems working now after I modified code. Main change is Pandas handles timedelta type differently (version 1.2.0: format value as ns in Int64 type; version 1.3.4: timedelta64[ns] type).  The value in JSON output is ISO format. So I re-write two filters in customtags.py.

2021-12-01 18:40 UTC, hepcat72 requested changes
One blocking issue, though it's fairly trivial to fix - and I could be persuaded otherwise. Great to see all those tests.  Good work Fan.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/DataRepo/compound_detail.html
> +                    {{ i.name }} {% if not forloop.last %};{% endif %}
In fact, is there a way to use the `join` filter you use elsewhere here?: `|join:" ;"`

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/DataRepo/compound_list.html
> +                <td>{{ i.tracer | yesno:"yes,no" }}</td>
C. Cool. This looks like an interesting filter.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/DataRepo/peakgroupset_detail.html
> +<h5><a href="{% url 'search_basic' 'PeakGroupSet' 'filename' 'iexact' peakgroupset.filename 'peakdata' %}">View Peak Data</a></h5>
NB. I might recommend removing "View " from the link text and changing the link to appear as a button. That's just what I would do.  Totally at your discretion.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/DataRepo/study_detail.html
> +                    <a href="{% url 'msrun_detail' i.msrun_id %}">MSRun Detail</a>
C. Same `__str__()` suggestion as above, though I just had another thought, based on my last comment.  You could display this link as a button as well, and thus the substring "Detail" becomes functionally redundant.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/home.html
> +    </style>
Q. Is there a `.css` file this could be added to, so it could be used elsewhere - if that seems useful?

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/home.html
> +                <div class="text-dark"><i class="fas fa-angle-right"></i></div>
Q. I'm not adept with css, but does it make a difference to use `span` instead of `i` here? That way, adding additional classes (if desired in the future) wouldn't potentially seem out of place...

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/home.html
> +                <div class="text-dark"><i class="fas fa-angle-right"></i></div>
In fact, could it be added to the surrounding `div` tag, to simplify the code?

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templates/sidebar.html
> +        <!--a href="{% url 'peakdata_list' %}" class="list-group-item list-group-item-action bg-light">Peak Data</a-->
NB. I think comment removal would be better here, but if not, then...
```suggestion
        <!-- <a href="{% url 'msrun_list' %}" class="list-group-item list-group-item-action bg-light">MS Runs</a> -->
        <!-- <a href="{% url 'peakgroup_list' %}" class="list-group-item list-group-item-action bg-light">Peak Groups</a> -->
        <!-- <a href="{% url 'peakdata_list' %}" class="list-group-item list-group-item-action bg-light">Peak Data</a> -->
```

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +    return dateparse.parse_duration(value).days // 7
B. These methods are functionally redundant/duplicates.  I think if you feel that using `dateparse` is better (which I would likely agree with if I dug into it), I would simply edit the `durationToMins` and `durationToWeeks` filters instead of add 2 more that do the same thing, differently.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +def hmdb_id_url(hmdb_id):
NB. The functions you are creating(/created) in this file are using a different naming convention (underscore-delimited-lower-case) than the pre-existing function names (camel-case).  I would suggest either changing yours to camel-case, or changing the pre-existing functions to underscore-delimited-lower-case (and everywhere they're called) to be consistent.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
NB. Use `Compound.HMDB_CPD_URL` here instead of hard-coding this URL here, as it already exists in `models`, and using that instead would reduce maintenance. Note, you will probably need another import above to access it.

2021-12-01 18:40 UTC, hepcat72 commented on DataRepo/views.py
> +    file_count = len(PeakGroupSet.objects.all())
NB. I think you may be able to use (for example) `Compound.objects.count()` here instead of calling `len()`.

2021-12-01 18:40 UTC, hepcat72 commented on requirements/common.txt
> +pandas==1.3.4
Q. Is this intentional? I thought this was in a separate PR.

2021-12-01 18:56 UTC, fkang-pu commented
> One blocking issue, though it's fairly trivial to fix - and I could be persuaded otherwise. Great to see all those tests. Good work Fan.

I mentioned in "Code Review Notes" section. The error was about too many repeated code blocks. I think it's due to 8 cards  I added to home page. If you have an idea how to fix it, I am for it.

2021-12-01 18:58 UTC, fkang-pu commented on DataRepo/templates/DataRepo/animal_detail.html
> +    <h5><a href="{% url 'search_basic' 'Animal' 'id' 'iexact' animal.id 'fcirc' %}">View Fcirc Data</a></h5>
fixed now

2021-12-01 19:01 UTC, fkang-pu commented on DataRepo/templates/DataRepo/animal_detail.html
> +                    <a href="{% url 'compound_detail' i.tracer_compound_id %}">{{ i.tracer }}</a>
It refers column name and value from the DataFrame ( `{% for i in df %}..`.). Shouldn't be a problem.

2021-12-01 19:10 UTC, hepcat72 commented
> > One blocking issue, though it's fairly trivial to fix - and I could be persuaded otherwise. Great to see all those tests. Good work Fan.
> 
> I mentioned in "Code Review Notes" section. The error was about too many repeated code blocks. I think it's due to 8 cards I added to home page. If you have an idea how to fix it, I am for it.

Oh whoops. My bad.  I forgot to read the review notes. Let me take a look...

2021-12-01 19:15 UTC, lparsons commented
Instead of skipping the entire ,`home.html` file, maybe just ignore the specific repeated blocks? https://www.npmjs.com/package/jscpd#ignored-blocks

2021-12-01 19:20 UTC, hepcat72 commented
> > > One blocking issue, though it's fairly trivial to fix - and I could be persuaded otherwise. Great to see all those tests. Good work Fan.
> > 
> > 
> > I mentioned in "Code Review Notes" section. The error was about too many repeated code blocks. I think it's due to 8 cards I added to home page. If you have an idea how to fix it, I am for it.
> 
> Oh whoops. My bad. I forgot to read the review notes. Let me take a look...

OK. Yeah, I see.  jscpd will complain when 5 or more lines repeat, and you have these 6 lines repeated a number of times:

```
                <div class="text-dark"><i class="fas fa-angle-right"></i></div>
             </div>
         </div>
     </div>
     <div class="col-xl-3 col-md-6 mb-4">
         <div class="card bg-card-1 text-dark">
```
You could eliminate the error a few different ways (other than what Lance suggested).  You could create a loop.  You could create a sub-template. You could modify your repeated lines to be on fewer lines (<5) or format them differently or change the order of the nested tags (though those would all be a bit of a cheat [I've done them]).

2021-12-01 19:22 UTC, hepcat72 commented
> > > > One blocking issue, though it's fairly trivial to fix - and I could be persuaded otherwise. Great to see all those tests. Good work Fan.
> > > 
> > > 
> > > I mentioned in "Code Review Notes" section. The error was about too many repeated code blocks. I think it's due to 8 cards I added to home page. If you have an idea how to fix it, I am for it.
> > 
> > 
> > Oh whoops. My bad. I forgot to read the review notes. Let me take a look...
> 
> OK. Yeah, I see. jscpd will complain when 5 or more lines repeat, and you have these 6 lines repeated a number of times:
> 
> ```
>                 <div class="text-dark"><i class="fas fa-angle-right"></i></div>
>              </div>
>          </div>
>      </div>
>      <div class="col-xl-3 col-md-6 mb-4">
>          <div class="card bg-card-1 text-dark">
> ```
> 
> You could eliminate the error a few different ways (other than what Lance suggested). You could create a loop. You could create a sub-template. You could modify your repeated lines to be on fewer lines (<5) or format them differently or change the order of the nested tags (though those would all be a bit of a cheat [I've done them]).

Incidentally, that wasn't the blocking issue.  The blocking one is labeled `B.`.

2021-12-01 19:22 UTC, fkang-pu commented on DataRepo/templates/DataRepo/animal_detail.html
> +                        <a href="{% url 'msrun_detail' i.msrun_id %}">MSRun Detail</a>
The rows are from a DataFrame for all animals including sample and  msrun columns. I could include all 4 msrun columns, but prefer to make it with a fewer columns. The sample list table contains more columns which a user can  also filter data based on an animal. I will wait a bit to see feedback from the lab. Should be easy to make such improvement.

2021-12-01 19:27 UTC, fkang-pu commented on DataRepo/templates/DataRepo/peakgroupset_detail.html
> +<h5><a href="{% url 'search_basic' 'PeakGroupSet' 'filename' 'iexact' peakgroupset.filename 'peakdata' %}">View Peak Data</a></h5>
Thanks, Added to my list  and will wait more suggestions/feedback from the lab. Will make minor changes to the templates in a new PR.

2021-12-01 19:30 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +def hmdb_id_url(hmdb_id):
B. Actually, upon second look, I see a problem here. The code that calls this is:
```
<td><a href="{{ i.hmdb_id |hmdb_id_url }}">{{ i.hmdb_id }}</a></td>
```
If it returns none, the href value will be `None`.  It will still be a link and will not work. I think that instead of using a filter, this should be coded as a conditional in the template.

2021-12-01 19:35 UTC, fkang-pu commented on DataRepo/templates/home.html
> +    </style>
I think you created extra_css file a while ago. I could add to it later. Right now I prefer to leave in home.html, so it's easy for everyone to change the color code. I was not sure if the colors I selected was good enough.

2021-12-01 19:42 UTC, fkang-pu commented on DataRepo/templates/home.html
> +                <div class="text-dark"><i class="fas fa-angle-right"></i></div>
I thought about make minor changes, but it would still appear as 8 blocks of similar code. I think it's probably better to address it in a separate PR.  I'll create an issue for it,

2021-12-01 19:45 UTC, hepcat72 commented on DataRepo/templates/home.html
> +                <div class="text-dark"><i class="fas fa-angle-right"></i></div>
Just want to note that this question is unrelated to the jscpd error issue.  I was simply wondering if `span` would be a better tag to use than `i`.

2021-12-01 19:46 UTC, fkang-pu commented on DataRepo/templates/sidebar.html
> +        <!--a href="{% url 'peakdata_list' %}" class="list-group-item list-group-item-action bg-light">Peak Data</a-->
I was not certain if we would bring those items back to the left menu later or get rid of left menu completely. I would just leave it for now, and make further improvements on templates after collecting comments/suggestions from the lab.

2021-12-01 19:53 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +def hmdb_id_url(hmdb_id):
Existing filters uses Camel-case  except "count_tracer_groups". For some cases, it seems easier to see the function of the filter using underscore.  I am not good with the names. We could discuss and come up a list of names for all filters. Will leave them unchanged for this PR.

2021-12-01 20:00 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
I felt Compound.HMDB_CPD_URL is just a hard code of the url. Spell it out in filter seems simpler and easy to see the function without importing Compound from the models.

2021-12-01 20:03 UTC, jcmatese commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
You could just use this property
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/9a9f7f454f6c70496bd668823a7ab1b8ff62778e/DataRepo/models.py#L229-L232

2021-12-01 20:04 UTC, fkang-pu commented on DataRepo/utils.py
Based on my tests, it seems Pandas 1.3.4 has improved handling of dtypes and `convert_dtypes` functions works so far. The tests I added to test_utils.py should cover edge cases.

2021-12-01 20:07 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
The concern isn't WRT how easy it is to read - it's with how easy it is to maintain. Things like hard-coded external URLs should only exist in 1 place.  This makes updating them easier. And I think John's suggestion is the way to go.  Better than my suggestion.  Though you still need an import.

2021-12-01 20:10 UTC, jcmatese commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
I suppose if you are working with attribute values in a dataframe, you might not actually have access to a Compound instance...

2021-12-01 20:12 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
> I suppose if you are working with attribute values in a dataframe, you might not actually have access to a Compound instance...

You don't need an instance.  It's a class variable.

2021-12-01 20:13 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
Oh, you're referring to the function... Could make it a class method that accepts a hmdb ID.

2021-12-01 20:19 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
Yes. Unless it's a class method. it's not callable with the function.

2021-12-01 20:20 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +def hmdb_id_url(hmdb_id):
Incidentally, `count_tracer_groups` was added after the camel-case convention was established when I created the file. But either way, this is a non-blocking issue. I just like to see naming convention consistency. And I think that using underscores would probably have been better, since that seems to be function name convention established in other files. Someone probably should have brought this up when I first put this file in a PR.

2021-12-01 20:20 UTC, fkang-pu commented on DataRepo/views.py
> +    file_count = len(PeakGroupSet.objects.all())
Seems Django doc. suggests to use len() instead of count() if possible.

2021-12-01 20:23 UTC, hepcat72 commented on DataRepo/views.py
> +    file_count = len(PeakGroupSet.objects.all())
Huh. OK. I wonder why they would event provide that if it's better to use `len()`... weird.

2021-12-01 20:24 UTC, fkang-pu commented on requirements/common.txt
> +pandas==1.3.4
Yes. Need to upgrade Pandas to at least version 1.2.0 to handle null values in Int columns. Initially had issues with 1.3.4, used 1.2.0 instead. I fixed a few issues last night to make my new code and test code working with version 1.3.4.

2021-12-01 20:31 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +    return dateparse.parse_duration(value).days // 7
I think they should stay as two different filters.  e.g. `duration_iso_to_weeks` convert timedelta in ISO format to weeks  (42 days  as 'P42DT0H0M0S'  in ISO format).

2021-12-01 20:36 UTC, hepcat72 commented on DataRepo/templatetags/customtags.py
> +    return dateparse.parse_duration(value).days // 7
I see. So it's not a `timedelta` object as returned by the ORM, because that's how pandas deals with it.  That makes sense.

2021-12-01 20:53 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +def hmdb_id_url(hmdb_id):
Just pushed a commit for handling href with None value for hmdb_id.

2021-12-01 21:06 UTC, fkang-pu commented on DataRepo/templates/DataRepo/animal_detail.html
> +                <td>{{ animal.age |durationToWeeks }}</td>
This age value is from ORM directly, so it's correct to use this filter.

2021-12-01 21:13 UTC, fkang-pu commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
In terms of `def hmdb_url()`, I think it might be better to make it a static method in utils.py later. It's not top priority right now.

2021-12-01 21:30 UTC, fkang-pu commented on DataRepo/views.py
> +    file_count = len(PeakGroupSet.objects.all())
Sorry I was totally wrong. Django doc states using len() is not as efficient as using count(). Somehow it registered in my mind in opposite way. I made changes to use count() now. good catch!  just pushed a commit.

2021-12-02 15:23 UTC, jcmatese approved these changes
Fine by me.  Just check that all the version upgrades would be copacetic to checkout on official servers...

2021-12-02 15:51 UTC, hepcat72 commented
When you're done making changes, let me know when this is ready for re-review by clicking the re-request review button...
<img width="336" alt="rereview" src="https://user-images.githubusercontent.com/2300532/144455981-d0c48150-90f1-4863-b1f4-dcb89f0adc94.png">

2021-12-02 16:02 UTC, fkang-pu commented
I researched a bit to see if I could modify code blocks in home.html. Haven't found a better solution I like. Will create an issue to address it later. Stop changing code now unless there are new blocking issue(s).

2021-12-02 16:15 UTC, hepcat72 approved these changes
The blocking issues have been addressed, so approving, though I will note that I can't find the issues related to comments where the creation of an issue was mentioned. Just noting so they won't fall through the cracks.

2021-12-06 20:58 UTC, lparsons approved these changes
Excellent additions that make it much simpler to get an idea of what is in the database and browse through the records. There were a few places I commented where some of the code could be made a bit clearer. One additional comment:

NB: If the new test data files are all part of a new study, I think it would be easier to keep track of them if they were organized in their own directory and named according to the type of data file they are (see #172). For example:
```
test_data_frames/
├─ sample_headers_set1.yaml
├─ sample_headers_set2.yaml
├─ sample_headers_set3.yaml
├─ samples_set1.tsv
├─ samples_set2.tsv
├─ samples_set3.tsv
```

2021-12-06 20:58 UTC, lparsons commented on .jscpd.json
> +    "**/home.html"
NB: I'd prefer that [specific blocks be ignored](https://www.npmjs.com/package/jscpd#ignored-blocks) instead of the entire file.

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templates/DataRepo/animal_detail.html
> +                {% if animal.tracer_compound.name %}
NB: I think this is intended to catch the case where there is no tracer, in which case, I would think this could raise an `NoneType` exception. IIf that is the case being tested for, it would be clearer to write `if animal.tracer_compound is None` here.

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templates/DataRepo/animal_detail.html
> +                <td>{{ animal.age |durationToWeeks }}</td>
NB: The naming convention used here is different than elsewhere (CamelCase here but underscores elsewhere). It would be preferable use a consistent naming convention (underscores).

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templates/DataRepo/compound_detail.html
> +                    {{ i.name }} {% if not forloop.last %};{% endif %}
NB: The `join` filter would be simpler to read.

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templates/sidebar.html
> +        <!--a href="{% url 'peakdata_list' %}" class="list-group-item list-group-item-action bg-light">Peak Data</a-->
NB: Generally, it's best to remove commented code. We have git history if we need to get it back. https://kentcdodds.com/blog/please-dont-commit-commented-out-code

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templates/DataRepo/compound_list.html
> +            {% for i in df %}
NB: It's easier to read the code later if you use more meaningful variable names. For example, use `row` instead of just `i`. The use of `i` is especially confusing in this case since often `i` is used as the index in a loop (e.g. 1, 2, 3, ...) but in this case it actually the row.

2021-12-06 20:58 UTC, lparsons commented on DataRepo/templatetags/customtags.py
> +        return f"https://hmdb.ca/metabolites/{hmdb_id}"
At the very least, `Compound.HMDB_CPD_URL` should be used here. In order to stay [DRY](https://realpython.com/lessons/dry-principle/), there should be a single method that constructs the URL. It would make sense to make a class method (e.g. `hmdb_url_for_id`) and then call that from the instance method (`hmdb_id`).

2021-12-06 21:19 UTC, fkang-pu commented
I added a note for myself before merging this PR, will improve the handling of hmdb_url in a new PR.

2021-12-06 21:19 UTC, merged