Addition of PeakGroup and PeakData models
Princeton-LSI-ResearchComputing/tracebase pull request #37
Opened 2021-04-15 20:11 UTC by jcmatese

Add PeakGroup model
Add PeakData model
Add rudimentary tests of these models
Abstract tracer-labeled test data

## Summary Change Description

Briefly describe the changes in this pull request (not intended as a full
recounting of the issue description).

## Affected Issue Numbers

- Resolves #21 

## Code Review Notes

Check nullability (or not) on data measurement and tracer-label requirements.
I added a composite constraint on PeakGroup that might not have been been specified

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-04-16 01:45 UTC, lparsons approved these changes
Looks good to me. I especially like the `help_text` additions.

2021-04-16 01:45 UTC, lparsons commented on DataRepo/models.py
> +# This simply shares some configured variables/values.
Nice idea, and thanks for pointing to those docs.

2021-04-16 01:45 UTC, lparsons commented on DataRepo/models.py
> +        help_text="Compound or isomer group name [i.e. citrate/isocitrate]",
Very nice addition to add the `help_text`, I think we should do this for the other classes as well (not in this PR, but later).

2021-04-16 01:45 UTC, lparsons commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
```suggestion
        "'1' means one element is labeled.  '3' means 3 elements are labeled",
```

2021-04-16 01:45 UTC, lparsons commented on DataRepo/tests.py
> +    def test_peak_group_unique_constraint(self):
Nice idea to start adding some tests like this. Thanks.

2021-04-16 12:46 UTC, jcmatese commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
I think in this case, atom _might_ actually be the more appropriate term. For example "Carbon is the labeled element in this experiment.  In this class (mspeak) of labeled glucose molecules,  3 of the 6 carbon atoms in the ring are labeled."

2021-04-16 12:59 UTC, lparsons commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
It's certainly how I would have stated it in the past, but now I'm not sure.

2021-04-16 14:16 UTC, lparsons commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
I actually think you are correct @jcmatese. For this PR, I don't want to get bogged down, we should proceed forward with whichever term. I'd like to continue this discussion in issue #35 .

2021-04-16 15:27 UTC, fkang-pu approved these changes
Looks good to me. I added a few comments, but don't mean to hold it back.

2021-04-16 15:27 UTC, fkang-pu commented on DataRepo/models.py
> -        default=CARBON,
Just add a note here since I am not sure about default value for this field.  let's move forward with data loading to see if it could be an issue.

2021-04-16 15:27 UTC, fkang-pu commented on DataRepo/models.py
> +
I'd like to see how the this model design works for a few sets of data, especially for citrate/isocitrate cases.

2021-04-16 16:25 UTC, jcmatese commented on DataRepo/models.py
> -        default=CARBON,
Yes, mapping of user values to database control values is going to be an issue.

```
$ cut -f8 DataRepo/example_data/obob_maven_6eaas_inf_original.tsv | sort -u
C12 PARENT
C13-label-1
C13-label-2
C13-label-3
C13-label-4
C13-label-5
C13-label-6
isotopeLabel
```

It is always possible that semantically, we are talking about different things.

2021-04-16 16:28 UTC, jcmatese commented on DataRepo/models.py
> +
yes, mapping the user's string on the result files back to our singular compound name will likely be an issue (upper/lower-case, aliases, ambiguous MS detection, etc.)

2021-04-16 16:29 UTC, lparsons commented on DataRepo/models.py
> -        default=CARBON,
Just an FYI, those values (`C12 PARENT`, C13-label-1` are output directly from El-Maven, and carried over in AccuCor). Any table loading script should be able to interpret them as `label_count 0`, `label_count 1`, etc.

2021-04-16 16:30 UTC, lparsons commented on DataRepo/models.py
> +
Compound names in the users El-Maven / AccuCor files will have to match what we have. If it doesn't, they will be required to fix the discrepancy.

2021-04-16 16:36 UTC, jcmatese commented on DataRepo/models.py
> -        default=CARBON,
Yah, I just don't know exactly what the data loader will pay _most_ attention to at this time, because the concepts are encoded in different ways in different outputs (i.e. the dataloader will have to compile/re-organize, and pick and choose where to map data from)
For example, in the related/paired corrected file/sheet:
```
$ cut -f2 DataRepo/example_data/obob_maven_6eaas_inf_corrected.tsv | sort -u
0
1
2
3
4
5
6
C_Label 
```

2021-04-16 16:38 UTC, jcmatese commented on DataRepo/models.py
> -        default=CARBON,
But in this case, to my thinking, the value should be '**C**'

2021-04-16 16:41 UTC, lparsons commented on DataRepo/models.py
> -        default=CARBON,
No worries, these are output in a predictable way. The AccuCor code parses the original sheet and outputs the parsed values in the corrected sheet. We may have to ask about the which atom was labeled (C, O, H, etc.) if we're loading raw (El-Maven) data, so having that as an argument the loading script seems fine to me.

2021-04-16 17:06 UTC, hepcat72 requested changes
Good stuff in here.  Nothing is technically blocking, though I did ask for some documentation for the PeakData class via a comment that I feel somewhat firm about, but there are some questions that could be significant. I'm fine with merging, but I thought there was enough to establish agreement on to mark it as "request changes", even though that agreement may just mean me coming up to speed on some model decisions.

2021-04-16 17:06 UTC, hepcat72 commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
Q. This file is fully auto-generated, right?  No manual edits?

2021-04-16 17:06 UTC, hepcat72 commented on DataRepo/models.py
> +        max_length=256, help_text="molecular formula of the compound [i.e. C6H12O6]"
i.e. = "in other words"
e.g. = "for example"

2021-04-16 17:14 UTC, jcmatese commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
The primary issues were superlinter related.  I think `isort` will reformat _every_ migration, so it must be run before PR.  Also, I discovered that if flake8 discovers >120 character line in `models.py` (for example, a longish `help_text `value), and you fix it there, you also have to fix it _again_ in the generated migrations, which is kind of annoying.

2021-04-16 17:20 UTC, jcmatese commented on DataRepo/models.py
> +    MAX_LABELED_COUNT = 20
This is the max number of labeled atoms in a tracer molecule.  It is set to 20, because the the maximum C-labeled tracer example we had was the fully labeled C16 palmitic acid (and most of the MS-detected metabolites are also <20 carbon atoms).   In the big scheme of things, it is probably necessary, other than providing a guideline or upper limit, if someone were ever to make a form/menu.

2021-04-16 17:24 UTC, jcmatese commented on DataRepo/models.py
> +        validators=[
Yes, I did not add `help_text` for the previously defined models, but I imagine someone will go back and augment them with [Michael's file ](https://docs.google.com/spreadsheets/d/1UI2Fs1hW6RiDcM7JhJYfG6yhecSQ8u7A9vaxSrJGeW0/edit#gid=0)

2021-04-16 17:38 UTC, jcmatese commented on DataRepo/models.py
> +    name = models.CharField(
There is a separately defined link(s) to the compound table (many-to-many) that are defined.  The current design falls out from 2 previous decisions.
1) the compound table represents single, unique molecular entities (1 HMDB).
2) the lab's MS protocols (selective reaction monitoring) cannot distinguish some isomers at the same mass and retention time, like citrate/isocitrate.

So 95% of the time a peak group name will be the singular compound name, except when it is not.  In other projects, we actually created protocols attached to the MS-Run where each MS reaction was defined (instrument and chromatography parameterization), and each reaction in the protocol was explicitly mapped to one or more metabolites.  We are not doing that in this project, but trying to use a heuristic (presumed compound).

2021-04-16 17:42 UTC, jcmatese commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
But yes, there is nothing in here that was not derived from the models, even though I had to manually edit them to get a green check from superlinter.

2021-04-16 18:19 UTC, jcmatese commented on DataRepo/models.py
> +        unique_together = ("name", "ms_run")
I believe this resolves to "there shall be only 1 peak group named/labeled _X_ in this MsRun".  There is a many-to-many relationship between PeakGroup and Compound. 
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/20fbc07422df4edfbb7d14bd736df808b69d355b/DataRepo/models.py#L177-L181

2021-04-16 18:22 UTC, jcmatese commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
I just grabbed it from [here](https://docs.google.com/spreadsheets/d/1UI2Fs1hW6RiDcM7JhJYfG6yhecSQ8u7A9vaxSrJGeW0/edit#gid=0)

2021-04-16 18:25 UTC, jcmatese commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
[I guess is means something to the users](https://www.chemguide.co.uk/analysis/masspec/mplus.html), of which I was unaware

2021-04-16 18:38 UTC, jcmatese commented on DataRepo/models.py
> +
```suggestion
# PeakData is a single observation (at the most atomic level) of a MS-detected molecule.
# For example, this could describe the data for M+2 in glucose from mouse 345 brain tissue.
```

2021-04-16 18:43 UTC, jcmatese commented on DataRepo/models.py
> +class PeakData(models.Model, TracerLabeledClass):
Does the suggestion above address your comment ([source](https://docs.google.com/spreadsheets/d/1UI2Fs1hW6RiDcM7JhJYfG6yhecSQ8u7A9vaxSrJGeW0/edit#gid=0))?

2021-04-16 18:45 UTC, hepcat72 commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
I assume that the complaint from superlinter originated from pylint as opposed to black or isort? I wonder if a local run of superlinter's black/isort components actually make changes or not.  Either way, resolving this.

2021-04-16 18:48 UTC, hepcat72 commented on DataRepo/models.py
> +    MAX_LABELED_COUNT = 20
The form reason seems sufficient.  Assuming that the compounds we've seen represent the comprehensive range of sizes we would ever encounter in the future, I will resolve.

2021-04-16 18:51 UTC, hepcat72 commented on DataRepo/models.py
> +        validators=[
Given this is a formatting edit, I think asking for the help text here would be beyond the scope of this PR, so I will resolve.  I will create an issue just in case.

2021-04-16 18:56 UTC, jcmatese commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
Nope it was [isort](https://github.com/Princeton-LSI-ResearchComputing/tracebase/runs/2358109615?check_suite_focus=true#step:4:843), wrapped by superlinter, insisting that `import DataRepo.models` must precede `import django.*`, because alphabet is important.  Superlinter must be running it in a mode of, "would you have made changes? if so, FAIL"

2021-04-16 19:13 UTC, hepcat72 commented on DataRepo/models.py
> +    name = models.CharField(
Thanks for the clear explanation.  I understand (though I haven't verified by checking the model) that there is a many to many link with compounds and that there exist compounds with the same mass that cannot be distinguished via mass (unless say, they were given different numbers of labeled carbons).  However, the relationship between a peak group "representative" compound column to the compound table is M:1.  And storing the name of the compound here duplicates it.

I'm fine with the reason for this being: we expect no changes to compound names and the convenience having it duplicated here outweighs the potential overhead of changing a compound name in multiple places.  However, I don't think anything above necessarily dictates it needs to be here.

I'm going to resolve this.  I mainly just wanted to make sure I wasn't misunderstanding anything.

2021-04-16 19:15 UTC, hepcat72 commented on DataRepo/models.py
> +        unique_together = ("name", "ms_run")
Good enough.  Just wanted to make sure we're all thinking the same about this.

2021-04-16 19:18 UTC, hepcat72 commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
OK.  You know what... I'll ask them on slack for my own edification.  I'll leave this issue unresolved until I hear back.

2021-04-16 19:40 UTC, hepcat72 commented on DataRepo/models.py
> +        "'1' means one atom is labeled.  '3' means 3 atoms are labeled",
OK, `M` stands for mass and `M+` means increased mass.  The scope is a molecule (as opposed to an atom in a molecule).  An atom with extra neutrons is a labeled atom, and a molecule can have multiple of these (randomly included in any position).  The only important thing is the overall number of extra neutrons in the molecule, which this count represents.  And I suppose technically, it could include an atom with 2 extra neutrons (assuming fewer neutrons is not considered).

Since this is their text, I say leave it.  Though it could help us keep things straight if we added a comment and/or updated field/variable names to convey the context.  We use label in 2 different contexts in the repo: the context of an atom and the context of a molecule.  So perhaps:

- `mol_label_count`
- # The number of extra neutrons per molecule

I'm clear now, so I'll leave it up to you.

2021-04-16 19:46 UTC, hepcat72 commented on DataRepo/models.py
> +class PeakData(models.Model, TracerLabeledClass):
Yes. Thanks.

2021-04-16 19:46 UTC, hepcat72 commented on DataRepo/models.py
> +
I was just going to paste that.

2021-04-16 19:48 UTC, hepcat72 commented on DataRepo/models.py
> +# This simply shares some configured variables/values.
I'm going to take the liberty of resolving open issues that appear read & resolved.

2021-04-16 19:51 UTC, hepcat72 commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
I'll look and see if there's a way to run it locally with modifications enabled.

2021-04-16 20:01 UTC, hepcat72 commented on DataRepo/migrations/0004_PeakGroup_Data.py
> +    ]
Doesn't seem possible upon first google, though I guess a run of black and isort independently could come in handy.

2021-04-19 16:21 UTC, hepcat72 approved these changes
Since my questions are answered and my remaining issues are NB, I am changing to approve. HMU for a second round review if anything changes other than my suggestions.

2021-04-20 22:15 UTC, merged