Restore linting to .github directory
Princeton-LSI-ResearchComputing/tracebase pull request #38
Opened 2021-04-16 00:42 UTC by lparsons

## Summary Change Description

Comments were added to to have `markdownlint` skip the MD041
first-line-heading errors on the github issues and pr templates. This
allows us to have the rest of the templates linted and explicitly
indicates the exception we decided to make. It also simplifies to the
superlinter config.

## Affected Issue Numbers

None

## Code Review Notes

None

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-04-16 14:40 UTC, hepcat72 commented
I had tried the first-line skip and ran into other issues.  1 was an issue with a level jump (from no header to level 2), which was silent for the issue templates, but errored on the PR template (due to the `----` section presence/absence at the top).  I feel like there was a third, but I can't recall.  Before I look them up in the commit logs, have you ensured that linting is actually happening and that local linting and superlinter agree and happen? I'm surprised you do not encounter the other issues.

2021-04-16 14:46 UTC, hepcat72 commented
I'm not sure it's actually working.  I pulled your branch and specifically ran the files and I get 3 types of errors:
```
$ markdownlint .github/*/* --config .markdown-lint.yml 
.github/workflows/superlinter.yml:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "name: Super-Linter"]
.github/workflows/superlinter.yml:7:1 MD023/heading-start-left/header-start-left Headings must start at the beginning of the line [Context: "  # Set the job key. The key i..."]
.github/workflows/superlinter.yml:8:1 MD023/heading-start-left/header-start-left Headings must start at the beginning of the line [Context: "  # when a job name is not pro..."]
.github/workflows/tracebase-tests.yml:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "name: TraceBase Tests"]
```
Am I doing something wrong?

2021-04-16 14:53 UTC, hepcat72 requested changes
hmm, it seems my errors are WRT yml files.

2021-04-16 14:57 UTC, hepcat72 approved these changes
I see my mistake.  The errors I saw were WRT yml files.  Changing review.  LGTM.

2021-04-21 14:42 UTC, jcmatese approved these changes

2021-04-21 15:03 UTC, merged