Models package init
Princeton-LSI-ResearchComputing/tracebase pull request #411
Opened 2022-04-06 19:52 UTC by lparsons

## Summary Change Description

This PR breaks the `models.py` file into a package with most models in an individual file. Each model was imported at the package level in `__init__.py` to make imports simpler. It also keeps the imports in the rest of the code the same. For example instead of `from DataRepo.models.animal import Animal` one can still use the style `from DataRepo.models import Animal`. Note that I did not import all of the functions in the `models.utilities` module into the package to keep the namespace clean, so those imports did have to change.

## Affected Issue Numbers

- Resolves #404 

## Code Review Notes

This is basically the same as #409, but using the package level imports.

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2022-04-06 20:25 UTC, jcmatese approved these changes
I imagine this might be preferable to the group, and I certainly have nothing against it

2022-04-06 20:25 UTC, jcmatese commented on DataRepo/models/sample.py
> +from .peakgroup import PeakGroup
```suggestion
from .peak_data import PeakData
from .peak_group import PeakGroup
```
guessing...

2022-04-06 20:25 UTC, jcmatese commented on DataRepo/models/peak_data.py
> +from .peakgroup import PeakGroup
```suggestion
from .peak_group import PeakGroup
```

2022-04-06 20:25 UTC, jcmatese commented on DataRepo/models/peak_data.py
> +from .tracerlabeledclass import TracerLabeledClass
```suggestion
from .tracer_labeled_class import TracerLabeledClass
```

2022-04-06 21:54 UTC, hepcat72 reviewed
I'm not finished with this review. I need to figure out a way to observe changes from original code.  Submitting this for now. I'll finish it tomorrow.

2022-04-06 21:54 UTC, hepcat72 commented on DataRepo/models/utilities.py
> +    ]
NB. Could this be defined in the init file and referenced here? I think that might make sense when it comes to adding/removing/changing models.

2022-04-06 21:54 UTC, hepcat72 commented on DataRepo/models/utilities.py
> +    mdls = [getattr(module, class_name) for class_name in model_names]
B. This can potentially create a data integrity issue in 2 places.  One is the validation database.  If models are added to the software and this is not updated, it could cause silent "leaks" in the validation database of accumulating values that could cause difficult to debug errors.  The other is the various researcher fields.  If a researcher field is included in a new model and this is not updated, researcher names could accumulate variants.

This is simple to fix.  I think that maintaining a static set of ordered models is reasonable even though the original reliance on appconfig.get_models() returns an ordered_dict in the correct order because it's an internal method and is not documented in terms of the order in which it returns models, so it could change, but I think that the static list should be validated for completeness by the dynamically generated set.  Something like:

```python
missing = []
for mdl in apps.get_app_config("DataRepo").get_models():
    if mdl not in mdls:
        missing.append(mdl)
if len(missing) > 0:
    raise Exception(f"Model list is missing these models: [{','.join(missing)}]")
```

Actually, you could put this in a test instead of here...

2022-04-07 13:07 UTC, jcmatese commented on DataRepo/models/utilities.py
> +    ]
I think this might be possible, and would make sense (and we just have to have a protocol section in the CONTRIBUTING reading about the addition of new models classes, like a note to "remember to edit `__init__.ALL_MODELS_IN_SAFE_DELETION_ORDER` , or similar)

2022-04-07 15:47 UTC, hepcat72 commented on DataRepo/models/utilities.py
> +    mdls = [getattr(module, class_name) for class_name in model_names]
It's also used to dynamically find fields named `researcher` in order to prevent researcher name variants, though for that purpose, order is unimportant.

2022-04-07 16:57 UTC, hepcat72 commented
And putting it all in 1 command...

```
for f in DataRepo/models/*.py; do git -c color.diff=always diff HEAD^^:DataRepo/models.py $f | grep -v ^.....\- -B 10 -A 10; done
```

2022-04-07 17:11 UTC, hepcat72 commented on DataRepo/models/compound.py
> +        Compound, related_name="synonyms", on_delete=models.CASCADE
NB. Elsewhere the linked to Model argument was changed to a named parameter, e.g. `to="DataRepo.<Model>"`. However, there is this and 3 other spots where that modification was not made (Foreign keys to `Protocol`, another `Compound`, and `PeakGroup`) in `animal.py`, `animal.py`, and `peak_data.py` respectively.

I would change those to a named parameter to be consistent, unless modification of those was excluded for a specific reason...

2022-04-07 19:12 UTC, jcmatese approved these changes

2022-04-18 21:02 UTC, fkang-pu approved these changes
It seems a better strategy for splitting models.py into multiple files (using the package level imports).

2022-04-20 20:00 UTC, hepcat72 requested changes
Battery is dying, so quick comment. I didn't see a resolution to me previous blocking issue. Did I miss it?

2022-04-20 20:00 UTC, hepcat72 commented on DataRepo/models/utilities.py
> +    ]
B. I'd still like to see this issue addressed: https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/411#discussion_r844449770

2022-04-20 20:08 UTC, lparsons commented on DataRepo/models/utilities.py
> +    ]
Oops, sorry. I missed adding the new test file for that. Added now.

2022-04-21 13:50 UTC, hepcat72 approved these changes
Great.

2022-04-21 18:12 UTC, merged