Multiforms refactor
Princeton-LSI-ResearchComputing/tracebase pull request #418
Opened 2022-04-26 18:42 UTC by hepcat72

## Summary Change Description

`multiforms.py` was refactored so that the advanced search class in views.py no longer needs to override the post method.

I misunderstood both the intent of multiforms and how it was implemented, thus when I applied it, my efforts did not jive with the original code.  Now it does.  Here are some of my key misconceptions about multiforms, what I originally did, and how I changed it to conform to the original design:

- Multiforms was written so that a single view can handle multiple types of form submissions (in no way does it do anything special to handle formsets (multiple instances of the same form type (i.e. copies of the same form inside one pair of form tags)).  This involves a few key mechanisms:
   - Identify the form that was submitted
   - Bind the correct form class to the submitted form data
   - Validate the form data
   - Return the correct response
- Multiforms uses a modified version of a django-y trick to identify form types.  It uses a field in the form data "string" to identify a form.
   - Multiforms assumes that the form-identifying field is named "action"
   - The "action" field contains a string that is used as a key in a dict lookup to get the class in order to bind it to the form data and process the form.
   - It also uses that key to call different versions of methods like, `<key_>form_valid`, `<key_>form_invalid`, and other methods, I did not utilize.
   - And it turns out that in the case of "grouped forms", the value in the action field was a key into the `grouped_forms` dict, whose value was a list of keys into the `form_classes` dict and specified forms that should be processed in a single submission, which was similar to my mixed form case, but not exactly.

Since multiforms.py overloaded the term "form name" (which I took literally as the name of the form element in the HTML), I originally did not understand why the methods I wrote were not getting called.  Plus, the fallback was to call the generic methods, so I had trouble debugging.

After newly understanding the way forms were identified, I decided I didn't want to go to the effort to add an "action" field to each form.  Instead, I allowed forms to be identified by simply the presence of a field with a specific name, instead of the value of a field that every form was required to have.

And, I made my mixed form case be much like the grouped forms case, except the only form that is bound is the "selected" form (indicated by the value in that field).

## Affected Issue Numbers

- Resolves #370

## Code Review Notes

I tried to add comments to help reviewers and others who read the code, but it all hinges on the post method override.  I also made the form setup more transparent by adding the form types in a new __init__ method in the advanced search class.  There are 2 types that are added: an "individual" form type for the paging form, and a "mixed" form type for the 3 advanced search form types (peak group, peak data, and FCirc).

When post is called upon form submission, the post method iterates through the keys `fmt` (the format select list) and `paging` (a hidden field to identify the paging form) to see if fields exist by either of those names.

If it's the paging form, the form is validated and either `paging_form_valid` or `paging_form_invalid` is called and the response they return is returned by post.

If it's the advanced search form, the selected form type is identified from the `fmt` select list, that type is bound, and every instance of all the advanced search forms is validated using the `is_valid` method of the selected form class.  Then either `form_valid` or `form_invalid` is called (since the `fmt_form_[in]valid` methods don't exist).

I added some exceptions and other feedback to make it easier to debug any issues should they arise in the future.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2022-04-26 18:46 UTC, hepcat72 commented on DataRepo/pager.py
> -        self.form_name = form_name
It turned out that the form name is never used in multiforms - it overloaded the term "form name".  It's really just an arbitrary key into either the `form_classes` dict or the `grouped_forms` dict, which was previously obtained from a field named `action`.  That field was what identified the form type.

2022-04-26 18:48 UTC, hepcat72 commented on DataRepo/views.py
> +        self.add_individual_form(self.pager.form_id_field, self.pager.page_form_class)
I thought crreating methods to be called in an `init` would be more transparent.

2022-04-26 18:54 UTC, hepcat72 commented on DataRepo/multiforms.py
> +                self.add_individual_form(form_key, self.form_classes[form_key])
This init method is currently unused (i.e. not called via super from the advanced search class's init method).  I initially wrote it so that all you had to do was set values for form_classes and `mixed_forms`, but I felt like that was difficult to understand, so I overrode the init method.  This still works though if you do it the other way.

2022-04-28 19:03 UTC, jcmatese approved these changes
Thanks for the docs.  If it does what you want it do, go for it.  I had trouble following where things were being defined (like the keys of `self.grouped_forms`) in MultiFormMixin, and I am not certain I have an intuition for the difference between `Grouped` and `Mixed` forms (despite the docs.  But that is my cognitive problem, not a problem with the code.

2022-04-28 20:43 UTC, hepcat72 commented
> Thanks for the docs. If it does what you want it do, go for it. I had trouble following where things were being defined (like the keys of `self.grouped_forms`) in MultiFormMixin, and I am not certain I have an intuition for the difference between `Grouped` and `Mixed` forms (despite the docs. But that is my cognitive problem, not a problem with the code.

This being a refactor, the working state has not changed - it still does everything it could do before the refactor, and no more.  But readability being a goal, I'm open to suggestions.

The difference between Grouped and Mixed forms is that Grouped binds and validates all form classes in the group.  Mixed only binds one form class and validates all forms using that class.  "Grouped" requires that all form types pass validation whereas mixed only requires that the selected form passes validation (e.g. "all required fields filled in").

Mixed requires that all included forms have the same fields.  And each form class must be able to tell one-another apart so that it validates correctly based on the "selected" class (/"Format", e.g. PeakGroups).  I.e. each form has to recognize and duly ignore (or rather, rubber-stamp as valid) forms of other types.

Since I haven't used "grouped" forms, I'm not actually sure how it works, but my understanding inferred from the code is that it processes independent form submissions at once.  I think that each form is inside its own pair of form tags.  Otherwise, I wouldn't know how it validates multiple form classes in a single submission, because I don't see how it's even possible to submit multiple forms (of different types) at once.  I know that formsets are multiple copies of the same form submitted at once, but I have not seen an example using different forms.  The `multiforms` code is/was so poorly documented and thus it assumed a bunch of django form knowledge that I did not have when I originally found it.

2022-05-03 16:06 UTC, lparsons requested changes
I don't fully understand how the various form types are intended to work, but this PR does seems to simplify the code. Great job learning and applying some improved understanding of Django here.

I had a couple of notes, with the one blocking issue being the raising of generic Exceptions, which should be a simple fix, but I feel a potentially important one.

2022-05-03 16:06 UTC, lparsons commented on DataRepo/multiforms.py
> +            raise Exception(
B: Is there a more specific Exception type we could raise here? Using a generic `Exception` means that to catch it, we would have to catch all other more specific exceptions that subclass it. Maybe there is already a suitable Django Exception, otherwise, it might make sense to create a custom exception type. 

Note: this applies elsewhere in this PR, just noting it once here)

2022-05-03 16:06 UTC, lparsons commented on DataRepo/multiforms.py
> +            raise Exception(
B: Is there a more specific Exception type we could raise here? Using a generic `Exception` means that to catch it, we would have to catch all other more specific exceptions that subclass it. Maybe there is already a suitable Django Exception, otherwise, it might make sense to create a custom exception type.

2022-05-03 16:50 UTC, hepcat72 commented on DataRepo/pager.py
>              init_dict[self.form_id_field] = 1
- [ ] Use `init_dict.setdefault` in the pager class

2022-05-03 16:53 UTC, hepcat72 commented on DataRepo/multiforms.py
> +            raise Exception(
- [ ] Use specific exception classes.

2022-05-03 16:53 UTC, hepcat72 commented on DataRepo/multiforms.py
> +            raise Exception(
dupe comment. resolving.

2022-05-03 16:54 UTC, hepcat72 commented on DataRepo/multiforms.py
> +    # recognize and ignore forms of other types.  All forms in a mixed form type must have the same fields.
dupe comment. resolving.

2022-05-03 16:54 UTC, hepcat72 commented on DataRepo/views.py
> +        # the same page), not a field ID assignment used in  javascript
- [ ] Situate comments above relevant lines of code

2022-05-04 17:18 UTC, hepcat72 commented
I implemented all your suggestions @lparsons. I re-requested your review if you want to take another look to see if I missed anything...

2022-05-04 17:22 UTC, lparsons approved these changes
lgtm

2022-05-04 18:13 UTC, merged