Functions and tests for infusate name parsing
Princeton-LSI-ResearchComputing/tracebase pull request #441
Opened 2022-05-24 12:41 UTC by jcmatese

## Summary Change Description

Just adding a utility file and some basic tests for **_parsing_** the initial infusate naming specification.

## Affected Issue Numbers

- touches part of #407 based on proposal in #364 
  
## Code Review Notes

**_Important: It does NO validation_**, yet.

My assumption is that these functions will/might not remain in this new file(s), but might be moved elsewhere in the codebase including possibly the new models.

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2022-05-24 14:15 UTC, jcmatese commented
Sorry about the 2 separate commits both of which fail on GitHub, but pass superlinter and all my tests at home.  If someone else had an environment that is equivalent to GitHub, feel free to pull, fix and push.

2022-05-26 16:45 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    isotope_labels: list
This could _probably_ be plural, as it returns lists of compounds/isotope_labels

2022-05-26 16:45 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    infusate_name: Optional[str]
This is the optional "short_name"

2022-05-26 16:45 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    original_infusate: str
This is the submission to be parsed.

2022-05-26 22:20 UTC, hepcat72 reviewed
Pausing mid-review for time.  I'll resume tomorrow, but thought I would enter what I have so far.  There are changes I would like to see as it stands right now, but I haven't gotten to where the regular expressions are used yet, so I may edit these issues before I finish...

2022-05-26 22:20 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +INFUSATE_ENCODING_PATTERN = r"(.*)\s*\{(.*)\}"
B. I'm not as familiar with python `re`, but my understanding of regular expressions in general is that `.*` is greedy.  It will match the entire string and then back up until it can match the rest of the expression.  That means that a poorly formatted value could end up with a left curly (`{`) (or even an entire `\{.*\}` string) in the first capture group.  In the least troublesome case, the first capture group would also consume trailing spaces.  I would suggest either:

1. making the first expression not greedy with: `(.*?)\s*\{(.*)\}`, which is a more relaxed suggestion
2. also dis-allowing curlies in the first capture with a class: `([^\{\}]*?)\s*\{(.*)\}`, which is a more strict version (allowing short names with curlies)

B. Even with the above, there is the possibility that the second capture group could consume the same cases, so (assuming we go with 2 above...):

1. relaxed: `([^\{\}]*?)\s*\{(.*?)\}`
2. strict: `([^\{\}]*?)\s*\{([^\{\}]*?)\}`

B. If the supplied string is malformed and also had a newline that `.` would not pass through, and otherwise, if the greedy edits are made above, you'll need an anchor at the end.  And an anchor in the beginning wouldn't hurt either, depending on what `.` is set to match:

- `^([^\{\}]*?)\s*\{([^\{\}]*?)\}$`

Caveat: I can't guarantee that my perlre-based suggestions are correct for python.

2022-05-26 22:20 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +TRACER_ENCODING_PATTERN = r"(.*)\-\[([0-9CNHOS,\-]*)\]"
B. Same concerns/suggestions as the first and third above, relating to the first capture-group and anchors.  The second capture group does not have the greedy problem since it doesn't match square brackets.

B. I'd like to see `CNHOS`, as a variable compiled from TracerLabelClass (a.k.a. `ElementLabel` in my upcoming PR merge).

Q. Do you think it would be (preemptively) worthwhile to account for the possibility of no labels in the tracer?  I know we decided not to support that, but in this code, it shouldn't matter.  Say something like...

- `(.*)(?:\-\[([0-9CNHOS,\-]*)\])?` or...
- `(.*)(?:\-\[([0-9CNHOS,\-]*)\]|)`

2022-05-27 15:28 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +INFUSATE_ENCODING_PATTERN = r"(.*)\s*\{(.*)\}"
Thanks for checking the regex carefully @hepcat72. I agree that there are likely some cases that will get incorrectly parsed. Would you mind helping to generate a list of some test cases we can use? Just the input strings would be a great help, I'll add some additional tests and fix the regex, logic, etc.

2022-05-27 15:31 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +TRACER_ENCODING_PATTERN = r"(.*)\-\[([0-9CNHOS,\-]*)\]"
Good call making `CNHOS` a variable. I think these methods could all end up in model classes. Is that PR close to being merged?

I think adding some test cases that define how we would like to parse tracers with no labels in them would be worthwhile.

* [ ] Make `CNHOS` a variable (eventually in the `ElementLabel` class)
* [ ] Add test case for tracer with no label

2022-05-27 16:01 UTC, hepcat72 reviewed
Pausing for context switch and pushing out review items accumulated thus far...

2022-05-27 16:11 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +    r"(?:(?P<labeled_positions>[0-9,]+)-){0,1}(?P<labeled_element>[0-9]+[CHNOS])(?P<labeled_count>[0-9+])"
I think those are good instincts Rob. I'd ask that, in addition to evaluating the RegEx, we come up with some good test cases. That will help me when I work on making the code more robust. We can probably do some things like check that only certain "valid" characters are in the string as a first step (e.g. to avoid worrying about newlines, non-printable chars, etc.)

2022-05-27 16:19 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +TRACER_ENCODING_PATTERN = r"(.*)\-\[([0-9CNHOS,\-]*)\]"
Looks like (at first glance) #429 is ready.  We were debating components of #428 up until yesterday on Slack and I had been waiting for consensus before addressing any review items.  Also, I posed the possibility that I implement those items in #442 yesterday and was interested in finding out whether that was agreeable...  And while we decided how to handle `short_name`, there are a couple other things I remain unclear or undecided about...

Since `short_name` now is decided to be categorical (based on assurances of its usage outside tracebase), I agree with Fan's general suggestions to make `name` unique, and I'm amenable to (primarily) handling `short_name` validity in the loading code, but I'm pondering a change to the name of the field so it doesn't unintentionally convey the same data relationship as `name`, which I feel like it does.  I may also decide whether or not there's a model validity check that can be applied, if not holistic.

And I feel like I don't have a final answer on whether `count` is required to equal `length(positions)`. I know how people feel about it.  I just don't have the impression that it's decided.

Perhaps, inferring that's a priority, I'll switch from reviewing John's PR to getting that PR to a merge point.

2022-05-27 16:26 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    r"(?:(?P<labeled_positions>[0-9,]+)-){0,1}(?P<labeled_element>[0-9]+[CHNOS])(?P<labeled_count>[0-9+])"
Note, having progressed to the point where I see the usage of this regex, it may be a good idea to use a moving anchor, like perlre's `\G`.  And that would also necessitate including the delimiter in some fashion, like appending (and I haven't checked this):

```
(,|\Z)\G
```

Actually, maybe it goes at the beginning.  So it might have to be a prepended pattern like this:

```
\G(,|\A)
```

And note, I always confuse `\a` vs `\A` and `\z` vs `\Z`, as I think their behavior changes based on what follows the final `/` in perl.

2022-05-27 16:27 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    r"(?:(?P<labeled_positions>[0-9,]+)-){0,1}(?P<labeled_element>[0-9]+[CHNOS])(?P<labeled_count>[0-9+])"
...and I'm not even sure it python's re has these meta-pattern "characters".

2022-05-27 16:35 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    isotopes = re.findall(ISOTOPE_ENCODING_PATTERN, isotopes_string)
Cross-referencing the re comment from the top... we probably want the \G at the beginning of the pattern, not the end.

2022-06-01 15:53 UTC, hepcat72 requested changes
I think that if this PR only implements a portion of an issue, such as issue #407, I think that the issue *must* be split up.  Otherwise, there's no way to judge completeness during review and there's no way for the developer who takes on the "remainder" of the issue to know what's done and what isn't done without digging through the code.  So I would suggest either splitting issue #407 into what this PR does and what it doesn't, or implementing everything in the issue in this PR.

I will add the test strings that Lance requested in the issue.

2022-06-01 15:53 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
B. Not all tests from issue #407 have been implemented.  (Note, this could be resolved by editing the issue itself.)

2022-06-01 16:01 UTC, hepcat72 commented
Regarding the [error](https://github.com/Princeton-LSI-ResearchComputing/tracebase/runs/6574963958?check_suite_focus=true#step:12:20311) you asked about in the description, I believe that `list` is a method, thus it's treating it as a subscripted variable.  I believe the `L` needs to be capitalized and the `List` type imported.

2022-06-01 16:58 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
...or you could add checkboxes to requirement and test items in the issue and check the ones that this PR addresses.

2022-06-02 17:13 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    isotope_labels: list
I believe this was replaced with `TracerData` in Lance's commit

2022-06-02 20:24 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "short_name{tracers1}{tracers2}"
The examples in the notes were not literal strings.  The test entries in the issue owner section are the literals.  I only supplied the notes for background.  So I'll create suggestions to enter the strings I came uo with in the issue owner tests section...
```suggestion
        name = "myshortname{lysine-[13C5]}{glucose-[13C4]}"
```

2022-06-02 20:24 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "short_name1{tracers1}\nshortname2{tracers2}"
```suggestion
        name = "myshortname1{lysine-[13C5]}\nmyshortname2{glucose-[13C4]}"
```

2022-06-02 20:26 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "  short_name1{tracers1}  "
```suggestion
        name = "  myshortname{lysine-[13C5]}  "
```

2022-06-02 20:27 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
This should `expect parsed elements with white space trimmed`, not `assertRaisesRegex`

2022-06-02 20:28 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "short_name1  {tracers1}"
```suggestion
        name = "short_name1 {lysine-[13C5]}"
```

2022-06-02 20:28 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
This should `expect parsed elements with white space trimmed`, not `assertRaisesRegex`

2022-06-02 20:30 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "lys1,2,3-13C3,badlabel,19O2"
```suggestion
        name = "1,2,3-13C3,badlabel,19O2"
```

2022-06-03 16:32 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +INFUSATE_ENCODING_PATTERN = r"(.*)\s*\{(.*)\}"
I did add some more test patterns, and tweaked the regex's until the errors went away.  May still need tweaking with more examples...

2022-06-03 16:56 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +        "original_infusate": infusate_string,
So are people "happy" with the `dict` return value of these classes? I don't mind changing `original_infusate` to `input` or `original_full_name` or whatever, to make it gel with naming/conventions in other PRs.  I was hedging, because I was imagining that after validation (in some _other_ PR), the "mapped/alternate/approved" name _might_ also be in this hash.  Would a `validation_performed` `True/False` suffice?  At this parsing step, all we know is that it is parseable, not that it is valid after running through whatever gauntlet of database rules we throw at it.

2022-06-03 16:58 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
I think I got this

2022-06-03 17:11 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
I think I got this

2022-06-06 20:42 UTC, hepcat72 requested changes
I believe there remain a few blocking issues and 1 new blocking issue. I marked the remaining blocking issues (and a few select non-blocking issues) with "👀", but the main issue is the new issue in the tests where the wrong parsing method is called. If I have time, I can circle back and implement resolutions to the remaining blocking issues.

2022-06-06 20:42 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
B. This is calling the wrong parser.  It should be calling `parse_isotope_string`, but instead, it is passing this isotope string to the `parse_infusate_name` method, which of course raises an exception.  I tested this string with the `parse_isotope_string` method in the shell and it does not generate an error as it should.  It silently skips malformed isotope strings:
```
In [1]: from DataRepo.utils import infusate_name_parser as inp

...

In [10]: inp.parse_isotope_string("1,2,3-13C3,badlabel,19O2")
Out[10]: 
[{'labeled_element': '13C',
  'labeled_count': 3,
  'labeled_positions': [1, 2, 3]},
 {'labeled_element': '19O', 'labeled_count': 2, 'labeled_positions': None}]
```

2022-06-07 15:12 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
I will put in a regex of "disallowed characters" to catch this particular string, but it is not clear to me if the encoding couldn't just be malformed in another manner, which would have to rely on validation code.  If you or Lance has a replacement pattern for `ISOTOPE_ENCODING_PATTERN`, we can try that.

2022-06-07 15:40 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
This can be solved by adding an anchor (e.g. perl's `\G`).  Not sure what the equivalent python re method is, but my suggestion on how to solve it was [here](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/441#discussion_r883766290).

2022-06-07 15:56 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
And this was one reason that I was opposed to using comma for multiple delimited items.  I just googled a bit and found that there's no viable way to do a perlre `\G` equivalent.  Work-arounds involve setting the `pos` (though I didn't dig into it) and have caveats.  It seems the most reliable way to solve would be by splitting on comma and conditionally rebuilding each expression.

2022-06-07 16:02 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
Well, I suppose you could concatenate all the matches back together, and if is does not match the input, raise an error?  I would prefer if we don't delay moving forward, given the number of tracer example we have been given so far, assuming that curator are screening all inputs, and assuming that validation code is going to be layered on top of this.

2022-06-07 16:04 UTC, hepcat72 commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
That would work too. Less math.

2022-06-07 17:06 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
>              _ = parse_infusate_name(name)
tried it

2022-06-07 18:46 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
> +            _ = parse_infusate_name(name)
I believe they have been implemented. Edited the issue to star them

2022-06-07 18:47 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +        labeled_element = isotope.group("labeled_element")
I don't agree

2022-06-07 18:52 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +
I would argue that validation of length of position and count should be handled separately from the parsing. It could be done when the objects are getting created.

I do think that separating the `labeled_element` into the `mass_number` and the `element` would be a more complete parsing of the string.

2022-06-07 18:53 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    pass
I will let @lparsons  decide, as I believe he instantiated them, and this sounds like a project-wide design decision.

2022-06-07 18:58 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +
Yes, my thought was that validation is done in #444 and a companion PR, so if there are any additional validation tests that are being asked for in either this OR #441 or in the model definition PR(s) #442 , they can alway be added to that issue.

2022-06-07 19:58 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +
Just checking.  Would you two prefer **removing** the `labeled_element` key and replacing it with `mass_number` and `element`, or keep all three?

2022-06-07 20:47 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +        labeled_element = isotope.group("labeled_element")
This reminds me of when Zoe and I are leaving the grocery store and we realize we forgot something we'll need in under a week. She's like "let's just go home - we can get it later" and I'm like "What? We're here now - I just saw where it was when we were in there, let's just go in and get it. It's a whole lot less effort than coming back in a few days and trying to remember where it was." lol But maybe your and Zoe's memory is better than mine.

2022-06-07 22:29 UTC, hepcat72 reviewed
I'll resume tomorrow.

2022-06-07 22:29 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    + r",\-]+)\])$"
Q. This is rather complex and I'm not entirely convinced it's all necessary, though perhaps I'm wrong. Could you explain the purpose of these changes?

For one, it doesn't seem that the unsaved capture group `(?:...)` is necessary.  Why isn't the first capture group something simpler like `.+?`?  I mean, I can see the intent to get a valid compound that doesn't bleed into a malformed list of isotopes, but the compound name is later validated against the DB synonym content, isn't it? And why isn't the isotopes capture group something like `"[0-9" + KNOWN_ISOTOPES + r",\-]+"`, because you don't need to exclude square brackets in the first character since the positive character class doesn't have them...

I just find the resolution of previous issues a bit perplexing.  Were there problems with the proposed solutions?

2022-06-07 22:29 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    + r",\-]+)\])$"
Suspecding the rest of this review until tomorrow.

2022-06-08 13:22 UTC, fkang-pu approved these changes
I tested a few cases and they all worked. The `infusate_name` in output is a bit confusing since it's short name of an infusate(or the set of tracers).  I think it's infusate.tracer_group_name in [PR442](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/442).

2022-06-08 13:27 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
>              "BCAAs {isoleucine-[13C6,15N1];leucine-[13C6,15N1];valine-[13C5,15N1]}"
I don't have a _strong_ opinion on the format in #442 because it seemed it was potentially being introduced to satisfy the following possible aims:

1. enforce a unique key/constraint (primary purpose?)
2. be queryable? (uncertain)
3. be displayable? (uncertain)

For just the 1st purpose, I don't think the format matters, and what was proposed seems fine.  
For purposes 2 or 3, I just don't know if it is particularly suitable/advantageous, vs other possibilities and so I am not currently worried about it.  If we have a UI that queries or displays it, we can tweak it then? (e.g."maintained")

I don't _think_ we necessarily need a method to construct this non-unique format immediately, because it _might_ only serve to suggest to users how to communicate their data. 
 
That being said, if someone does come up with an expressive, but parseable string/sentence describing  an infusate that the researchers can easily adopt (that would perhaps collapse the 2 columns of  `Infusate` and `Tracer Concentrations` defined in #400), I would be open to it.  But we are talking about a mythical "one infusate format to rule them all"  that covers the 3 points above, as well as 

4. researcher common parlance
5. lab communication
6. code interpretation

[_considering my past difficulties getting users to provide a standardized 2-word binomial nomenclature, never mind a parseable/formatted sentence describing a protocol_]

2022-06-08 13:35 UTC, jcmatese commented on DataRepo/tests/test_infusate_name_parser.py
> +        name = "short_name1 {lysine-[13C5]}"
For this parsing code, I am just matching the #400 proposal, for user-submitted treated animals.   See previous comment, regarding my thoughts.  If there is another proposed format using different characters/formatting that covers that use-case, and all the other possible use cases (input and output), we can discuss.

2022-06-08 13:38 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +KNOWN_ISOTOPES = "CNHOS"
Yes, this would be replaced with the new class in your other PR, which is not the base of this branch.  Suggest just making this an issue, which can be added during validation phase.

2022-06-08 13:45 UTC, jcmatese commented on DataRepo/utils/infusate_name_parser.py
> +    + r",\-]+)\])$"
Changes were made to get tests to pass.  I am unfamiliar with the original pattern, which Lance contributed.  I just tried to tweak it to address the issues that were reported.  If someone wants to re-write it more elegantly, despite it passing the proposed tests, have at it.  It is not my forté.

2022-06-08 18:28 UTC, hepcat72 commented
> I tested a few cases and they all worked. The `infusate_name` in output is a bit confusing since it's short name of an infusate(or the set of tracers). I think it's infusate.tracer_group_name in [PR442](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/442).

Yeah, the issue isn't that the patterns don't work.  They do.

2022-06-08 18:50 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +KNOWN_ISOTOPES = "CNHOS"
This is based off main.  If you're not at the current HEAD of main, you'll have the rebase before merge anyway.  Otherwise, that class simply exists under a different name and I'd say use it (`TracerLabeledClass`), but either way, that's moot after a rebase.

2022-06-08 18:53 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    + r",\-]+)\])$"
Yeah, I was thinking to do that and simply implement the code from my suggestions, which should work.  I'll see if I can knock that out by the end of the day.

2022-06-08 18:54 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +    + r",\-]+)\])$"
...as long as I'm not deluged by RT tickets...

2022-06-09 20:23 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +
`element` and `mass_number` are now separated. Validation will be done in a separate PR.

2022-06-09 20:38 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +    pass
I think we could include some standard error message to be appended to the specific error given when the exceptions are raised, but it's not necessary right now.

2022-06-09 20:42 UTC, lparsons commented
Since @hepcat72 submitted some changes to this, I believe all of the blocking issues have been addressed, so I'm going to merge this. Please create issues for any requested changes.

2022-06-09 20:42 UTC, merged