Updated enrichment_abundance and normalized_labeling (let's try this again)
Princeton-LSI-ResearchComputing/tracebase pull request #476
Opened 2022-07-24 00:56 UTC by hepcat72

## NOTE

I created another branch off of `peakgroup_format_multi` and merged the branch from PR #472 (closed) so that I could deal with the conflicts.  I still want to write tests for this branch, but I don't think that should prevent anyone from reviewing what's here now.  Also, I had made changes I'd intended for another branch/PR, after-which I found problems in the current branch/PR, so instead of teasing everything apart, I just committed those changes and the fix of the code in previous commits here.  Sorry for the mass of changes in one PR, but I think you should be able to follow it...

## Summary Change Description

Updated enrichment_abundance and normalized_labeling for multiple labels per tracer.  It does not handle multiple tracers (yet).

## Affected Issue Numbers

- Partially addresses #394
   - [x] PeakGroups:'Total Abundance'...
   - [x] PeakGroups:'Enrichment Fraction'...

## Code Review Notes

Same considerations as for the previous PR (whose branch this branches off of).  The more I think about these methods, the more I feel like (some of) these methods should be moved into `PeakGroupLabel`, because they're dependent on the labeled element.  I may more them in a future PR and change the return types back.

I put some comments inside `normalized_labelings` about multiple labels (which the changes in this PR support) and multiple tracers (not yet supported).  I'm not 100% certain yet about how to factor in multiple tracers.  There can be multiple serum peak groups (one for each tracer/compound), which means there are multiple enrichment fractions that can be computed for the serum sample.  When computing the normalized labeling for any random peak group/measured compound, what goes in the denominator?:  The sum of enrichment fractions from the latest serum sample's tracer compounds' peak groups?  The average?  The largest?

## Checklist

- [ ] All issue requirements satisfied (or no linked issues)
   - [x] PeakGroups:'Normalized Labeling'...
   - [x] PeakGroups:'Enrichment Abundance'...
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
   - I fixed existing tests
- [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_peak_data_1
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_peak_data_4
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_peak_data_serum
   - [x] DataRepo.tests.test_models.PropertyTests.test_enrichment_fraction_missing_compounds
   - [x] DataRepo.tests.test_models.PropertyTests.test_enrichment_fraction_missing_labeled_element
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_total_abundance_zero
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_common_labels
   - [x] DataRepo.tests.test_models.PropertyTests.test_peak_group_tracer_labeled_elements
   - [x] DataRepo.tests.test_models.PropertyTests.test_no_common_labels

2022-07-25 16:38 UTC, hepcat72 commented on CONTRIBUTING.md
> -    python manage.py load_animals_and_samples --animal-and-sample-table-filename DataRepo/example_data/small_dataset/small_obob_animal_and_sample_table.xlsx
C. I noted that adding this small datasets creates some invalid animals/duplicates, so I figured it doesn't belong in the contrib doc.

2022-07-25 16:44 UTC, hepcat72 commented on DataRepo/formats/dataformat.py
> +                )
C. I'm not actually sure this is right.  Is this the same as:
```
                  (
                      split_all
                      and self.model_instances[mdl_inst_nm]["manytomany"]["is"]
                  ) or (
                      self.model_instances[mdl_inst_nm]["manytomany"]["split_rows"]
                      and (
                          "distinct" not in self.model_instances[mdl_inst_nm].keys()
                          or self.model_instances[mdl_inst_nm]["distinct"] is False
                      )
                 )
```
...because that's what I intend. I don't think this is the same, but when I had those parens, VSCode underlined the parens in red and the linters said I needed a colon.  Do I have to add an outer set of parens?

2022-07-26 15:48 UTC, lparsons requested changes
I'm not able to follow the changes in the `Format` class very well, but the rest seems logical enough to me. I would be OK merging this once we are able to add some tests for calculations that use multiple tracers and multiple labels.

2022-07-26 15:48 UTC, lparsons commented on DataRepo/models/animal.py
> +                    tracer_labeled_elements.append(label.element)
C: I believe this will generate multiple queries and iterative over things in Python. An alternative would be to perform a single query, for example:
```python
list(TracerLabel.objects.filter(tracer__infusates__animal=self).order_by("element").distinct("element").values_list("element", flat=True))
```
or perhaps:
```python
set(TracerLabel.objects.filter(tracer__infusates__animal=a).values_list("element", flat=True))
```

2022-07-26 15:48 UTC, lparsons commented on DataRepo/models/animal.py
> +        """
NB: The method name implies this is only for Serum samples, suggest updating the doctring to reflect that.

2022-07-26 15:51 UTC, hepcat72 commented on DataRepo/models/animal.py
> +        """
Good catch.

- [ ] Update cod string in serum_tracers_enrichment_fractions which was copied from enrichment_fraction

2022-07-26 15:54 UTC, hepcat72 commented on DataRepo/models/animal.py
> +                    tracer_labeled_elements.append(label.element)
Oh yeah. Good observation/suggestion.

- [ ] Make a single DB query to get the common labels instead of nested for loops.

2022-07-26 15:55 UTC, hepcat72 commented on DataRepo/formats/dataformat.py
> +                )
I was poking at it during testing. I like the suggestion of using a method. I added comments to elucidate each section's goal.

- [ ] Make the conditional in getDistinctFields less opaque

2022-07-26 16:00 UTC, hepcat72 commented
> I'm not able to follow the changes in the `Format` class very well, but the rest seems logical enough to me. I would be OK merging this once we are able to add some tests for calculations that use multiple tracers and multiple labels.

I think readability is important. If you can point out specific sections in the format class that are difficult to follow, I'd like to improve their readability.

2022-07-26 19:21 UTC, hepcat72 commented
Review issues addressed. Tests added/fixed.  I added tags that I think would be very useful moving forward for the multiple tracer/label effort:

```
python manage.py test  --tag multi_fixed
```

And if you want to see what's broken:

```
python manage.py test  --tag multi_broken
```

...but I have only thus far applied these to the current branch's relevant test.

2022-07-26 20:01 UTC, jcmatese approved these changes
Just wanted to move this along, as it has been difficult to focus today and I don't want to hold this up.

2022-07-27 21:19 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        self.assertEqual(expected, output)
C. Somehow, I missed these TODOs in testing.  I must've forgotten to include this class in the list of tests I ran, but in my new branch to create tags for tracking multi-tracer/label updates, I encountered them and am filling those in in that branch.  Should have a PR ready soon.

2022-07-27 21:23 UTC, hepcat72 commented on DataRepo/models/peak_group.py
>          """
It's pseudocode - for simplification. There's no such class as `ThisPeakGroup` or `SerumTracerPeakGroup` either. Given this method will change in the move to a new PeakGroupLabel class, I'll just leave it for now.

2022-07-27 22:09 UTC, hepcat72 commented on DataRepo/models/animal.py
> +            # Count the total numnber of each element among all the tracer compounds
I'll fix this in another PR.

2022-07-27 22:10 UTC, hepcat72 commented on DataRepo/models/animal.py
> +            # Count the total numnber of each element among all the tracer compounds
Already did... so no checkbox.

2022-07-27 22:11 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> +                    )
This will go away when PeakGroupLabel is created, so I'll leave it for now, but that's a good suggestion.

2022-07-27 22:13 UTC, hepcat72 commented
Hey @jcmatese - not sure if you want to take a look since the changes yesterday (tests & review items), so I didn't re-request review. Up to you.

2022-07-28 12:46 UTC, jcmatese commented
> Hey @jcmatese - not sure if you want to take a look since the changes yesterday (tests & review items), so I didn't re-request review. Up to you.

Go ahead without me.  [I need to get this HTSEQ slurm PR staged/tested and moving along.]

2022-07-28 20:30 UTC, hepcat72 commented
I feel like you may have greenlit this somewhere, but I don't see it ATM, did you want to re-review this @lparsons?

2022-07-28 20:46 UTC, lparsons approved these changes
> I feel like you may have greenlit this somewhere, but I don't see it ATM, did you want to re-review this @lparsons?

I thought I did as well. The only thing I remember wanting to see was tests, which it seems you added.

2022-07-28 21:27 UTC, hepcat72 commented
Merged and pushed locally

2022-07-28 21:27 UTC, closed without merging