Fixed StudyTests and a bug relating to the new Animal.last_serum_sample field
Princeton-LSI-ResearchComputing/tracebase pull request #509
Opened 2022-09-14 20:28 UTC by hepcat72

## Summary Change Description

- The StudyTests tests were updated for the new loading format and schema.
- The Animal.last_serum_sample ForeignKey field had to have `db_column` specified to distinguish it from Sample's related foreign key.
- Also consolidated the get_researcher() code and created a method: parse_tracer_concentrations for re-use in tests.

## Affected Issue Numbers

- Resolves no issue

## Code Review Notes

Should be straightforward.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All *multi_working* tag tests pass locally](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*
  - [x] `@tag("multi_working")` added to newly passing test functions/classes *(or no newly passing tests)*
  - [x] `@tag("multi_broken")`, `@tag("multi_unknown")`, or `@tag("multi_mixed")` removed from newly passing test functions/classes *(or no newly passing tests)*

2022-09-14 21:50 UTC, lparsons requested changes
This looks like it fixes the issues. I did have a few questions asked inline.  One thing I think would be helpful would be to add some simple tests for the new `parse_tracer_concentrations` function.

2022-09-14 21:50 UTC, lparsons commented on DataRepo/models/researcher.py
> +        r for r in list(pd.unique(researchers)) if r is not None and r != ""
Q: I'm not understanding what this change does. Could you explain it? I'd just like to understand. Thanks.

2022-09-14 21:50 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +def parse_tracer_concentrations(tracer_concs_str: str) -> List[float]:
B: Adding some tests for this function would help to define how it works, esp on edge cases.

2022-09-14 21:50 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +            raise ae
Q: This is a bit confusing. Does the `if` cover the case where there is no comma and thus the split returns a single instance?

2022-09-15 17:31 UTC, hepcat72 commented on DataRepo/models/researcher.py
> +        r for r in list(pd.unique(researchers)) if r is not None and r != ""
`pd.unique(researchers)` turns None values into empty strings and while debugging the issue that prompted this PR, when I called this method in the shell, I was getting back:

`['Michael Neinast', 'Xianfeng Zeng', '']`

With my modification, it returned/returns:

`['Michael Neinast', 'Xianfeng Zeng']`

2022-09-15 17:34 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +def parse_tracer_concentrations(tracer_concs_str: str) -> List[float]:
The content of the function was simply copied/moved from `sample_table_loader.py` so I could call it from one of the tests, but I think a separate test would be a good thing to have, so:

- [ ] TODO: Add test for `parse_tracer_concentrations`

2022-09-15 17:37 UTC, hepcat72 commented on DataRepo/utils/infusate_name_parser.py
> +            raise ae
This was copied code, but if I recall correctly, this had to do with how excel (or the excel parser) returned a float if there was a single parsed delimited value in a cell versus a list of floats if there were multiple values.

There might be a better way of handling this by checking the type instead of allowing an exception to occur, but I'd argue that's outside of the scope of this PR (not that this PR doesn't already generously interpret what's in score, lol).

2022-09-15 17:38 UTC, hepcat72 commented on DataRepo/models/researcher.py
> +        r for r in list(pd.unique(researchers)) if r is not None and r != ""
Unfortunately, I cannot reproduce the behavior I'd observed before...

2022-09-15 17:58 UTC, lparsons commented on DataRepo/utils/infusate_name_parser.py
> +            raise ae
Sorry, I didn't recognize this was a copy/paste thing. Since it does seem to work, I'll agree it outside the scope.

2022-09-15 18:07 UTC, lparsons commented on DataRepo/models/researcher.py
> +        r for r in list(pd.unique(researchers)) if r is not None and r != ""
Thanks for explanation, that makes sense. I think using `filter` would work then, and might be a bit more readable.
```python
list(pd.unique(filter(None, researchers)))
```

2022-09-15 19:04 UTC, hepcat72 commented on DataRepo/models/researcher.py
> +        r for r in list(pd.unique(researchers)) if r is not None and r != ""
- [ ] TODO: Change list comprehension to filter

2022-09-15 19:25 UTC, hepcat72 commented on DataRepo/tests/models/test_animal.py
> +        self.assertEqual(1, ac)
Good catch.  This is a confusing misnomer.  The effect on "last_serum_sample" is indirect.  This specific query inside `DataRepo.models.researcher.Researcher.animals()` was throwing an exception about `Animal.last_serum_sample_id` not existing in the database.  The fix was to add `db_column` to the ForeignKey arguments.

- [ ] TODO: Make `test_last_serum_sample_queryable` easier to interpret

2022-09-15 19:33 UTC, hepcat72 commented on DataRepo/models/animal.py
>      )
[I disagree](https://stackoverflow.com/questions/1006917/are-circular-references-acceptable-in-database).  This design sets the appropriate constraints and represents unique data not captured by either link alone.  And this field exists in a place where is has a 1:1 relationship (Animal:Last_serum_sample).  Circular references are a problem when the foreign key is required, but that's not the case here.  Also, there are many instances where what you might consider "circular" references are used.  Such as a table with hierarchical records.  I think that this design is solid and correct and exists in the optimal place.  Can you demonstrate how these "circular" relations could cause a problem?

2022-09-15 20:42 UTC, fkang-pu commented on DataRepo/models/animal.py
>      )
I keep an open mind on this issue and like to have more discussions. I have a few arguments:
1. my preference is to avoid circular references since data loading process is more complex:
e.g. 
when inserting a new animal record, need to set `last_serum_sample` to null first as no sample records loaded yet; then insert a list of samples for this animal in Sample table, finally update "last_serum_sample" in Animal table after querying/comparing sample records for this animal.

2. an animal could have more than one last serum samples:
example:
https://tracebase.princeton.edu/DataRepo/animals/50/
https://tracebase.princeton.edu/DataRepo/samples/616/
https://tracebase.princeton.edu/DataRepo/samples/617/

3. The main question I asked myself is why we need to add this field? My understanding is it's required for calculating Fcirc values. To me it's more reasonable to keep it in Fcirc model, as the values in Fcirc table are derived from Animal, Sample, Infusate/Tracer and Peakgroup tables. Keep it in Fcirc table can also accommodate cases with multiple last serum samples. Otherwise the last serum sample would be cherry-picking if multiple serum samples meet the same criteria.

2022-09-16 22:49 UTC, hepcat72 commented on DataRepo/models/animal.py
>      )
Created #515

2022-09-16 22:56 UTC, hepcat72 commented
Review items implemented in #510

2022-09-16 22:57 UTC, merged