Added protocol load class, command, tests, and initial usage
Princeton-LSI-ResearchComputing/tracebase pull request #538
Opened 2022-10-05 16:05 UTC by jcmatese

## Summary Change Description

Added ProtocolLoader utility class, primarily for loading Animal Treatments defined in the animal and sample template file.
Logic is similar to Tissue Loader, but does not use a separate command, but rather was integrated into the existing animal/sample loading command.
I left off the multi_working tag, because I did not think it was currently relevant, but let me know if it is required.

## Affected Issue Numbers

- Resolves #523

## Code Review Notes

- Uncertain what would happen if the template is munged, missing that sheet, lacks any rows, etc.
- It uses the similar pattern as tissue loading, which has an additional layer/database for validation, which I don't really know if strictly necessary or advisable.
- Also copies some "space"/"tab" conditional logic for the name that the tissues loader was using, that I don't really understand the basis of, but I left it in case it was potentially important.
- Because of the way protocols/treatments are loaded, first-come/first serve preferentially, you might have to re-order the loading of studies to get the "right" protocol description loaded first.  Either that, or edit all the data files.

There are probably 2 ways to test this:

~~1. `./manage.py load_animals_and_samples --animal-and-sample-table-filename tracebase-rabinowitz-data/serine-glycine-free-glucose-infusion/animals_samples_treatments.xlsx --skip-researcher-check` or any animal and sample xlsx that contains a Treatments worksheet~~ as of [c420e0a](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/538/commits/c420e0ab20b1cad9c79ba45242999f7ed5fb1a18) , that functionality was reverted
2. `python manage.py load_study STUDY_LOADING.YAML` , where STUDY_LOADING.YAML contains a protocols key with a value of a file path to an animal and sample xlsx that contains a Treatments worksheet or a generic TSV-file containing protocols (name, category, description)
3. `python manage.py load_protocols --protocols=FILE` , or where file is a animal and sample xlsx that contains a Treatments worksheet or a generic TSV-file containing protocols (name, category, description)

### Outstanding Issues
**NOTE**: an executive decision probably needs to be made regarding the following code (keep or discard this historical functionality/assumptions of auto-insertion of name-only animal treatments)
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/def86001ba1358bdb2c3bdd21806f3012730a50f/DataRepo/utils/sample_table_loader.py#L305-L327
UPDATE: It was decided to remove that logic.  Protocols must already be in the database, before loading animals/samples.

**FURTHER**: an executive decision _probably_ needs to be made on the mechanism of **_updating_** the auto-generated descriptions of treatments (historically produced by the aforementioned code), either by the command script (with an additional/optional argument), or if the plan is to always drop the database and re-load with new data (including a pre-load of "fixed" `protocols.tsv` [same name, updated description]).
UPDATE: It was decided to not update protocol's description, after the fact. (via this code, anyway)

**TESTING META**:
**_I could use some assistance with getting some validation/view tests to pass_**
```
./manage.py test --tag=protocol_loading_broken
----------------------------------------------------------------------
Ran 9 tests in 24.332s
FAILED (errors=1)
./manage.py test --exclude-tag=protocol_loading_broken --tag=multi_working
----------------------------------------------------------------------
Ran 316 tests in 2699.428s
OK
```
I think it might be somehow failing on a couple missing "blank" samples, but I have not found the source file, or reason (yet).

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All *multi_working* tag tests pass locally](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [ ] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*
  - [x] `@tag("multi_working")` added to newly passing test functions/classes *(or no newly passing tests)*
  - [ ] `@tag("multi_broken")`, `@tag("multi_unknown")`, or `@tag("multi_mixed")` removed from newly passing test functions/classes *(or no newly passing tests)*

2022-10-05 16:23 UTC, jcmatese commented on DataRepo/tests/loading/test_loading_protocols.py
> +        """Test the ProtocolsLoader with dataframe missing category"""
```suggestion
        """Test the ProtocolsLoader with an improper category"""
```

2022-10-05 16:56 UTC, jcmatese commented
I think [this error](https://github.com/Princeton-LSI-ResearchComputing/tracebase/actions/runs/3191103687/jobs/5207012848#step:4:10877) was addressed in another PR, and was not added in this PR.

2022-10-07 17:09 UTC, hepcat72 commented
Is this still in draft? I was just about to review and noticed the draft label.

2022-10-07 17:25 UTC, jcmatese commented
I don't have strong feeling about it.  I think it is fine to looks at review/comment on/ find protocols texts, etc.

2022-10-19 18:09 UTC, jcmatese commented
Primarily checked in, incase I need to pull it to him over the next couple days (or if someone want to take a look at it)

2022-10-19 18:11 UTC, jcmatese commented
BTW, the "test dependencies" are a result of the "no longer automatically insert animal treatments" issue tweak

2022-10-25 17:37 UTC, jcmatese commented
Still trying to find this last test's failure solution, but people can start reviewing

2022-10-25 20:06 UTC, lparsons requested changes
Nice job implementing a change that touched quite a bit of code. The loader is nicely written and appears to work well for our purposes. I like the flexibility of inputs.

I had a few questions I put inline, and I noticed a few small things that I think we should address, but overall, this looks great.

2022-10-25 20:06 UTC, lparsons commented on DataRepo/tests/models/test_infusate.py
> +            verbosity=2,
Q: Do we want this level of verbosity baked into the test?

2022-10-25 20:16 UTC, jcmatese commented on DataRepo/tests/models/test_infusate.py
> +            verbosity=2,
I have no strong opinion, other than to reduce the overall verbosity given how much time I have had trying to sorting through test output in the past couple weeks.  I probably copy pasted that pattern from somewhere else, assuming in was preferred.  I probably grabbed it from `test_loading_tissues.py`, since that is what this was patterned on, at the beginning.
```
$ grep -r "verbosity=2" DataRepo/tests/*
DataRepo/tests/loading/test_loading_tissues.py:                verbosity=2,
DataRepo/tests/models/test_infusate.py:            verbosity=2,
DataRepo/tests/models/test_infusate.py:            verbosity=2,
DataRepo/tests/models/test_infusate.py:            verbosity=2,
DataRepo/tests/models/test_infusate.py:            verbosity=2,
DataRepo/tests/test_formats.py:            verbosity=2,
DataRepo/tests/test_models.py:            verbosity=2,
DataRepo/tests/test_models.py:            verbosity=2,
DataRepo/tests/test_models.py:            verbosity=2,
DataRepo/tests/test_models.py:            verbosity=2,
DataRepo/tests/test_models.py:            verbosity=2,
```

2022-10-25 20:20 UTC, lparsons commented on DataRepo/tests/models/test_infusate.py
> +            verbosity=2,
I would agree with you John, I think the overall verbosity of the tests is excessive. I'd vote for not including the verbosity flag in these new tests.

2022-10-25 20:21 UTC, jcmatese commented on DataRepo/example_data/AsaelR_13C-Valine+PI3Ki_flank-KPC_2021-12_isocorr_CN-corrected/loading.yaml
> +protocols: "../protocols/protocols.tsv"
I don't have a strong opinion, but I probably patterned it on the urge to "handle it like tissues", and followed previous use/example.
```
grep -Ir "tissues/loading.yaml" DataRepo/tests/*
DataRepo/tests/loading/test_loading_compounds.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/loading/test_loading_compounds.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/loading/test_loading_compounds.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/models/test_sample.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/models/test_fcirc.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/models/test_infusate.py:            "DataRepo/example_data/tissues/loading.yaml",
DataRepo/tests/models/test_hier_cached_model.py:    call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/models/test_animal.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_customtags.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_formats.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_models.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_models.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_models.py:            "DataRepo/example_data/tissues/loading.yaml",
DataRepo/tests/test_models.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_models.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_views.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_views.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
DataRepo/tests/test_views.py:        call_command("load_study", "DataRepo/example_data/tissues/loading.yaml")
```

2022-10-25 20:23 UTC, jcmatese commented on DataRepo/example_data/AsaelR_13C-Valine+PI3Ki_flank-KPC_2021-12_isocorr_CN-corrected/loading.yaml
> +protocols: "../protocols/protocols.tsv"
Oh, sorry, you are saying you don't want the "comprehensive list" to make a specific test/file work.  I could probably change it, if people want.  I think initially, I was hoping to have 1 example of "load comprehensive protocols to make all these tests work", but that did not really pan out, in the big scheme of things.

2022-10-25 20:32 UTC, jcmatese commented on DataRepo/management/commands/load_protocols.py
> +                str(self.description_header): "description",
ProtocolLoader is currently expecting a "standardized" data frame to be passed into it.  If you want name, category and description exported, I suppose we can do that, but at a certain point, I feel like I am replacing the string `"name"` with the variable `ProtocolLoader.NAME_HEADER`,   which almost obfuscates it .  Unless you are suggesting that ProtocolLoader doesn't expect a standardized data to be passed int, but rather inspects the data frame headers and does its own re-mapping/naming.

2022-10-25 20:33 UTC, jcmatese commented on DataRepo/management/commands/load_protocols.py
> +        if verbosity >= 2:
I can't take credit.  All of this was a prior pattern from load_tissues...

2022-10-25 20:38 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                    raise ValidationDatabaseSetupError()
I don't know.  Logic/pattern was mimicked on tissues, so presumed it was wanted.
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/45f21c17a7e00cf60db820be188e405e992d04cf/DataRepo/utils/tissues_loader.py#L37-L46

2022-10-25 20:43 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                        category = None
Sure I can try that.  I left all that in there, because I assumed it was important to functionality (from tissues)

$ grep -Ir "if str(name) == \"nan\":" DataRepo/*
DataRepo/utils/tissues_loader.py:                    if str(name) == "nan":
DataRepo/utils/protocols_loader.py:                    if str(name) == "nan":

2022-10-25 20:43 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                        description = description.strip()
Sure, I can try that.

2022-10-25 20:45 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                    # To aid in debugging the case where an editor entered spaces instead of a tab...
All of that is very strange, and I don't understand the issue fully, but someone thought it was important for tissues input, so I left it for protocols input. https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/45f21c17a7e00cf60db820be188e405e992d04cf/DataRepo/utils/tissues_loader.py#L76-L81

2022-10-25 20:51 UTC, lparsons commented on DataRepo/management/commands/load_protocols.py
> +                str(self.description_header): "description",
I'm suggesting that both locations use the same variable `ProcolLoader.NAME_HEADER`, instead of relying on the fact that this code has `"name"` and ProtocolLoader also has `"name"`.

2022-10-25 20:51 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
I think we have already had some discussion about whether we can have a truly comprehensive list of protocols, and whether the validation database is even to have permanently resident protocols (I don't think existing code expects them to be there).  Again, this was patterns after the existing tissues loader, but perhaps it should not have followed the logic exactly?  [this issue and my thoughts on handling it changed over the intervening weeks, but this was _probably_ the initial check-in]
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/45f21c17a7e00cf60db820be188e405e992d04cf/DataRepo/utils/tissues_loader.py#L84-L85

2022-10-25 20:52 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                            self.created[db] = [protocol]
I think this must have been Rob's addition, when adding the validation database.  I assumed it was the correct pattern, from tissues loader.

2022-10-25 20:53 UTC, hepcat72 commented
FYI, I'm starting a review of this PR.

2022-10-25 20:55 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                self.load_database(settings.VALIDATION_DB)
That depends. If the change I suggested above was made, then we know that `settings.VALIDATION_DB` is set, and there is no issue. In the other cases, I don't know if there is a check on whether it is set or not. We don't need to fix all other areas now (can just be an issue to check). However, I do think that we should ensure this new code works as intended and checks instances where we should throw `ValidationDatabaseSetupError`.

2022-10-25 20:58 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                    # To aid in debugging the case where an editor entered spaces instead of a tab...
If we don't know why this is here or have a good justification for it, I'd would say we remove it. To me it seems like the loader should not be concerned with how the dataframe was formed, but simply take it as is. The management command is the part of the code that parses the files, and thus, should be where the checks for file types, etc. are handled. At least, imo.

2022-10-25 20:59 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
I'm fine with the assumption of up to date protocols in the validation database. I'm not fine with skipping the `full_clean` when validating since that seems to defeat the purpose of validation.

2022-10-25 23:18 UTC, hepcat72 requested changes
I'm a bit concerned about how we're handling treatments here, but it depends on whether we expect to frequently get novel treatments.  Does the sample table load take the treatment name as-is, or does it match the value in the treatments tab (with the description) with what's in the database?  I'm not sure what the likelihood is that treatment names will be mismatched to treatments with the same name but a value already existing in the database and a different value in the excel sheet.

If this separate loader runs on the same sample file and loads the new treatments, this should be incorporated into the validation view logic.  It can still work without it, but it would report exceptions about missing protocols that are defined in the submission.

I'm still ruminating over what might need to be done.  I did have a few blocking issues, but if I'm off on any of them, let me know and we can hash it out.

2022-10-25 23:18 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                    # To aid in debugging the case where an editor entered spaces instead of a tab...
This was all hashed out during the PR code review where this code was introduced (WRT tissues, I think).  This was code to catch and handle a confusing case where a paste into an editor resulted in a tab character being converted into spaces.  The name of the record was `whatever    ` and there was no error.  It just silently loaded the weird name with multiple spaces and no description, and when I was trying to write a test where I was reaching for `whatever`, I was getting nothing, which confounded me.  So I came up with this solution.  We could of course be more strict and require exactly 2 columns, but I think there were already tested cases with an intentional single column and I didn't want to step on that.  And since all the tissues had underscores instead of spaces, I just went with this logic that used that to catch this issue automatically and save time/effort in maintenance phase.

2022-10-25 23:18 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
There is no validation going on here.  It's just a load of the validation database so that the sample and *corr files can be validated.  And as to the restrictions regarding what databases full_clean can run on, that's up to the django developers (unless my analysis of why full_clean threw exceptions was inaccurate).  Regardless, the purpose here is to support user-validation of other files, not protocol files.

2022-10-25 23:18 UTC, hepcat72 commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
Including the name is useful IMO.  It's probably this exception that put me onto the tab conversion to spaces.

2022-10-26 12:52 UTC, jcmatese commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
The reason I did it this way is because it gives a sensible/comprehensive message, without the recursive "Protocol.DoesNotExist from/while-handling Protocol.DoesNotExist" in the log.  It looks a _little_ weird in the code, but it looks _much_ better in the output (my opinion)

2022-10-26 12:57 UTC, jcmatese commented on DataRepo/example_data/protocols/protocols.tsv
> +"LC-MS, positive ion mode"	msrun_protocol	"For protocol's full text, please consult Michael Neinast."
Presumably Excel  (or whatever spreadsheet client I used in-between) , thinks that any string value with non-alphanumeric characters (single-quote, comma, etc.) should be quoted upon export?

2022-10-26 13:05 UTC, jcmatese commented on DataRepo/example_data/protocols/T3_protocol.tsv
> +vehicle	animal_treatment	"For protocol's full text, please consult Michael Neinast."
We are using pandas to import this file, So I think it would _probably_ handle it alright, if probably formatted to spec?

2022-10-26 13:44 UTC, jcmatese commented on DataRepo/tests/test_views.py
> +
If you like, I can just remove it altogether.  I was just appending to the previous patterns for compounds and tissues, immediately before in the same file:
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/7e15d52e2759bbba7ad35a0c6faa3ce7ad07ee3d/DataRepo/tests/test_views.py#L727-L753

2022-10-26 13:58 UTC, lparsons commented on DataRepo/example_data/protocols/protocols.tsv
> +"LC-MS, positive ion mode"	msrun_protocol	"For protocol's full text, please consult Michael Neinast."
I think that is a fairly standard thing, though usually for CSV files.

2022-10-26 13:59 UTC, lparsons commented on DataRepo/example_data/protocols/protocols.tsv
> +control_vehicle_for T3 in drinking water	animal_treatment	"For protocol's full text, please consult Michael Neinast."
It would be reasonable if the protocol data is unchanged in this PR, with the exception of the descriptions which we have ignored up until now.

2022-10-26 14:00 UTC, lparsons commented on DataRepo/example_data/protocols/T3_protocol.tsv
> +vehicle	animal_treatment	"For protocol's full text, please consult Michael Neinast."
We should not be committing code and data that we aren't sure works. Be sure this is tested somewhere (I think it is).

2022-10-26 14:09 UTC, jcmatese commented on DataRepo/example_data/protocols/T3_protocol.tsv
> +vehicle	animal_treatment	"For protocol's full text, please consult Michael Neinast."
The file is loaded here
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/7e15d52e2759bbba7ad35a0c6faa3ce7ad07ee3d/DataRepo/tests/test_models.py#L320-L323
and pre-existing value-test, here
https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/7e15d52e2759bbba7ad35a0c6faa3ce7ad07ee3d/DataRepo/tests/test_models.py#L478-L486
but there is not an **_additional/specific_** test to verify that quotation marks are not parsed/loaded, but I believe the above suffices?

2022-10-26 14:49 UTC, lparsons commented on DataRepo/example_data/protocols/T3_protocol.tsv
> +vehicle	animal_treatment	"For protocol's full text, please consult Michael Neinast."
Thanks for checking John. I don't think additional tests are required, but if the file is loaded and values tested that sounds great. I was a bit concerned when you said it "probably" worked, but this seems to show that it does work.

2022-10-26 15:49 UTC, hepcat72 commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
IMHO, the standard exception string could be better.  Including the name is useful.  Though I'm agnostic WRT `from None`.  Depends on the accuracy of the catch, though if this eliminates the trace (not sure) and the resolution relates to the caller(s), then I'd be opposed.

2022-10-26 15:50 UTC, hepcat72 commented on DataRepo/example_data/protocols/protocols.tsv
> +control_vehicle_for T3 in drinking water	animal_treatment	"For protocol's full text, please consult Michael Neinast."
Is there an issue for this?

2022-10-26 16:08 UTC, hepcat72 commented on DataRepo/tests/test_views.py
> +
Yeah, we should probably (if we don't already) make the name and description unique (for both tissues and protocols(/treatments)), and when processing the sample (excel) file, be checking if there's a difference in the tissues and treatments tab WRT what's in the database.  Whether it *loads* those things is a separate question, but it seems like a reasonable check during processing would be:

1. If the Sample sheet references a tissue name that's not in the DB, make sure it exists on the tissues tab
2. Else if it *is* in the database, make sure the description on the tissues tab matches the database
3. Same (steps 1 & 2) thing for treatments on the animals tab

Until that's implemented, any existing errors relating to these issues would be presented to the user on the validation page, but only as they arise from sample table loader, and that's as designed.  Any errors arising from the protocols loader would be something *we* would see in our loads on the command line.

I agree, this is something we can hash out in a meeting, but regardless, this code should be in `initialize_databases`.  I would advise the code be moved there and we address those exceptions in this PR.  If I can have a look at them, there's a good chance I can tell what the issue is.

2022-10-26 16:09 UTC, jcmatese commented on DataRepo/management/commands/load_protocols.py
> +            loader_args["category"] = self.batch_category
I may have to look more into this.  I don't think I have ever `__init__()` too much before, and I can't remember using it before in a `Command(BaseCommand)`

2022-10-26 16:11 UTC, hepcat72 commented on DataRepo/tests/test_views.py
> +
No, you're right.  I suspect I either missed a file header while scrolling though, or just was in the wrong headspace. Resolving.

2022-10-26 16:13 UTC, jcmatese commented on DataRepo/management/commands/load_protocols.py
> +                format,
Thanks, I think this probably needed fixing.

2022-10-26 16:17 UTC, hepcat72 commented on DataRepo/example_data/protocols/protocols.tsv
> +control_vehicle_for T3 in drinking water	animal_treatment	"For protocol's full text, please consult Michael Neinast."
I incorrectly inferred that "with the exception of the descriptions which we have ignored up until now" was a reference to the mixed use of underscores and spaces and that "descriptions" was a typo.  Regardless, my question is to whether we have an issue regarding the mixed underscores/spaces in the protocol names.

2022-10-26 16:18 UTC, jcmatese commented on DataRepo/utils/protocols_loader.py
> +                        category = category.strip()
thanks, will try

2022-10-26 16:21 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
Since users will be submitting protocols along with animals and samples, we should validate those as well, but I'm ok if we push the updates to validation off to other PRs.

2022-10-26 16:49 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
I agree.  And we could create an issue that handles it in 1 or 2 ways.  Either [the sample table loader could make a treatments-tab-aware check](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/538#discussion_r1005885013) so that no change to the validation code is necessary, or the the validation view can run the protocol loader on the submitted sample excel file before running the sample loader code, using the same design pattern of running the sample table loader before the accucor loader.  I'll reference this in a new issue.

2022-10-26 16:51 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
... or we might even be able to run an entire load_study call, if we have everything we need, though that could be more involved if, like other loading code, an exception stops processing, making subsequent commands unable to run.

2022-10-26 17:02 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
I agree that this has been discussed multiple times. There is no need to change directions at this point. We will load protocols separately from samples (as Rob said, same pattern as the sample table and accucor loaders). Let's get this code working as best we can so we can merge this week. Making the necessary updates to validation code seem to be holding things up at the moment, so that is why I suggested we push that off to a separate effort.

2022-10-26 17:23 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                        # full_clean cannot validate (e.g. uniqueness) using a non-default database
To be clear, there should be nothing in this PR that breaks the validation view.  This issue is just a question as to how to handle protocol errors that arise from that view as a result of this (or other) changes.  This particular line of code is a non-issue IMO.  However, there is code elsewhere in this PR that appears that it would break the validation view and I think it can likely be easily fixed before merging.  See my blocking issue(s).

2022-10-26 17:27 UTC, jcmatese commented on DataRepo/tests/models/test_infusate.py
> +            "DataRepo/example_data/protocols/loading.yaml",
Right, at the developer meeting it was decided that they need to be "pre-loaded", like tissues.  Thus, this call to a "comprehensive" test set of protocols.  Later, I added the ability of load_protocols to work with the multi sheet xlsx .  If you were absolutely certain of the protocol name re-use within the sheets of `DataRepo/example_data/small_dataset/small_obob_animal_and_sample_table.xlsx` , you could alternatively use call_command("load_protocols", protocols="DataRepo/example_data/small_dataset/small_obob_animal_and_sample_table.xlsx").  However, in this _particular_ case , I think its inclusion/loading _might_ be in error, because I don't see any sample loaded in that class.  I will try removing it, and see if it breaks anything.

2022-10-26 17:36 UTC, jcmatese commented on DataRepo/tests/test_views.py
> +
ok, I will move it back there, and re-introduce this test failure
```
======================================================================
FAIL: test_databases_unchanged (DataRepo.tests.test_views.ValidationViewTests)
Test to ensure that validating user submitted data does not change either database
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/DataRepo/tests/test_views.py", line 725, in test_databases_unchanged
    self.assertListEqual(vd_init_counts, vd_post_counts)
AssertionError: Lists differ: [51, 104, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0] != [51, 104, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

First differing element 17:
2
0

- [51, 104, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0]
?                                                         ^

+ [51, 104, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
?                                                         ^
```

2022-10-26 17:56 UTC, hepcat72 commented on DataRepo/tests/models/test_infusate.py
> +            "DataRepo/example_data/protocols/loading.yaml",
Well, it doesn't hurt, but I suspect you're right that it's not necessary in this case - mainly because the records in the tests are manually created instead of loaded.  In fact, the full compound and tissue loads are probably overkill.  I'd have to look close to be sure.

2022-10-26 18:04 UTC, hepcat72 commented on DataRepo/tests/test_views.py
> +
That error would be because you supplied the validation database to the --database option.  Remove that option and it should pass, because it should be loading into both.

2022-10-26 18:32 UTC, jcmatese commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
Just some background, because I originally tried the `as e `; current output (my preference):

`as None` output

```
======================================================================
ERROR: setUpClass (DataRepo.tests.test_models.IsoCorrDataLoadingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/Users/jcmatese/dev/tracebase/DataRepo/tests/test_models.py", line 1918, in setUpTestData
    call_command(
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/jcmatese/dev/tracebase/DataRepo/management/commands/load_animals_and_samples.py", line 134, in handle
    loader.load_sample_table(
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils/sample_table_loader.py", line 325, in load_sample_table
    raise Protocol.DoesNotExist(
DataRepo.models.protocol.Protocol.DoesNotExist: Could not find 'animal_treatment' protocol with name 'carboxymethylcellulose'

----------------------------------------------------------------------
```

`as e` output

```
======================================================================
ERROR: setUpClass (DataRepo.tests.test_models.IsoCorrDataLoadingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils/sample_table_loader.py", line 310, in load_sample_table
    treatment = Protocol.objects.using(self.db).get(
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
DataRepo.models.protocol.Protocol.DoesNotExist: Protocol matching query does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/Users/jcmatese/dev/tracebase/DataRepo/tests/test_models.py", line 1918, in setUpTestData
    call_command(
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/jcmatese/dev/tracebase/DataRepo/management/commands/load_animals_and_samples.py", line 134, in handle
    loader.load_sample_table(
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils/sample_table_loader.py", line 325, in load_sample_table
    raise Protocol.DoesNotExist(
DataRepo.models.protocol.Protocol.DoesNotExist: Could not find 'animal_treatment' protocol with name 'carboxymethylcellulose'

----------------------------------------------------------------------
Ran 0 tests in 5.246s

```

2022-10-26 18:37 UTC, lparsons commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
The reason I'd argue for the second version is that it actually refers to the line in the code that *caused* the error: [`sample_table_loader.py, line 310`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/538/files#diff-f4833d4f4ac4431461a2b911f4d6f59e796dae8a59dfbb9c191f004053bcf6d7R310-R312).

2022-10-26 18:40 UTC, jcmatese commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
and I think if you use `as e`, without a future reference to it, it runs afoul of our suite of linters

2022-10-26 18:51 UTC, jcmatese commented on DataRepo/utils/sample_table_loader.py
> +                            ) from None
How about `.with_traceback(e.__traceback__) from None` output, which might get the line number and may escape linters?

```
======================================================================
ERROR: setUpClass (DataRepo.tests.test_models.IsoCorrDataLoadingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/test/testcases.py", line 1201, in setUpClass
    cls.setUpTestData()
  File "/Users/jcmatese/dev/tracebase/DataRepo/tests/test_models.py", line 1918, in setUpTestData
    call_command(
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/jcmatese/dev/tracebase/DataRepo/management/commands/load_animals_and_samples.py", line 134, in handle
    loader.load_sample_table(
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils/sample_table_loader.py", line 325, in load_sample_table
    raise Protocol.DoesNotExist(
  File "/Users/jcmatese/dev/tracebase/DataRepo/utils/sample_table_loader.py", line 310, in load_sample_table
    treatment = Protocol.objects.using(self.db).get(
  File "/Users/jcmatese/dev/tracebase/.venv/lib/python3.9/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
DataRepo.models.protocol.Protocol.DoesNotExist: Could not find 'animal_treatment' protocol with name 'carboxymethylcellulose'

----------------------------------------------------------------------
```

2022-10-26 19:20 UTC, jcmatese commented on DataRepo/tests/models/test_infusate.py
> +            verbosity=2,
ended up removing this call, because I think the protocols are now loaded in the individual studies (a feature added later)

2022-10-26 20:30 UTC, jcmatese commented
I think this is ready to review again, if there is anything that is still blocking.  The Validation tests are the primary stopper, for me, but  perhaps Rob might be better suited to take it from here, with regards to that code.

2022-10-26 20:51 UTC, lparsons commented on DataRepo/management/commands/load_protocols.py
> +            self.new_protocols_df[col].str.strip()
This looks good, is there some data in the tests that includes "nan" and extra white space? I think there might be, but if not we should add some.

2022-10-26 20:51 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                    # To aid in debugging the case where an editor entered spaces instead of a tab...
I'm a bit bothered by the validation being so deep in the loader code. Since it's used in at least two places, it seems like we might want a standard "data cleaner and validator" for input files?

It also enforces an odd rule (name cannot contain spaces unless there is a description) that seems mostly a side effect of the check, not a real rule we want to enforce. There seems to be some potential for this to cause some issues down the line. 

However, I think it's unlikely either situation will come up since we strip leading and trailing white space now and most data will likely include descriptions. Since it's already here, I'm OK leaving it.

2022-10-26 20:51 UTC, lparsons commented on DataRepo/utils/protocols_loader.py
> +                            self.created[db] = [protocol]
I believe you are correct Rob, I was just noting that if we initialized `self.created` with keys and empty lists we wouldn't need this sort of code here. I didn't know if the initialization was also part of this PR.

2022-10-26 20:54 UTC, lparsons commented on DataRepo/example_data/protocols/protocols.tsv
> +control_vehicle_for T3 in drinking water	animal_treatment	"For protocol's full text, please consult Michael Neinast."
As long as they match the values in the Animal tables, then I think we can leave them until we go through and do a "cleanup" of the example and test data.

2022-10-26 20:58 UTC, lparsons requested changes
The changes looks great John, I think you have addressed all of my concerns with a couple of items left to do:
1. Fix the code so the tests pass (or modify the tests if that is required)
2. Identify the remaining tasks to ensure that the validation web interface reads the treatments in the same way we would when loading new study data. Create an issue for this.

2022-10-26 21:07 UTC, hepcat72 requested changes
The only blocking issue is the presence of the `--database` option in the `initialize_databases method in the `view_tests`.  As I mentioned in the first review, if that's removed, I expect it will allow the tests to pass.  If it doesn't, I'd be happy to submit a patch, but I'm pretty sure if you just mimic the tissue and compound loads, it will pass.

2022-10-26 21:14 UTC, hepcat72 commented on DataRepo/utils/protocols_loader.py
> +                    # To aid in debugging the case where an editor entered spaces instead of a tab...
That's fair.  I didn't like this solution either TBH.  I was just trying not to break other cases.  I believe I wrote tests for this code WRT tissues (where it recreates the conditions that wasted my time debugging), so if the latest version of the code solves this problem, we can remove it and if it passes the tests, merge the edit.

2022-10-26 22:07 UTC, hepcat72 commented
Removed the incorrect usage of the --database flag, then found that the protocols file being used in the database setup was missing the default msrun protocol that is generated in the accucor load used in the test.  Tests passed locally.  I expect they'll pass on GH as well... Logging off.

2022-10-27 20:47 UTC, hepcat72 approved these changes
With my merged patch, I no longer have any blocking issues.

2022-10-27 20:51 UTC, hepcat72 commented
@lparsons - I altered my review.  I didn't check if all my non-blocking issues were addressed and choose just to go with John's decision.  I see though that with today's merges, there is a conflict.  I'll take a look and see if I can resolve them.  If I can, I'll push an update.  John's off today.

I think that my changes address your concerns as well, but I'll request your review, in case you want to have a look.

2022-10-27 20:58 UTC, hepcat72 commented
The only conflict appears to have been the removal of protocol view tests.  I think I got that right.  I accepted the change where these were deleted in main:

```
<<<<<<< HEAD
    def test_protocol_list(self):
        response = self.client.get(reverse("protocol_list"))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "DataRepo/protocol_list.html")
        self.assertEqual(
            len(response.context["protocol_list"]), self.ALL_PROTOCOLS_COUNT
        )

    def test_protocol_detail(self):
        p1 = Protocol.objects.filter(name="Default").get()
        response = self.client.get(reverse("protocol_detail", args=[p1.id]))
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "DataRepo/protocol_detail.html")
        self.assertEqual(response.context["protocol"].name, "Default")

    def test_protocol_detail_404(self):
        p = Protocol.objects.order_by("id").last()
        response = self.client.get(reverse("protocol_detail", args=[p.id + 1]))
        self.assertEqual(response.status_code, 404)

=======
>>>>>>> main
```

Is that right, or did I get it backwards?

2022-10-27 21:08 UTC, hepcat72 commented
Well, it seems the merge didn't really work.  There's a linting error about `Protocol` not being defined.  Might have th un-merge and wait for John to resolve it.

2022-10-27 22:54 UTC, lparsons commented
Turns out there is a bit more work to do get this branch working with existing `main` (it's been branched for about three weeks). I've put my initial attempt in the `treatments-loading-merge` branch. Will create a PR to merge that into this branch and include a list of issues to resolve.

2022-10-28 15:53 UTC, lparsons commented
@jcmatese: @hepcat72 was able to implement his suggestions to fix the test code and I have resolved the conflicts with `main`. Ball is back in your court... 🏀

2022-10-28 16:40 UTC, lparsons commented
> Should I merge this then? Is there anything that is a mission critical blocker?

Looking back at the reviews, I see three blocking issues:

1. "... the presence of the --database option in the initialize_databases method in the view_tests" - @hepcat72
2. Fix the code so the tests pass (or modify the tests if that is required) - @lparsons 
3. Identify the remaining tasks to ensure that the validation web interface reads the treatments in the same way we would when loading new study data. Create an issue for this. - @lparsons 

I believe that 1 and 2 have been resolved, so once we have the tasks to fix the validation interface identified in an issue, I think we're ready to merge.

2022-10-28 16:46 UTC, jcmatese commented
> I believe that 1 and 2 have been resolved, so once we have the tasks to fix the validation interface identified in an issue, I think we're ready to merge.


I think those were all taken care of? [ [placeholder issue](https://github.com/Princeton-LSI-ResearchComputing/tracebase/issues/577) ]

2022-10-28 16:49 UTC, lparsons commented
#577 seems a bit light on details, but if that is sufficient for you, I'm good with us merging this PR and getting started on that issue.

2022-10-28 16:51 UTC, lparsons approved these changes
I believe the blocking issues have been taken care of. Note that merging this will mean we should start work on #577 in order to keep a functional validation page.

2022-10-28 16:52 UTC, hepcat72 commented
> > Should I merge this then? Is there anything that is a mission critical blocker?
> 
> Looking back at the reviews, I see three blocking issues:
> 
> 1. "... the presence of the --database option in the initialize_databases method in the view_tests" - @hepcat72
> 2. Fix the code so the tests pass (or modify the tests if that is required) - @lparsons
> 3. Identify the remaining tasks to ensure that the validation web interface reads the treatments in the same way we would when loading new study data. Create an issue for this. - @lparsons
> 
> I believe that 1 and 2 have been resolved, so once we have the tasks to fix the validation interface identified in an issue, I think we're ready to merge.

If I understand item 3 correctly, it nearly does, but as I think about it, from implementing my suggestions yesterday, the way it's now handled leaves side-effects.  In fact, it might have been wrong"ish" to add protocols the same way tissues and compounds are handled.  The sample-table loader gets/creates treatment protocols and the accucor loader gets/creates msrun protocols (though all I see is the default).  Maintaining protocols in this way *does* allow us to catch discrepancies (if in fact the loading code checks it - I did not verify this), but I *think* each validation leaves its additions in the validation database (which I don't think happens with tissues/compounds) so that the next test will be checked against what was added in the previous check.  That's not good.

If to rectify that, we don't pre-load protocols, then we don't get the benefit of checking against existing records...  Perhaps there's a middle-ground, where each test is preceded by a copy from the default DB to the validation DB (or a load of a comprehensive protocols file)?

2022-10-28 16:59 UTC, lparsons commented
I would prefer we have the issues worked out before we merge this. I'm open for a discussion after 2 PM today or we can talk on Monday.

2022-10-28 17:29 UTC, hepcat72 commented
> #577 seems a bit light on details, but if that is sufficient for you, I'm good with us merging this PR and getting started on that issue.

Yeah, I have not fleshed it out yet, but I will eventually. I with "reference in new issue" was more fully featured.  Like, let me copy/paste from the origin page and apply one of the templates.  And don't leave the current page FGS.

2022-10-28 17:33 UTC, hepcat72 commented
> I would prefer we have the issues worked out before we merge this. I'm open for a discussion after 2 PM today or we can talk on Monday.

I haven't tried the page out, but I see no real breaking issue with it the way it is.  The only thing I envision would not be ideal is seeing errors about inconsistent protocols, but even with that, I don't think the sample and accucor loaders even make those checks.  They just blindly get or create.  What is the problem as you see it?

2022-10-28 17:52 UTC, jcmatese commented
we don't necessarily need to merge it, if people are hesitant or think it is not pressing.  I still have doubts that the `nan` replacement and `strip()` are having the desired output on the incoming protocols data frame, but I am trying that now.

2022-10-28 18:02 UTC, lparsons commented
>  What is the problem as you see it?

The problem is that I don't feel like anyone actually knows the implications of this PR on the validation page and what steps will be needed to fix them. Once we merge this, we are committed to either fixing the validation or removing it. Our deadline for this milestone is next week, which we can push a bit if we need, but I don't want to push it too far.

> we don't necessarily need to merge it, if people are hesitant or think it is not pressing. I still have doubts that the nan replacement and strip() are having the desired output on the incoming protocols data frame, but I am trying that now.

To me, this signifies that we don't have appropriate tests in place. @jcmatese , can you create a test protocols file and write a few tests that will cover the issues you remain uncertain about?

2022-10-28 18:25 UTC, hepcat72 commented
> > What is the problem as you see it?
> 
> The problem is that I don't feel like anyone actually knows the implications of this PR on the validation page and what steps will be needed to fix them. Once we merge this, we are committed to either fixing the validation or removing it. Our deadline for this milestone is next week, which we can push a bit if we need, but I don't want to push it too far.

I mean, I'm pretty confident in my assessment and the validation page tests pass, but if it makes you feel any better, I can run a few manual validations just to have a look at it on the page.  Is there a specific test case you're concerned would cause a problem?

As I was telling John on slack, the validation page is just a wrapper of the sample and accucor load scripts.  It just reports the errors that come out of those loads to the users.  It makes a couple arbitrary choices about decresing the severity level of certain errors, but every error is always reported.  And the current tests do not show that any new errors are coming out of the tests...

2022-10-28 18:29 UTC, lparsons commented
Researchers are expected to submit animal treatments as part of the animal and sample sheets.  Those need to be loaded into the validation database before validating the animals and samples will load. The steps to make that happen should be outlined somewhere. Once they are sufficiently determined, then I think we can move forward. I don't foresee that functionality as being too hard to implement, but I think we should have a good idea of how it will work before we commit something (this PR) that will cause new submissions that should be valid, to fail validation.

2022-10-28 18:43 UTC, jcmatese commented
> To me, this signifies that we don't have appropriate tests in place. @jcmatese , can you create a test protocols file and write a few tests that will cover the issues you remain uncertain about?

I will check in what I was working with, but I don't ahead the code fixes, yet (was just starting when I got distracted by HTSEQ).

2022-10-28 18:44 UTC, hepcat72 commented
> Researchers are expected to submit animal treatments as part of the animal and sample sheets. Those need to be loaded into the validation database before validating the animals and samples will load.

OK, having just reviewed the sample table loader code, I see what you mean now.  All the script does is a `get` and raises an error if it's not there.

> The steps to make that happen should be outlined somewhere. Once they are sufficiently determined, then I think we can move forward.

Alright.  The steps are straightforward.  Just run the new protocol loader script in this PR in exactly the same way we load tissues and compounds (i.e. without the --database and without the --validate options).  It will load into both databases by default, which is the desired behavior.  And the treatment load files are all in the PR, correct?

> I don't foresee that functionality as being too hard to implement, but I think we should have a good idea of how it will work before we commit something (this PR) that will cause new submissions that should be valid, to fail validation.

The remaining issue is expected novel treatments.  Since there's no run of the protocol load on the submitted sample file, the validation page's run of the sample load would stop at the first novel treatment.

1. I think those errors should be buffered and reported at the end
2. The validation wrapper should *not* handle treatment protocols like tissues and compounds (i.e. treat them as pre-loaded).  This means that it should mimic the sample loader code
   - `self.loading_mode` should be removed
   - There should not be a second call to `load_database`
   - The protocol table should not be skipped during the clearing of the validation database

2022-10-28 18:54 UTC, jcmatese commented
I believe the validation could probably call psuedocode `load_protocols(protocols="submitted_animals.xlsx", database="validator")`, and assuming pre-existing protocols are already there, and new ones in the sheet would be loaded (but not in production), then that same workbook could attempt the loading of animals and samples in validator, which it presumably already does?

2022-10-28 18:55 UTC, hepcat72 commented
Doing a manual test in the shell, BTW, I see that it *does* check the consistency WRT name and description, so that's good:

```
LoadingError: Errors during protocol loading :
 Error in row 3: ["Protocol with name = 'Default' but a different description already exists: Existing description = 'For protocol's full text, please consult Michael Neinast.' New description = 'For protocol's full text, please consult anonymous.'"]
```

However, given the code that I know is in the accucor loader, it generates an MSRun protocol with the name 'Default' and a description that includes the researcher.  That will be a problem.

2022-10-28 18:57 UTC, jcmatese commented
> However, given the code that I know is in the accucor loader, it generates an MSRun protocol with the name 'Default' and a description that includes the researcher. That will be a problem.

Yah, I mainly focused on the animal treatments, and generic loading of any protocols, but did not touch msrun loading at all.

2022-10-28 19:00 UTC, hepcat72 commented
Scratch that.  I just double-checked.  It uses "protocol_input", which I assume is from the spreadsheet.  I think I was remember debug output from a test, not what's in the code.  So it should be OK.

2022-10-28 19:28 UTC, hepcat72 commented
OK, I'm playing around with the validation page and I do see issues having to do with an operation on the incorrect database (creating links From FCirc to Tracer using records from the different databases).  Should be easy to fix.  Regardless, whichever way we decide to treat protocols in the validation database, I don't think that there exists significant issues WRT this PR.  I do think that we should do as I recommended above though.

2022-10-28 21:09 UTC, fkang-pu approved these changes
Look good to me. Only minor comment: since the input for protocol loader is data frame, it should be quick and easy to check unique values for each column. It might be better than checking name, category, description when going through each row.

2022-10-31 14:46 UTC, merged