Compound view refactor
Princeton-LSI-ResearchComputing/tracebase pull request #54
Opened 2021-04-28 18:13 UTC by hepcat72

## Summary Change Description

Copied home template to a compound_list template and changed the home template to be a list of table list-views.  Also changed the format of the list view from a UL to a table where each row is a record.  The purpose is to support multiple table views.

## Affected Issue Numbers

- Resolves #53

## Code Review Notes

Note, I added a `__str__` method to the compound model and a conversion method, which was a part of my builtin exploration, but left them.  Create an issue to remove if this is redundant/unnecessary.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-04-28 20:56 UTC, lparsons requested changes
The view and templates look good to me, but the (unrelated) changes to `CONTRIBUTING.md` might have an error. In the future, it would be easier to keep documentation changes in a separate PR.

2021-04-28 20:56 UTC, lparsons commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
Have you tried this? I don't think this works, super-linter is expecting things to be in `/tmp/lint` inside the container. 

See the [docker documentation on the `--volume` flag](https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag):
> `-v` or `--volume`: Consists of three fields, separated by colon characters (`:`). The fields must be in the correct order, and the meaning of each field is not immediately obvious.
> * In the case of named volumes, the first field is the name of the volume, and is unique on a given host machine. For anonymous volumes, the first field is omitted.
> * The second field is the path where the file or directory are mounted in the container.
> * The third field is optional, and is a comma-separated list of options, such as `ro`.

2021-04-29 15:33 UTC, hepcat72 commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
OK.  You're right.  When I initially ran with `/tmp/lint`, I got a `does not exist` error and super-linter wouldn't run:
```
$ ../lint.sh 
Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory
docker: Error response from daemon: dial unix docker.raw.sock: connect: no such file or directory.
See 'docker run --help'.
```
Since it didn't give me the path about the offending file, I initially assumed that `/tmp/lint` was a path to a tmp dir on linux that didn't exist for me.  I had changed it, but got the same error.  When I was updating the doc, I forgot that the fix I'd found that worked was to "reset to factory defaults" on docker's trouble-shooting page.

Good catch, I will fix it.

- [ ] Revert the tmp dir path in contrib.

2021-04-29 15:35 UTC, hepcat72 commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
It was probably because I had a pre-existing .docker dir, but until yesterday, had not actually installed docker on this new laptop.

2021-04-29 15:59 UTC, jcmatese commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
regarding running superlinter via docker locally, I still seems to get differences in uniform linting "success", which makes me think there are some env-specific configurations.  Maybe it is just me, though
local success:
![image](https://user-images.githubusercontent.com/6091114/116581183-11d24400-a8e2-11eb-8d25-ef59ae753655.png)
vs GitHub action failure:
![image](https://user-images.githubusercontent.com/6091114/116581268-26aed780-a8e2-11eb-95db-92e003699a58.png)

2021-04-29 17:35 UTC, jcmatese commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
Maybe be too many variables to control for (because perhaps that migrations file was added between runs; would have to search logs).  The initial command was
```
#!/usr/bin/env sh
    docker pull github/super-linter:latest

    docker run \
        -e FILTER_REGEX_EXCLUDE="(\.pylintrc|\.github)" \
        -e LINTER_RULES_PATH="/" \
        -e IGNORE_GITIGNORED_FILES=true \
        -e RUN_LOCAL=true \
        -v ~/dev/tracebase/:/tmp/lint github/super-linter
```

But after that initial launch, I have just been clicking the "run" button in docker desktop app.
![Screen Shot 2021-04-29 at 1 33 49 PM](https://user-images.githubusercontent.com/6091114/116593860-8fe91780-a8ef-11eb-91ec-816984f8ec1c.png)

Let me peruse the logs, out of curiosity...

2021-04-29 17:41 UTC, jcmatese commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
"Your branch is up to date with 'origin/accucor-data-load'.

nothing to commit, working tree clean"

2021-04-29 17:43 UTC, jcmatese commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
Beats me.  Maybe if I just not running it often enough, or not at the right time (just before push)...

2021-04-30 21:52 UTC, hepcat72 commented on CONTRIBUTING.md
> +        -v /full/path/to/tracebase/:/full/path/to/tmpdir github/super-linter
In those cases, where superlinter behaved differently in the gh action versus my local individual linter tool runs, it was due to differences in the settings for the linter tools.  The first thing I would check is that your branch is in synch with the remote version.  I assume you did a `git status` to see that you're up to date - but that's only a local check with your copy of the head of that branch.  To check with the remote, you'd need to do a `git fetch` and a `git pull`.  Lance would be better at describing the difference, but usually when I run into weird issues, it's because I hadn't done a `git fetch`.  That doesn't change your code on your branch.  It updates you local repo's awareness of other changes going on elsewhere, which may include your branch's up-to-dateness with the remote copy of the branch.

I think that the superlinter settings can be different per-branch.  I.e. they are not global settings.  If they were global, and you were out of date with the remote version, that could explain the difference.  I don't think they are global though, so that couldn't explain it.  So the way I would check is to look at the specific error from flake8 in the remote log and see what settings you have that could differ...

2021-05-04 13:31 UTC, lparsons approved these changes
LGTM, :shipit:

2021-05-04 15:16 UTC, jcmatese approved these changes

2021-05-04 15:47 UTC, fkang-pu approved these changes

2021-05-04 16:21 UTC, merged