Last caveat
Princeton-LSI-ResearchComputing/tracebase pull request #545
Opened 2022-10-06 17:28 UTC by hepcat72

## Summary Change Description

Added a column to the FCirc format output of advanced search to let the user know what issues may exist with the FCirc calculations and the determination of the "last" serum tracer peak group.

Also addressed a couple other things:

- Updated the github template tags
- Corrected a few print messages and comments that I encountered
- Added catches of TransactionManagementErrors that I encountered during this implementation
- Added `Sample.is_last_serum_sample`

## Affected Issue Numbers

- Resolves #514

## Code Review Notes

I did not include the new column in the downloads.

The MaintainedModel catches/warnings do not occur currently.  I eliminated them from happening by rearranging the code in the tests, but the catches and warnings I added should help tremendously if they are encountered again in the future.  If you want them to be tested, I suggest suggesting we create an issue to test them.  I tried to catch everywhere where I think such an error could occur - it's basically whenever the database could be hit on a record that hasn't yet been committed to the database during an atomic transaction.  Note, accessing a value in the object doesn't necessarily hit the DB, which is why the autoupdates *can* work inside an atomic transaction.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All *multi_working* tag tests pass locally](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*
  - [x] `@tag("multi_working")` added to newly passing test functions/classes *(or no newly passing tests)*
  - [x] `@tag("multi_broken")`, `@tag("multi_unknown")`, or `@tag("multi_mixed")` removed from newly passing test functions/classes *(or no newly passing tests)*

2022-10-06 19:33 UTC, lparsons requested changes
The FCirc status updates look great, and I think they could be a great help to researchers. Nice work!

The changes to transaction management do not seem relevant for this PR and at the moment I don't fully understand them. If they are not required for the FCirc status updates, I would ask that we split them out into their own PR and discuss. It seems dangerous to be performing queries inside of atomic blocks, and more dangerous to be ignoring exceptions. It may all be OK, but it strikes me as an issue with the design that we should take a closer look at. At least, I'd like to be confident that the errors being ignored are *always* safe to ignore.

2022-10-06 19:33 UTC, lparsons commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: type:bug
NB: Would prefer the issue template changes be part of a separate PR that we could quickly merge.

2022-10-06 19:33 UTC, lparsons commented on DataRepo/models/fcirc.py
> +        overall = 1
NB: This is a lot of variables, many of which I am unable to decipher the meaning of.

2022-10-06 19:33 UTC, lparsons commented on DataRepo/models/fcirc.py
> +                ):
Q: Given that `is_last_serum_peak_group` is true, it seems odd that this would not be the last serum sample. My confusion is likely due to my not understanding the subtleties of `is_last_serum_peak_group` and `last_serum_sample`, but perhaps some additional explanation could help here?

2022-10-06 19:33 UTC, lparsons commented on DataRepo/models/fcirc.py
> +                        tc_none_samples.append(str(s))
NB: I wonder if this logic could be encapsulated in a function much like `is_last_serum_sample`. Perhaps `animal.has_null_time_serum_samples` or something similar?

2022-10-06 19:33 UTC, lparsons commented on DataRepo/models/fcirc.py
> +            ):
NB: Similar encapsulation could possible be done here.

2022-10-06 19:33 UTC, lparsons commented on DataRepo/models/maintained_model.py
> +                raise tme
C: I assume this logic is sound, but this code makes me a tad nervous that we might accidentally let some "real" problem pass with only a warning and thus void the guarantee of an atomic transaction.

Q: I'm confused as to why this is part of FCirc status updates. If it is not, please split out into a separate PR so that the changes can be better reviewed and tested.

2022-10-06 20:38 UTC, hepcat72 commented on DataRepo/models/fcirc.py
> +        overall = 1
I found it difficult to come up with succinct variable names, but I'll take a stab.

- [ ] Make more descriptive variable names.

2022-10-06 20:38 UTC, hepcat72 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: type:bug
reverted

2022-10-06 21:00 UTC, hepcat72 commented on DataRepo/models/fcirc.py
> +                        tc_none_samples.append(str(s))
- [ ] TODO: Encapsulate the `serum_validity` conditionals in their own functions

2022-10-06 21:45 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
> +                raise tme
Now that you have me thinking about this... let me back up and answer your question first.  The answer to the question is somewhat answered in the commit log messages (see the third commit log message). But to summarize, I was running into transactionManagementErrors during the development of the tests.  It took awhile to figure out what the problem was, and since the changes are interspersed with other commits and the solution was fresh in my mind, I wanted to capture what I had learned and create warnings that would aid me if I encountered them in the future.

This is now a new issue. I'd seen them twice before and had worked those cases out independently, but perhaps not as thoroughly (at least in terms of discretely understanding *why* the errors would happen in some cases and not in others).  Before, the main issue had been operations on stale buffer contents and I'd pretty much stopped there.  The time before that, it was related to the unique transaction wrapper django applies to every test, which I'd resolved by creating and applying `TracebaseTransactionTestCase` as a base class.  Here though, the error was occurring even with that fix and I learned it was due to how django's transaction wrapping doesn't seem to cover the `setUp` method.

Auto-updates *do* work in atomic transactions except in specific cases, which I have a better feel for now.  I don't 100% understand it, but I feel like I learned enough of the components at play to fix the way the code is arranged to avoid them, such as not using `setUp` - I moved that code to inside `setUpTestData`.

The suggestion for performing auto-updates after an atomic transaction block has to do with needing to propagate changes from parent records to children, for which I currently use `.count()` to see if I need to propagate, `.first()` to get the Model type, and `.all()` to loop and call their `.save()` methods to trigger the updates.  We didn't have propagation from parents to children before, but the FCirc autoupdates required it.

In *any* case, the logic behind deciding to ignore those exceptions was that all we're doing is skipping auto-updates, which can easily be rectified after-the-fact.  That brings me back to my initial thought...

I got all the code to work without triggering any of these warnings, but I decided to wrap everywhere I thought it *could* happen in the future, and in this case, I applied the catch where it shouldn't go, because it wraps the call to `super().save()` that actually performs the real data save (at least in the case of the triggering edit).  I should remove this single catch.  Any exceptions that could be the result of a TME would be caught and ignored (as related to auto-updates) so that this super call can still happen.  There should not exist an exception here, and if it did happen, it would, as you worried, cause a real problem.

- [ ] TODO: remove the TransactionManagementError catch wrapping the super save call.

2022-10-06 22:02 UTC, hepcat72 commented
> The changes to transaction management do not seem relevant for this PR and at the moment I don't fully understand them. If they are not required for the FCirc status updates, I would ask that we split them out into their own PR and discuss. It seems dangerous to be performing queries inside of atomic blocks, and more dangerous to be ignoring exceptions. It may all be OK, but it strikes me as an issue with the design that we should take a closer look at. At least, I'd like to be confident that the errors being ignored are _always_ safe to ignore.

I agree that more is to be done to fully understand the circumstances surrounding the TransactionManagementErrors, however given how difficult it would be to tease out these changes from the overall effort and my understanding of the scope of the effect of these changes, here's what I will do and why:

- I am going to remove the one catch I identified from your review surrounding the super.save() call.
  - Everything else, I am confident only results in auto-updates *not* being performed, which is easily rectified by running `pythong manage.py rebuild_maintained_fields` and does not affect the saving or loading of data from the files.
  - There is no change in behavior by removing that catch.
- I'm going to leave the catches/ignores/warns surrounding the database queries (`.count()`, `.first()`, `.all()`) and I propose we create an issue to intentionally test the triggering of these warnings
  - MaintainedModel cannot currently be written to propagate changes from parent to multiple children or through M:M models because that requires queries.  It was designed to buffer such changes to deal with that so that those updates could be performed after the block.  In fact, now that I think of it, those buffered updates could probably be located in their own atomic transaction block because the buffer-based update does not propagate and thus does not use queries.
  - We already have/had code merged into main where this requirement (of not being compatible with atomic transactions) was established and approved - and these warnings only aid in resolving issues where we run into errors from putting auto-updates inside atomic transaction blocks

Given this plan, I don't think there's anything dangerous involved.

2022-10-06 22:40 UTC, hepcat72 commented on DataRepo/models/fcirc.py
> +        overall = 1
I updated the names, but now they're probably too long.  If you understand them and have alternative suggestions, please provide.

2022-10-07 20:27 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
> +                raise tme
Thought more about this given yesterday's insight.  I think that the only exceptions that could be thrown here are the original ones involving the unique constraint, and given the work I did dealing with that when I encountered it before, I suspect that that can happen due to stale buffer contents, so instead of a warning, I created an exception to yield a hint about stale buffer contents.  There is no case now where an exception coming from this super.save call is ignored.

2022-10-07 20:55 UTC, hepcat72 commented on DataRepo/models/fcirc.py
> +                        tc_none_samples.append(str(s))
Seemed too simple for a separate function, so I took this to mean that the comments were hard to understand and reworded them and added comments in-line inside the conditional.

2022-10-10 17:41 UTC, lparsons approved these changes
I'm still a bit uncomfortable about some of the existing catches/ignore/warns, but your proposal sounds like a reasonable plan forward. Unfortunately, it looks like this branch was rebased (or at least force-pushed somehow), so it's tough for me to see what changed since my last review. Rob, if you are confident that these changes are needed for things to work properly, then go ahead and consider this approved, assuming the issues are created for proper follow-up in the next milestone.

2022-10-10 19:12 UTC, hepcat72 commented
Sorry about that. I probably should not be in the habit of rebasing, because it necessitates a force push (at least, I'm unaware of any way around that).  Given your continued concern, let me double-check some things and make sure follow-up issues are created.  I'll also go the extra mile and do some additional manual testing, but I am quite confident in the code.  I was already catching different errors in similar places.  I only considered the catches to be helpful aids for future development...

2022-10-10 19:22 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
>                  raise uc
C. Since these catches pre-date this PR, I thought about it some more.  While this is a call to the super class (`Model`), it can be called either via an explicit call from outside code (including calls to perform_mass_autoupdates) or it can be called via triggered updates of parent or child records, so I realized I should keep the try/catch, but I did 2 things:

- I always raise an exception (adding the tips to debug it if it occurs)
- Removed the TransactionManagementError catch since such errors should be caught and handled deeper in this code - and I don't want to catch errors caused by the explicit record updates.

2022-10-10 19:25 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
>                      )
C. These errors can only be caused by auto-update code and should not hold up the explicit record updates (the call to `super().save()`), since these auto-update fields can be filled in later.

2022-10-10 19:26 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
> +                        )
C. These errors can only be caused by auto-update propagation code and should not hold up the explicit record updates (the call to `super().save()`) whose changes triggered this propagation, since these auto-updates can be filled in later.

2022-10-10 19:27 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
> +                            )
C. These errors can only be caused by auto-update propagation code and should not hold up the explicit record updates (the call to `super().save()`) whose changes triggered this propagation, since these auto-updates can be filled in later.

2022-10-10 20:16 UTC, jcmatese approved these changes
I am ok with it (commented on what occurred to me while reading).

2022-10-10 20:16 UTC, jcmatese commented on DataRepo/models/maintained_model.py
>                  raise uc
C:  cant's speak to this, as  I have not really tried anything like this at scale (auto-updates on unique values).  It is difficult for me to consider the scenarios that would generate this errors.

2022-10-10 20:16 UTC, jcmatese commented on DataRepo/models/maintained_model.py
>                      )
C: Similar to above. Kind of beyond my experience, and assume that more warnings are a good thing, as longs as curators are the ones seeing them while curating/loading studies.

2022-10-10 20:16 UTC, jcmatese commented on DataRepo/models/maintained_model.py
> +                        )
C: as above, will take you work for it...

2022-10-10 20:16 UTC, jcmatese commented on DataRepo/models/maintained_model.py
> +            "rebuild_maintained_fields\n\n."
C: I feel like this is an important explanation that we might eventually want to copy and expound upon in some other developer documentation, once we get a better handle on complex django transactions (like study loading), the validation database, the on-the-fly test database(s), and perhaps the maintained models and cached decorators (the the interactions of the aforementioned).

2022-10-10 20:16 UTC, jcmatese commented on DataRepo/tests/models/test_fcirc.py
> +            self.assertEqual("100000100", fcr.serum_validity["bitcode"])
Q: I assume this helpful dictionary will be in some developer-facing document, eventually? Or rather, perhaps a generic  decoder, as opposed to this specific one (noe that aI see other similar explanations, below)

2022-10-10 21:07 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
>                  raise uc
These particular errors (at least the ones I've encountered) happen in the tests if the code in one test does a DB load and does not empty the buffered autoupdates.  I'd encountered these when I buffered auto-updates in one test (to intentionally not do those autoupdates) and neglected to empty the buffer, which triggers auto-updates on records that no longer exist.

2022-10-10 21:09 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
>                  raise uc
It presents as a unique-constraint error because it's trying to save a record whose object no longer is linked to the record saved in the previous test, so it ends up being interpreted as a duplicate add attempt, which runs afoul of the unique constraint.

2022-10-10 21:12 UTC, fkang-pu approved these changes
It's very helpful to have the new column to list issues with FCirc calculations. Nice addition! I went through the code related to maintained_model and autoupdate, but still need more time to understand details about how errors and exceptions are handled. After soft launch, I also want to take a bit time to think about FCirc model. One possible option is to store every serum sample with its MsRun(s), tracer_peakgroup(s), and other values related to FCirc, but only retrieve and display FCirc for last serum sample. It could simplify some code for evaluating different issues and also easy to see/debug edge cases. Just a thought for future discussions, not in scope of this PR.

2022-10-10 21:18 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
>                      )
The `Exception` in the inner try/catch occurs when trying to get a value from the object, the sole purpose is for printing the change status in the Auto-update console print, so failure to compose that message shouldn't hold things up.  The TransactionManagementError however occurs in specific cases when the auto-updates are performed inside an atomic transaction and the updater function (called via `update_fun()`) uses a database query to compose the new auto-updated value.  In this case, I print a warning and simply skip the auto-update.

2022-10-10 21:20 UTC, hepcat72 commented on DataRepo/models/maintained_model.py
> +                        )
This is similar to the catch above, but in this case, it's because to traverse that relationship and propagate an auto-update to a 1:M or M:M parent record, it has to do a query, and queries are a no-no inside atomic transactions (because you're querying records that have not yet been committed).

2022-10-10 21:23 UTC, hepcat72 commented on DataRepo/tests/models/test_fcirc.py
> +            self.assertEqual("100000100", fcr.serum_validity["bitcode"])
I tried to explain it in the docstrings, but the concrete examples are definitely easier to consume.

2022-10-10 21:24 UTC, merged

2022-10-10 21:25 UTC, hepcat72 commented
Merged on the command line.