Add Documentation
Princeton-LSI-ResearchComputing/tracebase pull request #598
Opened 2023-01-09 17:35 UTC by mneinast

## Summary Change Description

Add documentation to wiki.  Initial commit of Markdown documentation served as readthedocs in GitHub Pages.

## Affected Issue Numbers

- Resolves #567 

## Code Review Notes

All documentation files are found in the `TraceBaseDocs` folder.  See ReadMe inside that folder for details.

## Checklist

- [ ] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [ ] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-01-10 15:29 UTC, jcmatese approved these changes
Thanks for doing this!  I hope it assists your lab and they appreciate it.  I made some comments/suggests for very minor things that I saw in the `TraceBaseDocs` directory.  Some questions others might know better than I (since I don't know the interaction of Obsidian and mkdocs at all):

1. Do we really want the `.obsidian` directory in the repo?  Is it shared between people, or will it change every time a new person touches/edits `TraceBaseDocs`?
2. Does the html tree in `public` just replicate the markdown in `TraceBaseDocs`, or is it padded out with additional documentation pulled from the code base?  Just asking because if `public` is just a html rendering site of `TraceBaseDocs`, you _might_ want just the source (markdown), and not both "copies" of text that must be kept synced?  Others might have better informed opinions on this...

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +Mixtures of compounds are formatted: `tracer_mix_name {tracer; tracer}
missing a quote? (uncertain)
```suggestion
Mixtures of compounds are formatted: `tracer_mix_name {tracer; tracer}`
```

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +   * Example:  “T3 in drinking water”
May want a phrase here to make clear that lab-shared protocols/treatments that are uniquely named can shared between lab members (only 1 record in TraceBase...

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +Describe here experimental design, citations if the data is published, or any other relevant information that a researcher might need to consider when looking at the data from this study
```suggestion
Describe here experimental design, citations if the data is published, or any other relevant information that a researcher might need to consider when looking at the data from this study.
```

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +Unique identifier for the biological sample. Must match the name of a sample in Accucor or Isocorr data
```suggestion
Unique identifier for the biological sample. Must match the name of a sample in Accucor or Isocorr data.
```

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +Date sample was collected (YYYY-MM-DD)
```suggestion
Date sample was collected (YYYY-MM-DD).
```

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +* If you have a tissue that is not listed in `Tissues` tab, add your new tissue to the `Tissues` tab
```suggestion
* If you have a tissue that is not listed in `Tissues` tab, add your new tissue to the `Tissues` tab.
```

2023-01-10 15:29 UTC, jcmatese commented on TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md
> +Matches to the Animal ID that this sample was collected from
```suggestion
Matches to the Animal ID that this sample was collected from.
```

2023-01-10 16:07 UTC, jcmatese commented
> I agree obsidian should be excluded from this. Maybe entirely so there is no mention of it?

In that case, perhaps we could add it to the [`.gitignore`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/.gitignore) . We can see what other think.

2023-01-10 17:04 UTC, hepcat72 requested changes
Wow, this was a lot of work!  Great job.  The one thing that I think needs addressing is the (temporary) removal of the validate step.  See the comment on that section below.

2023-01-10 18:25 UTC, mneinast commented on TraceBaseDocs/TraceBaseDocs/Overview/Data Privacy and Attribution.md
> +Published work using data from TraceBase should cite the Researchers listed in TraceBase.  When TraceBase is published, an appropriate citation will be listed here.
I agree and part of the problem is that "here" is ambiguous.  I meant that citations could be listed in the Study Description.  Maybe we just state that simply, and not describe "future" anything?

2023-01-10 18:26 UTC, mneinast commented on TraceBaseDocs/TraceBaseDocs/Overview/Structure of TraceBase for the Researcher.md
> +Calculated data are found in three types of output: [PeakData](../Types%20of%20Data%20Output/PeakData.md), [PeakGroups](../Types%20of%20Data%20Output/PeakGroups.md), and [Fcirc](../Types%20of%20Data%
good point - I could be ok providing your more detailed description here.  It will be very important that lab members understand exactly what is calculated.

2023-01-10 18:28 UTC, mneinast commented on TraceBaseDocs/TraceBaseDocs/Upload/How to Upload.md
> +   3. If there are any errors reported, fix them in the Google spreadsheet and return to step 1.
ah i didn't realize validation was removed!  Yes we should revise to match current state of upload process.

2023-01-10 18:36 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/Structure of TraceBase for the Researcher.md
> +Calculated data are found in three types of output: [PeakData](../Types%20of%20Data%20Output/PeakData.md), [PeakGroups](../Types%20of%20Data%20Output/PeakGroups.md), and [Fcirc](../Types%20of%20Data%
If we want to be *very* precise, there are some caveats to be aware of... If 2 serum samples have the same date, the one designated "last" is *arbitrary*.  We don't currently have a way to consistently order them (in different load instances).  We also cannot tell the difference in msruns with the same date.  In the case of msruns, only the last one is ever used for calculations (and in looking for tracer compound peak groups.  Note the comment in the code for the `is_last_serum_peak_group` method:

> Note, there is an FCirc record for every serum sample, tracer, and label combo.  Each such combo represents a single "peak group" even though there can exist multiple peak groups from different serum samples and different msruns from the same serum sample.  However, multiple msruns from the same sample are ignored - only the last one is represented by a record in this table.  Michael and I (Rob) discussed whether it was worthwhile to compute values for peak groups from this sample in prior msruns and Michael said no, so:
> 
> This method determines whether the peak group from the last msrun that included this tracer and label is the last peakgroup when considered among multiple serum samples.  There could exist last peak groups in prior serum samples that would result in a false return here.

2023-01-11 21:45 UTC, lparsons requested changes
This is excellent Michael, thanks for putting so much of this together. Generally, it looks very good and is a huge improvement to the documentation for TraceBase.

I had a few comments here and some suggestions inline.

1. I love Obsidian, but I don't think we want to include that directory in the repository. While it's a great way to edit the markdown files, and I appreciate the addition of the config info in the README.md, any editor can be used. 

2. I would suggest that we rename the tracebase logo image file

2023-01-11 21:45 UTC, lparsons commented on TraceBaseDocs/README.md
> +1) `python mkdocs serve --verbose` (verbose is optional but recommended)
This is what worked for me:

```suggestion
1. `cd TraceBaseDocs`
2. `mkdocs serve --verbose` (verbose is optional but recommended)
```

2023-01-11 21:45 UTC, lparsons commented on TraceBaseDocs/README.md
> +2) `pip install mkdocs-roamlinks-plugin` ([roamlinks](https://github.com/Jackiexiao/mkdocs-roamlinks-plugin) adds support for some Obsidian links)
If we add these lines to `requirements/dev.txt` it would keep all of the developer requirements together. 

```
mkdocs>=1.4.2
mkdocs-roamlinks-plugin>=0.1.3
```

Then we could replace this with `python -U pip install -r requirements/dev.txt`

2023-01-11 21:45 UTC, lparsons commented on TraceBaseDocs/TraceBaseDocs/Untitled.md
> +
Probably want to remove this file...

2023-01-11 21:45 UTC, lparsons commented on TraceBaseDocs/TraceBaseDocs/Overview/Data Privacy and Attribution.md
> +All data derived from each animal is associated with a Researcher, or the person primarily responsible for the animal experiment.  During the upload process, additional Researchers might be identifie
I like having this, but it is really something specific to our instance of TraceBase and not general documentation of the software. Perhaps we could put this on the data repo wiki: https://github.com/PrincetonUniversity/tracebase-rabinowitz-data/wiki.

2023-01-13 16:24 UTC, fkang-pu approved these changes
Nice work!

2023-01-13 16:24 UTC, fkang-pu commented on TraceBaseDocs/TraceBaseDocs/Upload/Labeling and Organizing Data.md
> + - create a folder for each sequence that includes the date of LCMS and experiment identifier
To capitalize the first letter? Just make it consistent throughout the document.

2023-01-13 16:27 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/Labeling and Organizing Data.md
> + - create a folder for each sequence that includes the date of LCMS and experiment identifier
Yeah, that and usage of periods. I thought to suggest the same thing, but didn't.

2023-01-13 18:18 UTC, mneinast commented on TraceBaseDocs/TraceBaseDocs/Overview/Structure of TraceBase for the Researcher.md
> +Calculated data are found in three types of output: [PeakData](../Types%20of%20Data%20Output/PeakData.md), [PeakGroups](../Types%20of%20Data%20Output/PeakGroups.md), and [Fcirc](../Types%20of%20Data%
i'm incorporating this into the description of `Normalized Labeling.md`

2023-01-13 18:18 UTC, mneinast commented on TraceBaseDocs/TraceBaseDocs/Overview/Structure of TraceBase for the Researcher.md
> +Standardized data refers to Sample and Compound attributes that are kept consistent across datasets in TraceBase.  Examples of these consistent data include compound names, tissue names, researcher n
I'm modifying the figure and adding some text to describe protocols.

2023-01-18 21:33 UTC, lparsons approved these changes
This looks great @mneinast! The only thing left I see it to remove the `.obsidian` directory from the PR. That's actually a bit of PITA I think, so we can probably do it once everything else is ready but before we merge. Once we're ready to merge, let me know and I'll look into it (unless someone else wants to sort that out... 😉 ).

Also, if you've addressed all of @hepcat72 's comments, you can "re-request" a review from him at top right of the PR page.

2023-02-08 17:07 UTC, lparsons commented
@mneinast Can you please run `git rm -r TraceBaseDocs/TraceBaseDocs/.obsidian` and then do a `git committ` and `git push` to remove that `.obsidian` directory? Then we can merge this and get the docs website live. Let me know if you have any questions or issues doing that.

2023-02-09 19:34 UTC, merged