Add element_count to Compound
Princeton-LSI-ResearchComputing/tracebase pull request #60
Opened 2021-04-30 01:59 UTC by lparsons

## Summary Change Description

The method uses the chempy package to parse the chemical formula and
returns the count of the specified element in the compound.
## Affected Issue Numbers

- Resolves #59

## Code Review Notes

I decided to use the chempy package, which is heavyweight, but seems rather robust. It may be useful for other things in the future as well. If we decide it's too heavyweight, it should be simple to replace it without changing the behavior of the `element_count` method.

## Checklist

- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
- [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)

2021-04-30 12:49 UTC, jcmatese approved these changes
I think this would be fine, as-is, but you _may_ want to consider an abstract/inherited/imported method that could also be utilized by `PeakGroup` which also has a `formula` , and _may_ be simpler to work with? (closer to the data).  That way, both `Compound` and `PeakGroup` could call `element_count`, on their own intrinsic `formula`?

2021-04-30 13:27 UTC, lparsons commented
> I think this would be fine, as-is, but you _may_ want to consider an abstract/inherited/imported method that could also be utilized by `PeakGroup` which also has a `formula` , and _may_ be simpler to work with? (closer to the data). That way, both `Compound` and `PeakGroup` could call `element_count`, on their own intrinsic `formula`?

Good point! I agree with you if we keep the model as is.

Somehow I didn't realize that both tables had a "formula" attribute, and in fact the documented model in #16 only has formula in `PeakGroup`. To avoid inconsistency, we should eliminate the duplication of `formula` or do something to ensure that the `formula` matches between associated `Compound`s and `PeakGroup`s. 

Here is my proposal (thoughts @fkang-pu @hepcat72 @jcmatese)

* Store `formula` in `Compound`. This makes logical sense (compounds have formulas). 
* Add validation logic to `PeakGroup` to ensure that all associated `Compound`s have the same formula
* Create a property `PeakGroup.formula` that returns the first `Compound.formula`
* Create a method `PeakGroup.element_count` that calls the first `Compound.element_count`

2021-04-30 14:05 UTC, jcmatese commented
I think `PeakGroup.formula` (and `name`, for that matter) is a proxy compound detection/alias for "given this specific chromatography (`med_rt`) and this `med_mz`, _you have it on my authority_ that it is _this_ molecular formula/structure we are targeting, which should be these compound(s)", as opposed to other competing formulas that might share the approximate m/z.  So you can _either_ consider it redundant, and in danger of being inconsistent with linked compounds, _or_ an important logical cross-reference that you could leverage(with validation).  I don't feel strongly, either way, other than to say it is theoretically [possible to have multiple compounds at the same m/z](https://www.uni-saarland.de/fileadmin/upload/lehrstuhl/jauch/An04_Massenspektroskopie_Skript_Volmer.pdf) (see slides 37-41), if you hadn't already done the profiling required to document where isolated metabolites are separated, given standard chromatography protocol(s).

2021-04-30 14:09 UTC, fkang-pu commented
@lparsons @jcmatese @hepcat72 I think `formula` should be in `Compound`.  To handle referencing `formula` in `PeakGroup` to `Compound`, another proposal is to add `CompoundGroup` (Foreign key to `Compound`, `formula` is unique, or use `formula` as primary key directly), then `PeakGroup` would have M:M relationship with `CompoundGroup`. This would handle isomer cases (e.g.citrate/isocitrate ) without a work around.

2021-04-30 14:16 UTC, lparsons commented
> I think `PeakGroup.formula` (and `name`, for that matter) is a proxy compound detection/alias for "given this specific chromatography (`med_rt`) and this `med_mz`, _you have it on my authority_ that it is _this_ molecular formula/structure we are targeting, which should be these compound(s)", as opposed to other competing formulas that might share the approximate m/z.

Yes, this is my understanding as well.

> So you can _either_ consider it redundant, and in danger of being inconsistent with linked compounds, _or_ an important logical cross-reference that you could leverage(with validation).

The current model simply stores the `formula` for the `PeakGroup` separately from the `formula` for the `Compound` and does no validation. I agree with your interpretation that we are creating a "logical cross-reference". Given that the inference was made during the peak picking process in El-Maven, the `formula` is being associated with the `PeakGroup `at that time. If we implement my proposal, we could include some extra validation upon import to ensure that we associate exactly all of the compounds that share a formula with the formula in the El-Maven/AccuCor file as a further check on the researchers assumptions.

> I don't feel strongly, either way, other than to say it is theoretically [possible to have multiple compounds at the same m/z](https://www.uni-saarland.de/fileadmin/upload/lehrstuhl/jauch/An04_Massenspektroskopie_Skript_Volmer.pdf) (see slides 37-41), if you hadn't already done the profiling required to document where isolated metabolites are separated, given standard chromatography protocol(s).

Very good point. I think we add the extra validation upon import that I described above we would have a model that is more consistent with our interpretation and be able to catch logical inconsistencies before they get stored in the database.

2021-04-30 14:22 UTC, lparsons commented
> @lparsons @jcmatese @hepcat72 I think `formula` should be in `Compound`. To handle referencing `formula` in `PeakGroup` to `Compound`, another proposal is to add `CompoundGroup` (Foreign key to `Compound`, `formula` is unique, or use `formula` as primary key directly), then `PeakGroup` would have M:M relationship with `CompoundGroup`. This would handle isomer cases (e.g.citrate/isocitrate ) without a work around.

Yes, this would handle the citrate/isocitrate type cases very elegantly. My concern with this, however, is the need to define these groups _apriori_ in the database, which would add a lot of overhead for compound groups of size one (which would be most of them). I believe that my proposal is not a workaround, but instead adds some logical validation checks to ensure that the assumptions made by the researcher are correct. Basically, `PeakGroup` becomes an _ad-hoc_ `CompoundGroup` if needed. It might also make sense to display "isomers" on the `Compound` detail page (and maybe a flag on the `Compound` list) that shows other `Compound`s that share a formula.

2021-04-30 14:25 UTC, jcmatese commented
Yah, I would be ok with that proposal, then.  Will have to work out the sequencing, because the proposal also impinges on #55 , presumably.

2021-04-30 14:33 UTC, lparsons commented
> Yah, I would be ok with Lance's proposal, then. Will have to work out the sequencing, because the proposal also impinges on #55 , presumably.

Yes, it would likely have some affect on that. It seems simplest to merge #55 first, and update things in this new PR. Alternatively, if everyone is OK with this proposal and we want to merge it first, I would happy adding some commits to make #55 work with the new PR. Regardless, I will create an issue to define this proposal. If we merge #55 before I start work, great, if not, no big deal, I'll make the changes either way.

2021-04-30 14:41 UTC, jcmatese commented
Yah, I think it would be easier to merge this first, then apply the peakGroup model changes and methods (you proposal) on top of #55 , afterwards?

2021-05-03 18:47 UTC, hepcat72 requested changes
Nicely done. There was one issue I feel would be a solid improvement and one non-blocking code maintenance/duplication issue.  The others are very minor.

2021-05-03 18:47 UTC, hepcat72 commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
B. I'd prefer you use the `atomic_number` method from inside `periodic.py` instead of `symbols.index(atom) + 1`. It handles an exception for case.  It should be more robust if they ever change things.

2021-05-03 18:47 UTC, hepcat72 commented on DataRepo/models.py
> +        return atom_count_in_formula(self.formula, atom)
NB.  There are 2 copies of this method (`atom_count`) in this file: one in PeakGroup and one in Compound.  Perhaps both these classes should have a common base class that holds 1 copy of this method.

Q. What is the utility of storing a formula in PeakGroup in the model?  I believe I recall hearing about ionized versions of the same formula, which I assume is one things differentiates them and dictates the relationship - but why does the user need them?  I.e. what is the requirement that makes the storage of the formula here - just for my edification.

2021-05-03 18:47 UTC, hepcat72 commented on DataRepo/tests.py
> +        self.assertEqual(t_peak_group.atom_count("C"), 6)
Q. Since I was just asking about it in another PR, what do we expect to be returned if the formula is null or empty string (since those are possible in the PeakGroup class)?

2021-05-03 18:47 UTC, hepcat72 commented on DataRepo/models.py
> +        # symbols is a tuple of elements in atomic weight order
NB. Atomic number and atomic weight (usually measured in daltons) are 2 different thing.  What composition stores as a key is atomic number.
```suggestion
        # composition returns dict of {atomic_number: count}
        # symbols is a tuple of elements in atomic number order
```

2021-05-03 19:49 UTC, lparsons commented on DataRepo/tests.py
> +        self.assertEqual(t_peak_group.atom_count("C"), 6)
That's a really good question. I don't think we should be allowing blank formula's for a `PeakGroup`, since that doesn't make much sense. I would consider adding a constraint to disallow null and also writing a validator to ensure valid formulas, and adding that to PeakGroup and Compound.

2021-05-03 19:56 UTC, lparsons commented on DataRepo/models.py
> +        return atom_count_in_formula(self.formula, atom)
Since they are one line functions, I feel like the added complexity wouldn't be worth it.

As for storing formula in PeakGroup, that was the topic of a lot of discussion last week (via Zoom). See https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/60#issuecomment-830119154. Basically, PeakGroup is storing the assertion that the researcher is making about the peaks (they are deciding that the peak is likely due to a molecule with the specified formula). Since that molecule may correspond to multiple Compounds, we also store that association as well.

2021-05-03 19:57 UTC, lparsons commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
I was looking for a better way to do that, I'll see if I can find that method and use it, thanks!

2021-05-03 20:03 UTC, lparsons commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
Hmmm. I don't see a way to go from `symbol` to `atomic_number` without directly accessing the `symbols` list. [`atomic_number`](https://bjodah.github.io/chempy/latest/_modules/chempy/util/periodic.html#atomic_number) takes a `name` and returns a `number`. For now, I think I'll have to keep it this way.

2021-05-03 20:04 UTC, lparsons commented on DataRepo/tests.py
> +        self.assertEqual(t_peak_group.atom_count("C"), 6)
For now, it will throw a `ParseException`, which seems reasonable at this point.

2021-05-03 20:28 UTC, hepcat72 commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
I thought all you would have to do is import the atomic_number method from periodic.py:
```
def atomic_number(name):
    try:
        return symbols.index(name) + 1
    except ValueError:
        return lower_names.index(name.lower()) + 1
```
And call it, passing the atom name, e.g.:
```
        count = substance.composition.get(atomic_number(atom), 0)
```
What am I missing?  Can the method not be imported for some reason?

2021-05-03 20:32 UTC, lparsons commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
The `atom_count` method takes a `symbol`. The `atomic_number` function takes a `name`. I see no way to convert between `name` and `symbol` (or `symbol` and `name`) without accessing the `symbols` list directly.

2021-05-03 20:51 UTC, hepcat72 commented on DataRepo/models.py
> +        return atom_count_in_formula(self.formula, atom)
WRT complexity: fair enough. I wouldn't have thought of it as complex, but I agree the duplication is simpler.

WRT `PeakGroup.formula`, I have nothing to comment on that would/should hold up this PR. I admit I was aware that discussion was going on, although I was focussed on other details at the time.  Having reviewed that discussion you linked, I understand it is another storage of a "presumed" value, i.e. a working hypothesis.  Personally, I would probably indicate that in the field name, but that's not an issue for this PR.

But if we're treating it as a link, I wonder if we are controlling the formula values enough for them to actually be links.  There are multiple ways to represent a formula for the same compound, unless we apply some added constraints (e.g. atom order (e.g. CO2H versus HC2O - maybe we're already doing this?), atom uniqueness in the representation (e.g. COOH versus CO2H versus HC2O), formula completeness (e.g. CO2 versus CO2H - sometimes H's are left implied)).  Do we do this validation?

Also, as I understand LC-MS, first, molecules are separated by charge (the LC component), and then separated by mass (the MS component) (depending on the way the separations are done).  John pointed out in that discussion that multiple compounds can have the same m/z ratio - but in the context of PeakGroups, doesn't the formula have more to do with mass than it does with charge?  The PeakGroup is a peak in a MS plot.  In fact, we could validate the chemical formula based on the detected mass (though I don't think we have that).  I'm not sure that I'm familiar enough with the technique/instrument they are using to make a solid case.

But WRT the link - I suspect that the intended utility of having formula in PeakGroup as a link is to be able to link to multiple compounds.  Using the formula for the link seems like a maintenance issue that I'm not sure we're explicitly handling.  Plus, if the point is to link potentially multiple compounds (like citrate/isocitrate), then formula would not support all cases in terms of compounds having the same mass. You can have the same mass and different formulas (although I understand that that's not likely to be the case in the expected data).  I think it effectively works for the expected use-case, but I don't think it is extensible.

2021-05-03 21:01 UTC, hepcat72 commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
Huh.  Well, I assume you know what you're talking about and will leave it up to you, but when I look at the tests, I see atom supplied as a string: `alanine.atom_count("C")`. That string is passed into this surrounding method with `atom_count_in_formula(self.formula, atom)`. I wouldn't understand why you counldn't just import this method:

https://github.com/bjodah/chempy/blob/dd8b934e9f2732d26ba6b5a71e5ee908079bd739/chempy/util/periodic.py#L257

And call it like this:
```suggestion
        count = substance.composition.get(atomic_number(atom), 0)
```
Wouldn't that look up the atomic number of the symbol here?:

https://github.com/bjodah/chempy/blob/dd8b934e9f2732d26ba6b5a71e5ee908079bd739/chempy/util/periodic.py#L9

2021-05-03 21:03 UTC, hepcat72 commented on DataRepo/tests.py
> +        self.assertEqual(t_peak_group.atom_count("C"), 6)
OK, GTK.  Resolving.

2021-05-03 21:08 UTC, hepcat72 commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
Oh wait - I see what the confusion is.  The name of the argument for `atomic_number` is `name` - **BUT** it is doing a lookup in the `symbols` array(?).  And if that gets an exception, it tries to look it up as a name.  I'll admit that's weird.  I hadn't noticed that at first.  But - it should work.

2021-05-03 21:21 UTC, hepcat72 approved these changes
I still feel like you can import and call `periodic.atomic_number` using the symbol, but I assume I'm missing something so: approved.

2021-05-03 21:31 UTC, lparsons commented on DataRepo/models.py
> +        count = substance.composition.get(symbols.index(atom) + 1, 0)
Yup, you're right. Should work. That's a terrible argument name... 🤦 

I'll make that change.

2021-05-03 21:41 UTC, lparsons commented on DataRepo/models.py
> +        return atom_count_in_formula(self.formula, atom)
It is not being used as a link, but instead a record of what the researcher explicitly "stated" during the peak picking process. The link to the compound table is an attempt to standardize the compunds a bit and provide some lookup to HMDB, etc. It's not a perfect model, but it's reasonably close to modeling the information conveyed by the data.

We do not want to use formula as a link since the researchers have used other data to differentiate the compunds with the same mass (retention time on the liquid chromotography column being a major piece of information).

2021-05-03 21:52 UTC, hepcat72 commented on DataRepo/models.py
> +        return atom_count_in_formula(self.formula, atom)
That makes more sense. But having looked at John's accucor loading PR, I thought that `PeakGroup.name` already conveyed what the researcher "stated"/thinks the peakgroup is in terms of compound.  As long as we're not going to treat it like a 1:M link to compound, then if we're simply recording what accucor puts out (relaying what a researcher entered), then I'm not too concerned.  My only concern is that the name of the field doesn't convey anything to indicate it's "presumed". That said, I have nothing further and am resolving this issue.

2021-05-07 13:55 UTC, jcmatese approved these changes

2021-05-07 13:57 UTC, lparsons commented
@hepcat72 Thanks for pushing on the `atomic_number` usage, I read that three time and didn't see that it used the `symbol` despite calling it `name`.

2021-05-07 13:57 UTC, merged