Refactor list templates - part 2
Princeton-LSI-ResearchComputing/tracebase pull request #626
Opened 2023-02-07 17:16 UTC by fkang-pu

## Summary Change Description

- Made changes to the following templates to solve issues with table height and two vertical scrollbars, using the same strategy implemented in [PR602 ](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/602) for study, animal, and sample pages.
 
  - list of tissues
  - peak group sets
  - list of compounds
  - list of infusates

## Affected Issue Numbers

- Resolves #613
- Resolves #614
- Resolves #615
- Resolves #616 

## Code Review Notes

- Used two css files to set table header variables (for tables with long header text to wrap  or  tables with a few columns). Mainly set different height for `<th>` for Bootstrap-table plugin. Will re-visit the css files in the future to see if they can be re-organized.  
-  Would like to get the changes merged into main this week, since the list pages would look better for demo next week.

## Checklist

- [x] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [x] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-02-08 15:58 UTC, hepcat72 requested changes
Overall, I think that this doesn't address the root issue, that being the dimensions of the elements involved.  Hiding the scrollbars may work in your browser(s) on your computer, but it may cause unforeseen issues for someone else.  If the scrollbars are appearing, it means there's a dimensions issue that should be addressed directly.

2023-02-08 15:58 UTC, hepcat72 commented on DataRepo/templates/DataRepo/animal_treatments.html
> +    <script src="{% static 'js/setTableHeight.js' %}"></script>
nb. I could be wrong, but I don't remember reviewing this file.  Either way, I have a few suggestions:

- The method doesn't "set" table hieght.  It "gets" the table height.  (It calculates and returns it.)  It should be named something like "getTableHeight"
- It checks it pctVH is between 0 and 1 (not inclusive) and otherwise scales with a default of 0.75. If an invalid value is submitted, there should be ab error or at least a log message.
- If you want pctVH to have a default, you should check if the value is defined.  If it is not, set 0.75.  (See my `hierarchical_formsets.js` for examples.)
- It uses a magic number for the header height.  This should be a parameter to the method with a default of 120.

2023-02-08 15:58 UTC, hepcat72 commented on DataRepo/templates/DataRepo/compound_list.html
> +<h4>List of Compounds</h4>
nb. To be more succinct...
```suggestion
<h4>Compounds List</h4>
```

2023-02-08 15:58 UTC, hepcat72 commented on DataRepo/templates/DataRepo/animal_treatments.html
> +        let divID = "div_out_tab";
nb. This value (`div_out_tab`) is hard-coded in many files and places.  So I think it should be saved in one place and accessed as a variable.  You can either provide it from the python view code or retrieve it from javascriopt code and save it as a template variable in each template.  Either way, the value should only be hard-coded in 1 place.

2023-02-08 15:58 UTC, hepcat72 commented on DataRepo/templates/DataRepo/compound_list.html
> +    <link href="{% static 'css/bootstrap_table_cus1.css' %}" rel="stylesheet">
nb. `bootstrap_table_cus1.css` as a file name, doesn't well convey what the code is for.  Please rename to something that better conveys what the code is for.

2023-02-08 15:58 UTC, hepcat72 commented on DataRepo/templates/DataRepo/msrun_protocols.html
> +    </script>
nb. This code occurs in a number of places. I would recommend using an `include` that supplies variables for the height and table ID.

2023-02-08 15:58 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
b. I don't think that hiding the scrollbars is a good strategy. Most people's scrollbar settings are set to "automatic". It means that scrollbars appear if they are necessary and disappear if they are not necessary. So if the scrollbars are showing up, it means that there's an element dimensions issue (some contained element is larger than an outer element), like the issue that I fixed in the base html a few months back that was affecting every page.  I haven't run this code, but I can envision cases where scrollbars are necessary, but inaccessible.  Not everyone has a scroll wheel (not on my old backup mouse when my mouse battery dies).  

I would like to see a solution that deals with the root dimensions issue problem.

2023-02-08 16:48 UTC, lparsons commented on static/css/bootstrap_table_cus2.css
> +}
Hmmmm. I guess I misunderstood what was happening in the PR. I agree that hiding the scrollbars is not a solution, and is likely a problem for accessibility. In my testing I didn't see this happening, it seemed that the table height was set correctly. What happens if we remove the CSS that forces the scroll bars to disappear?

2023-02-08 16:53 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
According to the issue description, 2 sets of scrollbars are visible.

2023-02-08 16:55 UTC, lparsons commented on static/css/bootstrap_table_cus2.css
> +}
I thought the table height and scrollbars were at least partially fixed in #602?

2023-02-08 16:57 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
Is that different from #613, or a duplicate issue?

2023-02-08 16:57 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
Honestly, I was a little confused by some of the issue descriptions.

2023-02-08 16:59 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
Oh wait, that's a PR.  That PR says it only partially addressed #613.

2023-02-08 17:02 UTC, hepcat72 commented on static/css/bootstrap_table_cus2.css
> +}
We're not always very good (myself included) about granularizing our issues, so it's hard to say what portion of an issue a PR addresses.  I've gotten into the habit of referencing to-do checklist items in an issue, but usually those kinds of issues are broad in scope, like refactors.

2023-03-28 16:09 UTC, hepcat72 commented
Is this still being worked on?  If not, can we close it?

2023-03-28 16:50 UTC, fkang-pu commented
> Is this still being worked on? If not, can we close it?

Yes, I am still work on it. But I will close it, since my new strategy are quite different from this PR. It's better to submit a new PR when I am ready.

2023-03-28 16:50 UTC, closed without merging