Added an error if units provided are the wrong units
Princeton-LSI-ResearchComputing/tracebase pull request #676
Opened 2023-04-28 22:37 UTC by hepcat72

## Summary Change Description

During the review of a recent PR (#622), it was decided the stripping the units with only a warning was too risky, so I proposed in #666 to only strip "expected" units and otherwise issue an error that stops loading, so that's what this PR does.

While I was at it looking at units, I also added units to the Tracer Concentrations in the web and download templates.  They were already in the FCirc templates, but not the peak groups or peak data, which I believe was an oversight.  I'd gone to look at the website to get the expected tracer concentration units and was surprised they weren't there...

## Affected Issue Numbers

- Resolves #666

## Code Review Notes

Open to suggestions on strictness/flexibility and where to store the expected units that's not too "hard-coded" like it is now.

## Checklist

- [ ] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [x] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [x] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [ ] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-05-02 19:00 UTC, lparsons requested changes
I like the additional functionality, though I don't think there is a need for a warning when expected units are found and stripped and the data is loaded.

2023-05-02 19:12 UTC, hepcat72 commented
> I like the additional functionality, though I don't think there is a need for a warning when expected units are found and stripped and the data is loaded.

I would have agreed with you had I not encountered a case where the warning revealed a problem.  In the cold exposure data, there was a subset of rows where units had been provided.  I think they were correct units, but Michael pointed out that another researcher had added them, but that the numbers were incorrect.

Units are not officially "allowed", which is why I originally made it a warning.  But I'm amenable to allowing "correct/supported" units and removing the warning.  We would have to update the docs WRT the documented format of the columns in the spreadsheet template.

2023-05-02 19:15 UTC, hepcat72 commented on DataRepo/tests/test_exceptions.py
> +        self.assertEqual(una.units_dict, units_dict)
You don't think that modifying their entered value warrants a warning?  I would think that if you don't store exactly what they entered, you should let them know.

2023-05-02 19:16 UTC, hepcat72 commented on DataRepo/utils/exceptions.py
> +            print(f"HEREHERE: {units_dict}")
- [ ] TODO: Remove debug print

2023-05-02 19:18 UTC, hepcat72 commented on DataRepo/utils/exceptions.py
> +                "Units are not allowed."
I think a warning is warranted if you are changing what the user entered.  Say for example, they entered values using `minutes`.  They might try and search the database for a value in that field containing the substring "minutes".  I feel like we should warn them if we are going to change what they entered.

2023-05-02 19:22 UTC, hepcat72 commented
Re-requesting review @lparsons. I added some points of discussion to your blocking issue. Let me know if I've changed your mind.

2023-05-02 19:23 UTC, lparsons commented on DataRepo/utils/exceptions.py
> +                "Units are not allowed."
I'm OK with whichever way you decide to go, but I view this less like we are changing what they provided, but instead, interpreting what they provided. Similar to how we parse dates and then store it in our own format.

2023-05-02 19:26 UTC, lparsons commented
In my opinion, we often interpret what they enter (e.g. dates, compounds, etc.) and store things as appropriate in the database, not as verbatim strings. If you'd like to leave it, that's fine, but let's try to make it clear that we did, in fact, store the value they provided assuming the provided unit. As it reads right now, it almost seems like the data wasn't valid and/or stored.

2023-05-02 19:26 UTC, lparsons approved these changes

2023-05-02 19:57 UTC, hepcat72 commented on DataRepo/utils/exceptions.py
> +                "Units are not allowed."
That's fair.  You convinced me.

- [ ] TODO: No warning when expected units are stripped.

2023-05-08 20:45 UTC, fkang-pu approved these changes
LGTM!

2023-05-09 20:20 UTC, merged