Add ArchiveFile class and basic tests
Princeton-LSI-ResearchComputing/tracebase pull request #715
Opened 2023-07-21 20:09 UTC by lparsons

## Summary Change Description

Create the `ArchiveFile` model class along with basic tests. 

* Uses the Django [FileField](https://docs.djangoproject.com/en/4.2/ref/models/fields/#django.db.models.FileField) for [managing files](https://docs.djangoproject.com/en/4.2/topics/files/).
* Uses basic hardcoded tuples for fields with choices
* Custom [`TestRunner`](https://docs.djangoproject.com/en/4.2/topics/testing/advanced/#defining-a-test-runner) was used to ensure tests with [`FileFields` don't store files that persist across test runs](https://www.caktusgroup.com/blog/2013/06/26/media-root-and-django-tests/).

## Affected Issue Numbers

- Resolves #694 

## Code Review Notes

* Files are stored in the local file system in subdirectories organized by `datatype`
* Django's `FileField` does ensure filenames are unique
* In production we should ensure the `MEDIA_ROOT` is setup on a network drive that is monitored for space utilization and is properly backed up.

## Checklist

- [ ] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [ ] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-07-21 21:42 UTC, hepcat72 commented
Looks like a dependency install failure.  I am seeing the same thing on my template tweaks PR.  My tests locally passed though.

2023-08-01 22:54 UTC, hepcat72 requested changes
This looks like it was quite a cryptic endeavor to get working.  Not only does it create a mechanism for allowing file records, but it also archives the files themselves.  Very impressive. I had a few minor issues/questions/comments, but one thing I'm a bit concerned about is that I don't know whether the file path uniqueness check happens before or after the archive file is written.  We don't check the existence of the file path before attempting to create the record (and thereby write the file).  If the uniqueness check is done before the file is written, we're OK.  If not, then a user with a file with the same name as a previously loaded file could get overwritten. Sorry I didn't look this up myself. It's the end of a pretty long day.

Honestly, it's probably OK.  I can't imagine they'd write the files before committing the atomic transaction.  I just didn't check.

There's also the possibility of accumulating orphaned files due to renaming.

2023-08-01 22:54 UTC, hepcat72 commented on TraceBase/settings.py
> +TEST_RUNNER = "TraceBase.runner.TraceBaseTestSuiteRunner"
C. It took me awhile to find my way to [this doc section](https://docs.djangoproject.com/en/4.2/topics/testing/advanced/#using-different-testing-frameworks) that explains:
> When you run ./manage.py test, Django looks at the [TEST_RUNNER](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TEST_RUNNER) setting to determine what to do. By default, [TEST_RUNNER](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TEST_RUNNER) points to 'django.test.runner.DiscoverRunner'. This class defines the default Django testing behavior.
> ...
> If you define your own test runner class and point [`TEST_RUNNER`](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-TEST_RUNNER) at that class, Django will execute your test runner whenever you run ./manage.py test. In this way, it is possible to use any test framework that can be executed from Python code, or to modify the Django test execution process to satisfy whatever testing requirements you may have.
Now that I understand it, it makes sense, because I didn't see a link between `TraceBaseTestSuiteRunner` and `TestCase` or the settings overrides.

nb. Perhaps link [this doc](https://docs.djangoproject.com/en/4.2/topics/testing/advanced/#using-different-testing-frameworks) above the setting of `TEST_RUNNER`.

nb. Maybe we should create an issue to somehow consolidate the various testing tweaks (overrides, runner, TestCase superclasses?

2023-08-02 15:40 UTC, hepcat72 commented on DataRepo/models/archive_file.py
> +    return f"archive_files/{date_folder}/{data_type_folder}/{filename}"
Perfect. It would be nice if we captured that knowledge in a comment somewhere, but I will mark this as resolved.

2023-08-02 15:42 UTC, hepcat72 commented on DataRepo/models/archive_file.py
> +    )
I see. I still feel like there's potential for ambiguity from a user perspective, but that said, this is a minor non-blocking issue.

2023-08-02 15:49 UTC, hepcat72 commented on DataRepo/models/archive_file.py
> +    data_format = models.ForeignKey(DataFormat, on_delete=models.CASCADE)
nb. OK, creating an issue is good.  Wasn't `PROTECT` supplanted by `RESTRICT`? I don't think(?) `PROTECTED` is deprecated, but I recall that `RESTRICT` was added after `PROTECTED` in order to conform to DB conventions and is equivalent (an alias?). TBH, I don't know if one is preferred over the other, but that's the sense I vaguely recall from my last perusal of the docs.

nb. Also, if we are intentionally leaving orphans, and we would get errors about pre-existing files, I think packaging that exception to suggest a resolution would be helpful.  Otherwise, we should create an issue to document our process for handling that error.

2023-08-02 16:04 UTC, hepcat72 commented on DataRepo/models/archive_file.py
> +    data_format = models.ForeignKey(DataFormat, on_delete=models.CASCADE)
OK.  So they are different.  I hadn't dug into it.  I just recalled a section about why restrict was added.

2023-08-02 20:40 UTC, fkang-pu approved these changes
Overall, it looks fine to me. Here are  a couple of comments you can consider or ignore. 

- Django 4.2 has a new feature [InMemoryStorage](https://docs.djangoproject.com/en/4.2/ref/files/storage/). I am wondering if it could simplify some of the tests using temp. storage in this PR.  Upgrade Django first?
- column "`code`" in  `DataType` and `DataFormat` is for short names stored in database. Alternatively, we  could use "symbol", similar to symbols used for genes.

2023-08-03 15:09 UTC, hepcat72 approved these changes

2023-08-03 18:00 UTC, jcmatese approved these changes
Let's try it out.  I only saw potential typos and a question on the "approved" field for long descriptions/texts.

2023-08-03 19:48 UTC, lparsons commented on DataRepo/fixtures/data_formats.yaml
> +    description: "IsoCorr13C15N format peak data from a mass spectrometery run"
No, I spelled it wrong, good catch @jcmatese.

2023-08-03 19:49 UTC, lparsons commented on DataRepo/models/archive_file.py
> +    )
I think a `TextField` would be preferred here. Somehow I didn't think Django had those, but I'm not sure why I thought that. Thanks.

2023-08-03 19:52 UTC, lparsons commented on DataRepo/models/archive_file.py
> +    return f"archive_files/{date_folder}/{data_type_folder}/{filename}"
> Q: Should we slugify the filename?

I think that's probably wise.

2023-08-03 20:33 UTC, merged