Add LCMethod model with basic tests
Princeton-LSI-ResearchComputing/tracebase pull request #717
Opened 2023-07-26 20:16 UTC by jcmatese

## Summary Change Description

Adds basic LCMethod class, migration, and rudimentary tests

## Affected Issue Numbers

- Resolves #702 

## Code Review Notes

- I don't know about the decorator `@override_settings(CACHES=settings.TEST_CACHES)`, but since it was similar to `Protocol`, I added it

~~Take a look at the enumeration methodology and constraint (see `Meta`).  [One example I saw](https://docs.djangoproject.com/en/4.2/ref/models/fields/#enumeration-types) had a class-within-a-class to do this, but I made it a distinct external class `ChromatographicTechniqueChoices`~~

~~Also added a unique constraint on essentially the collection of columns (see `Meta`)~~

- I have _no_ idea on the delete order for LCMethod, but I slotted it in
- NOTE: the migrations will have the same 0009 prefix as PR #715 , so you might want to rebase one or the other, after the first one gets merged (and make migrations again?)
- I did not add this to the *Unreleased* section of `changelog.md` , because I did not see that section.  Perhaps it needs to be added back?

## Checklist

- [ ] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [ ] All issue requirements satisfied (or no linked issues)
- [x] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [x] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-07-26 22:55 UTC, jcmatese commented
@fkang-pu you might be interested with the constraints I made, and how they end up propagating into the Postgres database

2023-07-27 18:43 UTC, hepcat72 requested changes
This PR is true to the issue description and well implemented. It includes some added nifty coding patterns that edified me and I appreciate that.  I do have a few blocking issues that are mainly design issues.  I think that this issue could have benefitted from a design review.  There are other non-blocking minor issues that can be ultimately ignored, but I would like to see a little extra checking of the exceptions in the tests.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    )
b. I'm open to discussing this, but in my opinion, `run_length` belongs in either a linking table or at least, some other table with an M:1 relationship with this table (a quick fix would be to put it in the table that links to this one).  Correct me if I'm wrong, but I would imagine that different runs using the same method could go different run lengths, possibly depending on sample size perhaps, or some other determinant. That possibility would create overhead in maintaining the consistency of the description and/or technique (if variations of a technique are added in the future). It would also cause searching/linking/stats problems. An experiment linked to one method with a different run time than that method's entries could cause a user to not be aware of other runs with the same method but different times.

Alternatively, if run-length is not precise, but significant run length differences tied to individual discrete techniques could be bucketed, then another solution would be to make this an enum field like short/medium/long.

And I do apologize. This is a design issue, and not the fault of the issue owner. We had discussed these models holistically and I did not catch this issue in that context. This would have benefitted from a design review where a line-by-line review could have drawn this issue out earlier in the software engineering process and thus reduced the amount of overall work to fix.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +        ]
nb. `method` and `technique` appear to be used interchangably, spanning the class name, fields, choices variable names, meta values, etc.  I think one should be used consistently, whether it's `method` or `technique`.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +                name="%(class)s_record_unique",
Q. This is probably a dumb question, but I am unfamiliar with the usage/meaning of `%(class)` in a string and I cannot find it in the docs (perhaps just due to inadequate search terms).  We have not used it in any of the other uniqueconstraint settings before, so I'm curious about it's usage here. Is this like a template pattern where `LCMethod` is inserted?

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +            ),
C. Neat.  I didn't know about `CheckConstraint` before. Thanks for the edification!

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +                name="%(class)s_technique_valid",
nb. I might make this a tad more descriptive, based on the examples I saw in the docs.  Perhaps `technique_in_choices`?

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +            ),
Q. What's the determining factor that puts this in a `CheckConstraint` versus a `validator` in the field definition (like the max/min validators)?

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    OTHER_TECHNIQUE = "Other", "Other"
nb. `_TECHNIQUE` seems a bit redundant given the class name. Consider removing it.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    OTHER_TECHNIQUE = "Other", "Other"
b. `LCMethod. chromatographic_technique` is saved using these values.  Having `Other` as a unique key and a freeform description in the `LCMethod` record is problematic.  The first one in creates a description that is thus applied to ever other LCMethod record where `Other` is selected, which will definitely lead to incorrect association of that description to subsequent `LCMethod` records.  This design of implementing the enumeration will not work.  Either nomenclature/choices/enumerations need to be managed in a different way, or `Other` will have to be removed. Removing `Other` could be a quick short-term solution that could kick the can down the road to the input method, where other could be allowed, and would prompt a back and forth between the user and the curator to add a new method to the codebase.  Another option would be to change this to something negative, like "not listed", in which case, we would either disallow a description or have a canned value that says something about talking to the user.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        self.default_t_chromatographic_technique = (
Q. This prompts a question... Should `LCMethod.chromatographic_technique` be defining a default?

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        _, created = LCMethod.objects.get_or_create(
C. Cool. I don't know if I ever noticed this before, but using `_` as a "junk" value is something I never thought of. We should probably establish this as a good practice/convention. I know I'd used arbitrary variable names in the past.  E.g.:
```
DataRepo/tests/test_formats.py:        (qs, junk1, junk2) = sg.performQuery(fmt=format)
```

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +        with self.assertRaises(IntegrityError):
Q. Is unique constraint violations the only type of integrity error? I don't think it is, so...

nb. Please check the content of the exception to ensure it's a unique constraint violation.

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +            _ = LCMethod.objects.create(
nb.
```suggestion
            LCMethod.objects.create(
```

2023-07-27 18:43 UTC, hepcat72 commented on DataRepo/tests/test_models.py
> +            )
nb. Check the content of the exception to be sure it is what you're assuming.

2023-07-27 19:33 UTC, lparsons commented on DataRepo/models/lc_method.py
> +    MAXIMUM_VALID_RUN_LENGTH = timedelta(days=1)
Quick comment here, as we discussed with @mneinast, the "Run Length" is part of the method definition. An example method used previously is "HiLic_25min". Thus, this should be part of the class and not in a separate class/table, imo.

2023-07-27 19:34 UTC, lparsons commented
> I do have a few blocking issues that are mainly design issues. I think that this issue could have benefitted from a design review.

As we discussed in the meeting on Monday, this IS the design review.

2023-07-27 20:07 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    MAXIMUM_VALID_RUN_LENGTH = timedelta(days=1)
GTK.  Thanks.  I will edit affected issues I created.  Do we know if it's technically possible to run over 24h?

2023-07-27 20:18 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    )
Lance pointed out that the run length is specific to the method.  I.e. it constitutes a significant method difference.  I am going to change this issue to non-blocking.  I would change it to resolved except that I don't understand the significance of the difference between, for example, hilic 25m and let's say hilic 20m. And is an over-run of 25m to 26m possible (e.g. by inattention), and if so, is it significant? Also, if querying for all hilic (or other) methods (regardless of run length) has any conceivable value, like let's say a user wants to find data associated with any hilic method, then the query is a bit more complex than getting related table records linked to a single record and I'm not sure a user would instinctively know to do that... I just don't know enough to predict the likelihood of the use-cases.

2023-07-27 20:27 UTC, hepcat72 commented
> > I do have a few blocking issues that are mainly design issues. I think that this issue could have benefitted from a design review.
> 
> As we discussed in the meeting on Monday, this IS the design review.

Fair enough. I think the change is small enough that that's a reasonable strategy. And given my concern about `run_length` was previously considered, it seems that it pans out. The concern over the `Other` value could require a bigger change than might have been anticipated, but we'll see. Perhaps I'm wrong about that too, or it's fix could turn out to be simple. I was thinking about it during my late lunch and I thought that maybe if we set `null=True` and disallow a user-supplied description, that could be an easy fix as well.

2023-07-31 14:07 UTC, fkang-pu commented
> @fkang-pu you might be interested with the constraints I made, and how they end up propagating into the Postgres database

FYI.
query the database for this model (table: "DataRepo_lcmethod"):
```
         Column           |          Type          | Collation | Nullable |                     Default                     
---------------------------+------------------------+-----------+----------+-------------------------------------------------
 id                        | integer                |           | not null | nextval('"DataRepo_lcmethod_id_seq"'::regclass)
 chromatographic_technique | character varying(256) |           | not null | 
 description               | text                   |           |          | 
 run_length                | interval               |           | not null | 
Indexes:
    "DataRepo_lcmethod_pkey" PRIMARY KEY, btree (id)
    "DataRepo_lcmethod_chromatographic_technique_1592bc73_like" btree (chromatographic_technique varchar_pattern_ops)
    "DataRepo_lcmethod_chromatographic_technique_key" UNIQUE CONSTRAINT, btree (chromatographic_technique)
    "lcmethod_record_unique" UNIQUE CONSTRAINT, btree (chromatographic_technique, description, run_length)
Check constraints:
    "lcmethod_technique_valid" CHECK (chromatographic_technique::text = ANY (ARRAY['HILIC'::character varying, 'Reverse Phase'::character varying, 'Other'::character varying]::text[]))

```

2023-07-31 17:54 UTC, jcmatese commented
going to convert this back to Draft, and make some edits based on developer meeting discussion...

2023-07-31 18:18 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +    MAXIMUM_VALID_RUN_LENGTH = timedelta(days=1)
While it is _technically_ possible for a sample to (not) run over 24 hours, in practice, I doubt runs would _regularly_ go even over an hour, never mind 24 hours.  I will see if @mneinast or Wenyun can comment on the longest run time they can remember.  I did a brief search , and could not find any examples exceeding a day [[1](https://www.researchgate.net/post/What_is_the_maximum_RT_in_RP-HPLC)] .  The thought has to prevent possible errors in an admin or loading interface (just setting common sense heuristic limits/windows), but if people think it is problematic, I can remove it.  Generally, [metabolic Cores are pushing to run >50 samples a day](https://www.pnas.org/doi/10.1073/pnas.2301215120?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed#sec-3), not <1.

2023-07-31 18:24 UTC, jcmatese commented on DataRepo/tests/test_models.py
> +        _, created = LCMethod.objects.get_or_create(
I am indifferent about it, but I think some linters complain about naming/defining a variable, and then not using/referencing it later.  This `_`/junk convention bypasses those complaints.   [but you won't find **_me_** complaining about it, personally]

2023-07-31 18:33 UTC, lparsons commented on DataRepo/tests/test_models.py
> +        _, created = LCMethod.objects.get_or_create(
Using underscores is a standard convention: https://docs.python.org/3/tutorial/classes.html#private-variables

2023-08-01 14:20 UTC, mneinast commented on DataRepo/models/lc_method.py
> +    MAXIMUM_VALID_RUN_LENGTH = timedelta(days=1)
I think a 24 hour max run length is reasonable.  I am not aware of anyone running a single sample longer than a few hours.

2023-08-01 14:36 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +    MAXIMUM_VALID_RUN_LENGTH = timedelta(days=1)
OK. Resolving. Let's keep the max.

2023-08-01 18:02 UTC, lparsons reviewed
I believe there are some additional changes pending for this PR to remove the "Choices" class since we decided this table itself will define the controlled vocabulary. However, I did review the rest and it looks great so far.

2023-08-01 18:02 UTC, lparsons commented on DataRepo/tests/test_models.py
> +        with self.assertRaises(IntegrityError):
Something like:
```python
    with self.assertRaises(IntegrityError) as ie:
         LCMethod.objects.create( ... )
     self.assertEqual(str(ie.exception), 'Unique constraint violation...')
```

2023-08-01 19:02 UTC, jcmatese commented
Office discussion among @lparsons and @fkang-pu suggested that we should add a unique `name` attribute and make `description` unique by itself (which might make the additional multi-column unique constraint redundant)

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +      temperature 4°C, injection volume 10 µl, and column temperature 25°C.
Waiting on some feedback from Wenyun, but there will likely be model changes (name), and potentially different records for methodologies that are less defined as these example (e.g. everything we currently have in Tracebase)

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +    id = models.AutoField(primary_key=True)
Add a name attribute, unique max_length=256, blank=False, null=False

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +        max_length=256,
rename `chromatographic_technique` to `type` , and make field shorter length?

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +    )
Make unique?

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +            ),
Drop constraint if name and description are made unique.

2023-08-01 19:19 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +        return self.chromatographic_technique
If we add name, then this logic must change to accommodate.

2023-08-01 19:20 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +            ),
Hmmm, that seems potentially better than a validator, in that the constraint is created in the database as opposed to just in the python object.  If I understand it correctly, it seems like it would protect us from invalid changes at the DB prompt, and from raw SQL statements created in python code.  Maybe we should be doing this for the min/max validators as well?

2023-08-01 19:26 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +            ),
I definitely had this bite me today, because if you bypass the `full_clean` route, but just call `create` without a defined attribute (in my case, a `TextField` `description`, in tests) , Django will happily convert that to an empty string and insert it into the database without error, despite model specifications of `null=False, blank=False`

2023-08-01 19:27 UTC, hepcat72 commented
> Office discussion among @lparsons and @fkang-pu suggested that we should add a unique `name` attribute and make `description` unique by itself (which might make the additional multi-column unique constraint redundant)

So that would be?:
- chromatographic_technique
- run_length
- name
- description

I'd be OK with that.

2023-08-01 19:28 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +            ),
Had to add this because it was possible to circumvent `description` being meaningful content by using `create`

2023-08-01 19:28 UTC, lparsons commented on DataRepo/models/lc_method.py
> +            ),
Personally, I like having some constraints controlled by db and others in in code. Sometimes, rules need to be broken and having that flexibility and separation in the code can be very nice. Regardless, let's not go making changes to things right now. We need to keep our eye on the prize and get datasets with mzXML files stored in TraceBase before too many more experiments get completed and not uploaded.

2023-08-01 19:30 UTC, jcmatese commented
> > Office discussion among @lparsons and @fkang-pu suggested that we should add a unique `name` attribute and make `description` unique by itself (which might make the additional multi-column unique constraint redundant)
> 
> So that would be?:
> 
> * chromatographic_technique
> * run_length
> * name
> * description
> 
> I'd be OK with that.

Yes, although I would also lean towards renaming `chromatographic_technique` to `type` (e.g. `lcmethod.type`)

2023-08-02 21:01 UTC, jcmatese commented
OK, feel free to take it from here (I could live with this into short term).

2023-08-03 12:27 UTC, mneinast commented
I like the 4 suggested fields for LC.

2023-08-03 15:56 UTC, lparsons approved these changes
I really like the use of the `name` column, I think it adds a lot of clarity and flexibility. The constraints are implemented in a nice way too.

NB: Consider using the [`natural_key` and `get_by_natural_key` methods](https://docs.djangoproject.com/en/4.2/topics/serialization/#topics-serialization-natural-keys) used in #715 so we can avoid having to specify (and export) the `pk` field in the fixtures (and when serializing the objects).

2023-08-03 15:56 UTC, lparsons commented on DataRepo/fixtures/lc_methods.yaml
> +    name: "HILIC-25min"
NB: Consider adding some additional text to the name to clarify that this is an "unspecified" or otherwise less defined method. Perhaps `HILIC-25min-nonspecific`? @mneinast Thoughts? (same for the reverse phase below).

2023-08-03 16:42 UTC, hepcat72 approved these changes
John, I frequently learn new things when reviewing your code, so thanks for that. And I greatly appreciate the thought and effort you put into these changes. I no longer have any blocking issues, so I am approving, though there are some changes that I think would be good to make in the new code. Take a look and please consider addressing my new issues if you think they have merit.

2023-08-03 16:42 UTC, hepcat72 commented on DataRepo/fixtures/lc_methods.yaml
> +  pk: 1
Q. I believe existing fixtures may have already specified `pk` values and I probably approved those PRs, but given my experience with AutoFields WRT primary keys and copying records in Django, it occurs to me that either Django fixture handle this implicitly or it could represent a potential problem. I wasn't able to find any documentation that addresses this, so I am creating this issue as a question.

In a record copy (as I experienced with the validation database awhile back), Django's tracking of the "next ID" in an autofield does not keep track if you explicitly enter a value for a primary key.  Then the next time you go to add a record (relying on AutoField to create a new ID, you hit a uniqueness error.

So either fixtures DO keep the autofield up to date or any additional records will hit an error since we explicitly set the `pk` value here.

I did find a blog post that suggested you could leave ok `pk` in the fixture in the case of an `AutoField`. Do people think it would be safer to *not* set a `pk` value? Do fixtures *require* a `pk` value or can anyone confirm that AutoFields work correctly when fixtures with `pk` values are already added? I couldn't even find an mentions about this in the docs.  I could assume it would work, but I'd prefer to know for a fact it does.

2023-08-03 16:42 UTC, hepcat72 commented on DataRepo/migrations/0009_LCMethod_addition.py
Still would like to see the changelog updated.

2023-08-03 16:42 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
nb. This is a clever way to handle disallowing empty strings at the database level (as compared to `blank=False` which only applies to forms) and it taught me something I didn't know, which is always cool.  But in this case, there's a simpler way to do this that is less obscure, simpler, and more straightforward.

Instead of using this in your `CheckConstraint`:
```
models.Q(type__length__gt=0)
```
You can do this instead, which doesn't require any special setup:
```
models.Q(type__ne="")
```

In fact, we should probably add checks like this to other models/fields.  I think the effort to do this check is great.  I just think a little tweak can improve it.

2023-08-03 18:13 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +    name: "HILIC-25min"
I went with that name to more-or-less match the string for previously submitted studies' `msrun_protocol`s, the submission template ("Hilic25min"), and what the researchers _seem_ to communicate most commonly.  I am not against changing the name, though, if people think it would be more accurate, and perhaps encourage the creation of "specific" records.

2023-08-04 12:56 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
Tried it.  Got
```
raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'ne' for CharField or join on the field not permitted.
```
reverting back, because I don't have time to fool around with this, today.  There is a strong likelihood that someone is going to have to pick up both this PR and the rabinowitz-draft-data PR, because my day is completely booked (might have to take a complete vacation day), and I leave for a week's vacation next Monday.

2023-08-04 13:10 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
I forgot. `ne` doesn't exist. You have to do `~models.Q(name="")` or `~models.Q(name__exact="")`. I double checked in the docs. `exact` is the default. You just have to negate the Q expression with the tilde.

2023-08-04 13:12 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
All of the possibilities are listed here: https://docs.djangoproject.com/en/4.2/topics/db/queries/#field-lookups

2023-08-04 14:37 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
ok, I can try that

2023-08-04 14:40 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +models.TextField.register_lookup(Length)
Cool. If there are some other coding efforts you could use a hand with, let me know. I need to fix some new bugs in an ATAC Compendium PR I edited yesterday, but that shouldn't (I hope) take too long.

2023-08-04 16:48 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +  pk: 1
I am not against it.  I don't have much experience with fixtures, and how they might work for us if we want to go back and edit the names/descriptions.  With the pk included, this works without issue (seemed to me), but I don't know if the pk is not included.  I am going to postpone changes to the fixture and the @lparsons suggestions "NB: Consider using the [natural_key and get_by_natural_key methods](https://docs.djangoproject.com/en/4.2/topics/serialization/#topics-serialization-natural-keys) used in https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/715 so we can avoid having to specify (and export) the pk field in the fixtures (and when serializing the objects)."  Until we can vette the content, see how the related data migrations might occur, and test those possible issues (name or description tweaks, requested by developers/researchers).  I just don't have time for this today, and I **_really_** want to hand this off before I become unavailable.

2023-08-04 17:40 UTC, merged