Modify initial lcmethod fixture
Princeton-LSI-ResearchComputing/tracebase pull request #731
Opened 2023-08-16 16:57 UTC by jcmatese

## Summary Change Description

Updated inital fixture records' attributes
Updated lcmethod model to name as a natural key
Updated lcmethod model name description for new fixture Updated lcmethod model type description for new fixture New migration updates attribute descriptions
New migration updates deletes and reloads lcmethods

## Affected Issue Numbers

- Resolves #728 

## Code Review Notes

For data review, this has seen the eyes of Wenyun, Michael, and @lparsons already, but if anyone has concerns/preferences on dash-filled lcmethod.names or lcmethod.types, speak up.

For code review, there is not _too_ much changed, but I did experiment with deleting and loading lcmethods records within the migration (the thought was to "reset" the table).  There may be unpredictable (by me) ramifications to this.  For example, when I initially ran the tests, it complained that the "unknown" protocol already existed, presumably because test runs all the migrations (including this migration that loads the preset lcmethods).

## Checklist

- [ ] Changes have been added to the *Unreleased* section in the [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
- [ ] All issue requirements satisfied (or no linked issues)
- [ ] [Linting passes](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
- [ ] [Migrations created & committed *(or no model changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)
- Tests
  - [ ] [Tests implemented *(or no code changes)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [ ] All example load tests pass (remotely) *(or their failures predated and are unrelated to this branch)*

2023-08-16 17:56 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar
C: Just noticed the name and descriptions (included name) differs. Which raises the question(s):

1. should we include the quoted names within the description?
2. if so, should we also match the exact string/case?

2023-08-16 17:56 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +      “Lipid-Reversed-phase-HRMS”: this method involves the analysis of lipids
C: same as above

2023-08-16 19:20 UTC, jcmatese commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +    ]
C: Once again, this dependency would be in conflict with PR #727 , and would have to be updated if that once is merged first (rebase, or something...)

2023-08-16 20:00 UTC, hepcat72 requested changes
This faithfully implements the issue, though I'm tentatively requesting changes due to the fixture load that happens independent of existing data.  If the database is empty, I wouldn't expect a migration to add data. It's not required, but I would also like to see smart quotes replaced with regular quotes for search-ability.  Everything else is at your discretion.

2023-08-16 20:00 UTC, hepcat72 commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-HILIC-HRMS”: this method involves the analysis of polar metabolites
nb. This uses "smart quotes", e.g. `“` versus regular quotes, e.g. `"`.  Regular quotes will be more searchable.  I suggest searching and replacing all smart quotes with regular quotes.

2023-08-16 20:00 UTC, hepcat72 commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar
nb. It's redundant data. I feel pretty strongly that it should not be reiterated in the description, but the only issue is added overhead due to changes and I don't expect this to *likely* change. However, removing it will ensure data consistency should we ever refactor.

2023-08-16 20:00 UTC, hepcat72 commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
b. I could be missing something, but I'm tentatively marking this as blocking just in case. I know there was a previous PR where a migration created `ArchiveFile`(?) records using the data from `PeakGroupSet`.  In that instance, a "load/insert" in a migration makes sense, but I feel like loading fixtures in a migration independent of the removal goes beyond the concept of a migration.  My instinct tells me that a migration should essentially convert existing data.  I think that if a specific old record exists, it should be deleted and replaced by its new version.  If it doesn't exist, there should be no insert/load.

It might be safe to assume that if any records are present, all are present, so perhaps there's a way to obtain the number of deleted records to use to decide to do the load.

2023-08-16 20:00 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +        """Allows Django to get objects by a natural key instead of the primary key"""
nb. I think Lance told me what "natural key" was a week or so ago, but ATM, I cannot remember. I think having a docstring is great, and since this is essentially the definition(/override) of a required(?) abstract(/super) class method, a docstring isn't technically even necessary (because it can be looked up), but maybe substitute "natural key" with something that better conveys the purpose.  I know that would help me.

2023-08-16 20:15 UTC, jcmatese commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
well, if people prefer, I can remove the load aspect, and modify delete aspect to target the specific names.  Alternatively, all of this was just convenience, so if people object to it, I can remove it all and people can manage their own database data (since none of this is in actual staging/production or code-usage). It would just get moved to another PR, I guess (issue #703)

2023-08-16 20:24 UTC, hepcat72 commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
Or... if you go with the assumption I suggested (to keep it simple), you can use a conditional in a single method:
```
def update_lc_methods(apps, schema_editor):
     if LCMethod.objects.all().delete() > 0:
        call_command("loaddata", "lc_methods", app_label="DataRepo")
```
And call that one method:
```
migrations.RunPython(update_lc_methods)
```

2023-08-16 20:28 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +        key reference to objects of the type that defines the method.
I don't think my question even makes any sense, re-reading it. 🤷🏼‍♂️

2023-08-16 20:31 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +        """Allows Django to get objects by a natural key instead of the primary key"""
Maybe it does... Maybe that's what allows the fixture to have the pk value absent and what keeps the autofield up to date?

2023-08-16 20:33 UTC, jcmatese commented on DataRepo/models/lc_method.py
> +        key reference to objects of the type that defines the method.
my aforementioned "test" of serializer behavior that makes me question what a pk/natural_key get exported, in this model anyway:
 ```
$ ./manage.py shell
Python 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from DataRepo.models import LCMethod

In [2]: from django.core import serializers

In [3]: data = serializers.serialize("yaml", LCMethod.objects.all())

In [4]: print(data)
- model: DataRepo.lcmethod
  pk: 10
  fields:
    name: lipid-reversed-phase-25-min
    type: lipid-reversed-phase
    description: '“Lipid-Reversed-phase-HRMS”: this method involves the analysis of
      lipids using reversed-phase chromatography on C18 columns, coupled with high
      resolution mass spectrometry. It is mainly used for the analysis of lipids.'
    run_length: 00:25:00
```

2023-08-17 15:37 UTC, fkang-pu approved these changes

2023-08-17 15:37 UTC, fkang-pu commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
I need a bit time to study/think about how to use fixtures. To my understanding, fixtures are only for loading data into empty models (tables). In a long run, `LcMethod `(`DataFormat` and `DataType` as well) data need to be managed like compounds and tissues - load the list (get_or_create, or raise error for conflicting record). If a lc_method record is already referenced in a child table, delete/reload wouldn't work.

2023-08-17 16:10 UTC, lparsons requested changes
This looks good, but I would like to see two things addressed before merging:
1. Avoid the use of fixutres and avoid adding data to a database during migration. Migration should update existing records only.
2. Remove the redundant quoted string in the descriptions. I don't think they clarify things, they are really just a leftover from me not cleaning up the email communications well enough.

2023-08-17 16:10 UTC, lparsons commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-HILIC-HRMS”: this method involves the analysis of polar metabolites
I concur with @hepcat72, all "smart quotes" should be avoided. Though, I probably vote for removing them all entirely (see below).

2023-08-17 16:10 UTC, lparsons commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar
I would vote for removing the quoted strings in the descriptions entirely. I had tried to make things more consistent from the various emails from Wenyun, but seeing it all together now those seem entirely redundant and not particularly useful.

2023-08-17 16:10 UTC, lparsons commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
B: I don't think this is how data migrations are intended to work. They should only do something if there is existing data in the database. In practice, for TraceBase, this would mean that they are run only once and probably won't even run on production data since we'll want to reload data in order to capture the archive files upon loading. I would suggest a function that loops over existing records much like the migration in #727 .

2023-08-17 16:10 UTC, lparsons commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
From my understanding, the fixtures should be entirely separate from the migrations.

2023-08-17 16:10 UTC, lparsons commented on DataRepo/models/lc_method.py
> +        """Allows Django to get objects by a natural key instead of the primary key"""
The main goal of using a [natural key](https://en.wikipedia.org/wiki/Natural_key) for me was to avoid having to specify the id on the fixture. I haven't had the chance to test the serialization code, but Django does document that. IMO, ["natural key" is standard term](https://en.wikipedia.org/wiki/Natural_key) and should be used. Also, I believe this method name is used by Django, so we don't have the liberty to change it.

2023-08-17 16:13 UTC, hepcat72 commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar
I think that if we want the name to be a part of the description, we handle that in a template as opposed to in the database record, meaning they would only ever be combined when presenting the data to the user in the interface. But even then, I think they should be presented as distinct field values so that a user doesn't think they can use a search string for the description that includes the name.

2023-08-17 16:16 UTC, jcmatese commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
The only thing this would effect is developer that have run the fixture, and you have old records in their databases.  If we agree those cases do not matter, I will just remove all that remove/load code.  It is not really a data migration, _per se_.

2023-08-17 16:17 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-HILIC-HRMS”: this method involves the analysis of polar metabolites
I will just remove all names and quotes from the descriptions.  Problem solved...

2023-08-17 16:38 UTC, hepcat72 commented on DataRepo/models/lc_method.py
> +        """Allows Django to get objects by a natural key instead of the primary key"""
Thanks for the wiki link. So this is starting to make some intuitive sense to me. A natural key is a key that's used in the real world (like an accession). I don't think it's related to the primary key at all. `natural_key()` sets some field as a key... to be used as the record's foreign key in other models using `get_by_natural_key()`? That would mean that the only foreign key references we would need to worry about breaking is changes to the name field... assuming that calling `natural_key()` changes those foreign keys implicitly...

2023-08-17 19:32 UTC, jcmatese commented on DataRepo/fixtures/lc_methods.yaml
> +      “Polar-Reversed-phase-HRMS”: this method involves the analysis of polar
removed

2023-08-17 19:32 UTC, jcmatese commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
removed

2023-08-17 19:33 UTC, jcmatese commented on DataRepo/migrations/0012_lcmethod_fixture_update.py
> +        migrations.RunPython(load_lc_methods_fixture),
removed

2023-08-17 20:41 UTC, hepcat72 approved these changes
💯

💁🏻 OK, so [this](https://gist.github.com/rxaviers/7360908) is how Lance apparently adds the squirrel in the fedora... It's at the bottom. :godmode:

2023-08-17 22:52 UTC, lparsons approved these changes
:shipit: 

[On GitHub, what is the significance of the "Ship It" squirrel?](https://www.quora.com/On-GitHub-what-is-the-significance-of-the-Ship-It-squirrel#:~:text=Someone%20in%20the%20GitHub%20community,originally%20shared%20as%20a%20tweet.)

2023-08-18 01:02 UTC, merged