Issue 696 use archivefile
Princeton-LSI-ResearchComputing/tracebase pull request #733
Opened 2023-08-17 18:59 UTC by lparsons

## Summary Change Description

Display data from `ArchiveFIle` instead of `PeakGroupSet`. Since the loading code still loads into `PeakGroupSet`, after this PR, new data won't be able to be added until #697 is completed. In the meantime, having a database at migration `0012` and then migrating to `0013` will provide data to test this code.

## Affected Issues/Pull Requests

- Resolves #696

## Review Notes

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in the affected "resolved" issues are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting).
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] Added changes to *Unreleased* section of [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md).
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2023-09-27 19:26 UTC, hepcat72 requested changes
This PR replaces usage of PeakGroupSet with ArchiveFile in the views and models.  The code overall looks workable/good.  None of my issues are blocking, but there are some issues I would prefer to see addressed.

The "Request Changes" status of this review relates primarily to the following issue:

b. `Conflicting migrations detected` error in the tests.

Please also:

nb. Update the change log
nb. Comment on the failing tests in the PR description, if there are any associated with these changes (and comment on the migrations error if that is expected)

2023-09-27 19:26 UTC, hepcat72 commented on DataRepo/formats/peakdata_dataformat.py
C. We should probably create an issue to add the date time stamp for searching, which means I would have to add support for date/time comparisons.

2023-09-27 19:26 UTC, hepcat72 commented on DataRepo/templates/DataRepo/search/results/peakdata.html
> +                    <!-- Archive File Filename-->
nb
```suggestion
                    <!-- Archive File Filename -->
```

2023-09-27 19:26 UTC, hepcat72 commented on DataRepo/urls.py
> +] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
Q. Does this allow users to browse everything under `/archive`?

2023-09-27 19:26 UTC, hepcat72 commented on DataRepo/views/models/peakgroup.py
> +    ordering = ["msrun_id", "archive_file_id", "name"]
C. I'm not sure I recall why we're ordering by IDs.  Might be a good reason for it.  This is what is default-used for views, so the order will appear arbitrary to users (roughly by load order).  If we load by `["msrun", "archive_file", "name"]`, if I recall correctly, it will default to the `ordering`s specified in those related models. I could be wrong though.

2023-09-27 21:03 UTC, lparsons reviewed
Thanks for the helpful comments. Sorry about the test errors and conflicts, I accidentally requested the review prematurely, the PR was still in draft. I'm taking it out of draft now and responded to your comments, ready for a re-review.

2023-09-27 21:03 UTC, lparsons commented on DataRepo/views/models/peakgroup.py
> +    ordering = ["msrun_id", "archive_file_id", "name"]
I'm not making any meaningful change here, but I agree with your overall assessment here. Would make sense to perhaps order by date and/or name, but I'll leave that for a separate issue.

2023-09-27 21:25 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> +        on_delete=models.CASCADE,
These 2 statements seem at odds:

This one suggests it's about when PeakGroup records are deleted:

> Having `on_delete=CASCADE` here means that if the archive file record is deleted, the associated PeakGroups would also be deleted.

And this one suggests it's about when `ArchiveFile` records are deleted

> we could consider using `RESTRICT` (or `PROTECT`) if we want to force the deletion of every PeakGroup before removing the `ArchiveFile` record.

This is the same directionality confusion I always have about `CASCADE` versus `RESTRICT` or `PROTECT`.  If it's about cascade-deleting all `PeakGroup` records that link to it when an `ArchiveFile` record is deleted, I would not allow that `CASCADE`.  But I think your second description is right.  We should use the setting that says that the `ArchiveFile` record is only deleted when everything that links to it has been deleted.

> In practice, I don't think we'll use this much unless and until we use the Admin interface.

That's fair.  You're right, this won't be used in the current code, but making sure this would behave the way we would want if we do start allowing edits will make things easier.

2023-09-27 21:27 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> +        help_text="The data file from which this PeakGroup was imported.",
No, you're right.  I had the model flipped in my head when I looked at this.

2023-09-28 21:25 UTC, hepcat72 requested changes
Given a response in the last review, that archive file will, (confirming what I'd thought), hold multiple file types, I think the field name and other references to that field, should be more specifically named, to facilitate transparency and searching.

2023-09-28 21:25 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> +        on_delete=models.CASCADE,
nb. OK.  I think that the relationship should be `RESTRICT`.  I think `RESTRICT` will allow the delete to proceed if the operation triggering the delete includes all `PeakGroup` records that link to the archive file record.  This is non-blocking because I know this has no affect on the current state of the codebase, but I don't think there's any reason to not use `RESTRICT`.

2023-09-28 21:25 UTC, hepcat72 commented on DataRepo/models/peak_group.py
> +    archive_file = models.ForeignKey(
b. Given your response to [this comment](https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/733#discussion_r1339198198), indicating that `ArchiveFile` will indeed contain multiple file types (as I had recalled), I'm going to call this one blocking, though I am open to being swayed otherwise.  I think this `archive_file` foreign key field in the `PeakGroup` model should reflect the type of file it is linking to in `ArchiveFile` the same way `Animal.treatment` indicates the protocol record type when it links to the `Protocol` model.  And I think that this is the same issue where I pointed out that `displayname` in the format code should reference the file type.  All of those references should be specific to the context where the reference is being made.  I suggest a value similar to what you used in the tests: `ms_peak_annotation`, but perhaps something akin to `peak_annotation_file`.

2023-10-06 20:04 UTC, hepcat72 requested changes
All I found in this review were places where the change from referring to an "Archive File" as a "Peak Annotation File" in the context of Peak Groups and Peak Data seem to have been overlooked.  It was changed in some places where either of those contexts were active.  Perhaps final changes weren't pushed?

2023-10-06 20:16 UTC, lparsons commented on DataRepo/formats/peakdata_dataformat.py
> +            "path": "peak_group__peak_annotation_file",
The model will still be `ArchiveFile` since it's used for multiple purposes, but the relationship from `PeakGroup` is now `peak_annotation_file`. This looks correct to me.

2023-10-06 20:17 UTC, lparsons commented on DataRepo/formats/peakdata_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
Again, looks correct to me.

2023-10-06 20:17 UTC, lparsons commented on DataRepo/formats/peakgroups_dataformat.py
> +            "path": "peak_annotation_file",
Seems correct.

2023-10-06 20:18 UTC, lparsons commented on DataRepo/formats/peakgroups_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
Seems correct.

2023-10-06 20:21 UTC, lparsons commented on DataRepo/templates/DataRepo/search/downloads/peakgroups_colheads.tsv
> +Sample	Tissue	Time Collected (m)	Peak Group	Measured Compound(s)	Measured Compound Synonym(s)	Formula	Labeled Element	Total Abundance	Enrichment Fraction	Enrichment Abundance	Normalized Labeling	Arch
Good catch, it's just a label so no tests caught it and I missed it. Fixed.

2023-10-06 20:21 UTC, lparsons commented on DataRepo/templates/DataRepo/search/downloads/peakdata_colheads.tsv
> +Sample	Tissue	Time Collected (m)	Peak Group	Measured Compound(s)	Measured Compound Synonym(s)	Formula	Labeled Element:Count	Raw Abundance	Corrected Abundance	Fraction	Median M/Z	Median RT	Archive Fil
Good catch, it's just a label so no tests caught it and I missed it. Fixed.

2023-10-06 20:21 UTC, lparsons commented on DataRepo/templates/DataRepo/peakgroup_detail.html
> +            <td>Archive Filename</td>
Good catch, it's just a label so no tests caught it and I missed it. Fixed.

2023-10-06 20:22 UTC, hepcat72 commented on DataRepo/formats/peakdata_dataformat.py
> +            "path": "peak_group__peak_annotation_file",
This particular line is not user-facing, but it is useful in a documentation sense.  The key here represents an instance of a model, not the model itself.  In this instance, the context is as it relates to peakdata and it references a peak annotation file.  They key, similar to multiple instances of the `Compound` model (whose keys are either `MeasuredCompound` or `TracerCompound`), should be `PeakAnnotationFile`.  If this isn't clear, perhaps we should discuss it at the next meeting, and I can explain it in more detail.

2023-10-06 20:25 UTC, hepcat72 commented on DataRepo/formats/peakdata_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
You're right about line 260. I shouldn't have included that in the highlight. And I didn't notice the inclusion of "Annotation" on 253.  I just noticed "Archive".  My mistake.

2023-10-06 20:25 UTC, hepcat72 commented on DataRepo/formats/peakgroups_dataformat.py
> +            "path": "peak_annotation_file",
https://github.com/Princeton-LSI-ResearchComputing/tracebase/pull/733#discussion_r1349289868

2023-10-06 20:26 UTC, hepcat72 commented on DataRepo/formats/peakgroups_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
Line 82 should be `(Internal) Peak Annotation File Index`.

2023-10-06 20:29 UTC, lparsons commented on DataRepo/formats/peakdata_dataformat.py
> +            "path": "peak_group__peak_annotation_file",
Thanks for clearing that up.  I wasn't sure what these were used for. I can certainly update it though. I assume `model: ArchiveFile` line should remain unchanged, but I can change the key. It's unfortunate we have so many of these places where we have strings that represent class or attribute names since they are difficult to check for accuracy.

2023-10-06 20:32 UTC, lparsons commented on DataRepo/formats/peakgroups_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
This is where it gets pretty grey for me. It value is literally the index in the `ArchiveFile` instance, but I take your point that is the index of the Peak Annotation File from the context of the PeakGroup. I'll change it.

2023-10-06 20:41 UTC, hepcat72 commented on DataRepo/formats/peakdata_dataformat.py
> +            "path": "peak_group__peak_annotation_file",
You are correct.  And I have been ruminating over this design, wondering how I can possibly do it without duplicating strings...  This design, incidentally, mimics a similar design I used for creating composite views in perl for our genome annotation and other websites.  Ironically, in perl, it took much less in the way of config and code.  Each composite view was just a tab delimited file and the queries weren't limited the way the ORM doesn't go through M:M linking tables.

2023-10-06 20:45 UTC, hepcat72 commented on DataRepo/formats/peakgroups_dataformat.py
> +                    "displayname": "Peak Annotation Filename",
The only time this would ever be visible to a user, is when rendering the search form via a link from the basic search.  There is a conversion from the ID field to an alternate unique field, in which case, the user wouldn't see this, but we don't always have a unique field in every table, and if the conversion ever happens to fail (because it results in multiple records), it falls back to the ID.

2023-10-06 20:47 UTC, lparsons commented on DataRepo/templates/DataRepo/archive_file_detail.html
> +            <td>{{ archivefile.imported_timestamp|convert_iso_date }}</td>
Another good catch, I just checked and that does not work. However, it seems to display nicely without the filter.

![image](https://github.com/Princeton-LSI-ResearchComputing/tracebase/assets/645128/ba04109c-cebf-4cae-a738-4d23f765ae58)

2023-10-06 21:05 UTC, hepcat72 reviewed
Presuming this passes, this looks good, but I have a hunch that there will be tests to fix relating to the orderings of the dicts compared in the some of the tests.

Submitting this review as a comment.  If/when it passes: approved.

2023-10-09 18:43 UTC, hepcat72 approved these changes
GTG. Sorry for the knit-picking.

2023-10-09 19:05 UTC, merged