Added MSRunSequence
Princeton-LSI-ResearchComputing/tracebase pull request #771
Opened 2023-10-18 17:40 UTC by hepcat72

## Summary Change Description

Added an `MSRunSequence` model.

## Affected Issues/Pull Requests

- Resolves #707

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] Added changes to *Unreleased* section of [`changelog.md`](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2023-10-30 21:08 UTC, lparsons requested changes
This adds the required model class, though there are a few issues with the attributes, notably the required `notes` field. 

The migration is missing (and that should have generated an error, so perhaps we have a problem with our GitHub actions tests for that).

Finally, there should be some tests added (see #715 for an analogous PR).

2023-10-30 21:08 UTC, lparsons commented on DataRepo/models/msrun_sequence.py
> +        on_delete=RESTRICT,  # Don't delete an LCMethod if this record is deleted
I believe this comment is incorrect. `on_delete` specifies the behavior to adopt when the _referenced object_ is deleted. In this example, if an MSRunSequence record is delted, there is no integrity issue in the database, the LCMethod records can exist without any MSRunSequence records. However, if the referenced LCMethod record is deleted, this would cause an integrity error, thus we define what to do in that case. Here, we say that deleting an LCMethod record that is referenced in any MSRunSequence records is [restricted](https://docs.djangoproject.com/en/stable/ref/models/fields/#django.db.models.RESTRICT) (which seems like the right choice to me).

2023-10-30 21:08 UTC, lparsons commented on DataRepo/models/msrun_sequence.py
> +        null=False,
Notes should be optional.

2023-10-31 16:12 UTC, hepcat72 commented on DataRepo/models/msrun_sequence.py
> +        on_delete=RESTRICT,  # Don't delete an LCMethod if this record is deleted
I added the comment specifically to have this discussion, because I find the wording and the example in the docs very confusing. I always have to look it up and I'm usually still not sure.  According to the first sentence in the docs, it seems reversed.  I.e. it seems like what the doc says is `on_delete` specifies what to do with the object referenced by the `ForeignKey` value when *this* record is deleted:

> Prevent deletion of the referenced object...

The `ForeignKey` field contains a reference to an object of another model.  That is (to me) a "referenced object" and `RESTRICT` "prevents deletion of that reference object" (loose quotes).

Then the example they use is ambiguous because multiple artists can be on an album.  Plus the word "CASCADE" implies a top-down action (like a cascading waterfall). Album->artist->song.

When the words put those relationships visualized in my head, interpreting their example becomes very complex when you try to make it fit that image.

So what you're saying is that it should read: `Delete an MSRunSequence only if all other records with references to it are being deleted`?

2023-10-31 16:14 UTC, hepcat72 commented on DataRepo/models/msrun_sequence.py
> +        null=False,
Good catch.
- [ ] TODO: Make `notes` be `null=True, blank=True`

2023-10-31 16:17 UTC, hepcat72 commented
> The migration is missing (and that should have generated an error, so perhaps we have a problem with our GitHub actions tests for that).

I swear I tried to create a migration, but it didn't create one.  I figured it was because this didn't link to anything yet.  I'll try again.  Maybe I made a dumb mistake.

- [ ] TODO: Try to create a migration

> Finally, there should be some tests added (see #715 for an analogous PR).

- [ ] TODO: Add tests for MSRunSequence

2023-11-02 19:10 UTC, hepcat72 commented
@lparsons - Apparently, in order for `makemigrations` to make a migration, the model has to be added to `__init__.py`.  I hadn't added it.  That's why it wasn't created when I ran it, and why the tests did not fail.

2023-11-03 19:28 UTC, lparsons requested changes
Looks good with the addition of a migration and a few tests. I don't think the archive files should be added to the repository, however. Once those are removed, this will be ready to go imho.

2023-11-03 19:28 UTC, lparsons commented on DataRepo/models/msrun_sequence.py
> +        on_delete=RESTRICT,  # Delete this MSRunSequence if all other records referencing it are being deleted
NB: I think you are understanding this correctly, though the comment is still a bit misleading to me. Setting `on_delete` to `RESTRICT` means that the `MSRunSequence` can only be deleted if there are no other records referencing it, not that it will be deleted.

2023-11-03 19:28 UTC, lparsons commented on DataRepo/tests/models/test_msrun_sequence.py
> +            name="L.C. McMethod",
:smile:

2023-11-03 19:28 UTC, lparsons commented on DataRepo/tests/models/test_msrun_sequence.py
> +    def setUp(self):
NB: I would thought we would have an explicit test to create the object.

2023-11-03 19:45 UTC, hepcat72 commented on DataRepo/models/msrun_sequence.py
> +        on_delete=RESTRICT,  # Delete this MSRunSequence if all other records referencing it are being deleted
I see your point, and I think that when I edited the MSRunSample help text after this update, I understood it better, because I had to think about it more.  This doesn't delete - it just doesn't stop deletion if it happens via a separate field's `CASCADE` and all references to it are included in the operation.

I must say, I find the documentation wording and the example it gives, really confusing.  IMO, they should have used a simpler example and tried to make the explanation too succinct.  I think I have it now, but the next time I encounter wanting to set this, I'm going to have to figure it out all over again.

- [ ] TODO: Edit the `RESTRICT` comment to not suggest that `RESTRICT` does a delete

2023-11-03 20:06 UTC, hepcat72 commented on DataRepo/tests/models/test_msrun_sequence.py
> +    def setUp(self):
Can you clarify what you mean?  `test_msrun_sequence` creates the object.  Do you mean a literal call to `MSRunSequence.objects.create()`?  I know that `create()` calls `save()` (and it does so with a `force_insert=True`).  If I were to call `create()` and do a `full_clean()` after, I'm not sure if an exception from `full_clean` would cause the save to be undone... unless it was in an atomic transaction (which the tests run under anyway).  Point is, at least for tests, I would say that `create/full_clean` is roughly equivalent (or sufficiently equivalent) to `__init__/full_clean/save`.

2023-11-03 20:13 UTC, lparsons commented on DataRepo/tests/models/test_msrun_sequence.py
> +    def setUp(self):
Sorry, you're right. I somehow thought the object was being created in `setUp`, but either I was just seeing things incorrectly, or perhaps the GitHub issues affected things. I did have some issues with rendering for bit there.

2023-11-03 20:26 UTC, hepcat72 commented
- [ ] TODO: Remove the archive files that were unintentionally added

2023-11-03 22:10 UTC, merged