Updated the submission process for `MSRunSample` and `MSRunSequence`
Princeton-LSI-ResearchComputing/tracebase pull request #797
Opened 2023-12-04 19:57 UTC by hepcat72

## Summary Change Description

- updated the [submission form](https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit)
   - Added an instrument field with radio buttons
   - Turned date field from short answer to date
   - Changed operator answer to radio buttons with an "other" option - to control name variants.  To do that, I did the following:
     ```
     ssh tracebase
     sudo -iu tracebase
     cd /var/www/tracebase
     source /usr/local/tracebase/bin/activate
     python manage.py shell
     
     In [1]: from DataRepo.models.researcher import get_researchers
     In [2]: print("\n".join(sorted(get_researchers())))
     ```
- Converted google docs links to markdown
  - Converted terms and definitions sheet using https://www.tablesgenerator.com/markdown_tables

## Affected Issues/Pull Requests

- Resolves #711

## Review Notes

I did not try generating the web content.  The links I created should probably all be checked.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2023-12-04 20:00 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Contributing/Report a bug or request a feature on github.md
Those files were mainly exported as text from gdocs and then marked up(/down). I also tried to catch things like smart quotes and contained links to other gdocs.

2023-12-04 20:01 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/TraceBase Terms and Definitions.md.txt
C. Generated using an online markdown table generator and pasting in content from the previously linked google sheet.

2023-12-04 20:02 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
> +     | T3 in drinking water (1.5 mg/L) | T3 was provided in drinking water at 1.5 mg/L for two weeks prior to the start of infusion.              |
C. Generated using a markdown table generator online.

2023-12-04 20:02 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
> +     | T3 in drinking water (1.5 mg/L) | T3 was provided in drinking water at 1.5 mg/L for two weeks prior to the start of infusion.              |
I actually converted text from an embedded image in the gdoc.

2023-12-04 20:03 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Contributing/Report a bug or request a feature on github.md
Be sure to also review the changes to the [submission form](https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit), which I comment on in the PR description.

2023-12-04 20:21 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Contributing/Report a bug or request a feature on github.md
C. I took advantage of the opportunity of this small update to take care of some google doc links. Multiple files were created to replace direct links to google docs.

Those files were mainly exported as text from gdocs and then marked up(/down). I also tried to catch things like smart quotes and contained links to other gdocs.

Be sure to also review the changes to the [submission form](https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit), which I comment on in the PR description.

2023-12-04 20:22 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/TraceBase Terms and Definitions.md
C. Generated using an online markdown table generator and pasting in content from the previously linked google sheet.

2023-12-04 20:23 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
> +    | T3 in drinking water (1.5 mg/L) | T3 was provided in drinking water at 1.5 mg/L for two weeks prior to the start of infusion.              |
C. Generated using a markdown table generator online.

I actually converted text from an embedded image in the gdoc.

2023-12-04 21:03 UTC, hepcat72 commented on .markdown-lint.yml
> +  tables: false
C. The table content auto-wraps.  The longest line is 562.  So I learned you can set the linter to ignore line length for tables.

2023-12-04 21:04 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Contributing/Report a bug or request a feature on github.md
C. I took advantage of the opportunity of this small update to take care of some google doc links. Multiple files were created to replace direct links to google docs.

Those files were mainly exported as text from gdocs and then marked up(/down). I also tried to catch things like smart quotes and contained links to other gdocs.

Be sure to also review the changes to the [submission form](https://docs.google.com/forms/d/1Y2SEQgLTd8QUjbXGCuo3989WQxMfsfh4AbJyeL3f6c8/edit), which I comment on in the PR description.

2023-12-04 21:05 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/TraceBase Terms and Definitions.md
C. Generated using an online markdown table generator and pasting in content from the previously linked google sheet.

2023-12-04 21:06 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
> +    | T3 in drinking water (1.5 mg/L) | T3 was provided in drinking water at 1.5 mg/L for two weeks prior to the start of infusion.              |
C. Generated using a markdown table generator online.

I actually converted text from an embedded image in the gdoc.

2023-12-04 21:09 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/TraceBase Terms and Definitions.md
https://www.tablesgenerator.com/markdown_tables

2023-12-04 21:09 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
> +    | T3 in drinking water (1.5 mg/L) | T3 was provided in drinking water at 1.5 mg/L for two weeks prior to the start of infusion.              |
https://www.tablesgenerator.com/markdown_tables#

2023-12-05 16:41 UTC, lparsons requested changes
Looks great @hepcat72. 

The submission form seems much nicer and easier (multiple choice questions are easy to answer). 

The cleanup of the docs is a big bonus, thanks for catching that and updating the markdown. I did push a small commit to fix some broken links I discovered when building the docs (some predated this PR, but they were simple file path fixes). There are a few files that I think should be combined (or just stick to one version). Those are small fixes though and really just some additional cleanup.

2023-12-05 16:41 UTC, lparsons commented on TraceBaseDocs/TraceBaseDocs/Download/Format of Downloaded Data.md
B: This file seems like it duplicates some information and should be combined with `TraceBaseDocs/TraceBaseDocs/Types of Data Output/Downloaded Data Formats.md`

2023-12-05 16:41 UTC, lparsons commented on TraceBaseDocs/TraceBaseDocs/Upload/How to label sample information.md
B: This seems duplicative and should be combined with `TraceBaseDocs/TraceBaseDocs/Upload/Sample Information Sheet.md`

2023-12-05 16:48 UTC, hepcat72 commented
> Looks great @hepcat72.
> 
> The submission form seems much nicer and easier (multiple choice questions are easy to answer).
> 
> The cleanup of the docs is a big bonus, thanks for catching that and updating the markdown. I did push a small commit to fix some broken links I discovered when building the docs (some predated this PR, but they were simple file path fixes). There are a few files that I think should be combined (or just stick to one version). Those are small fixes though and really just some additional cleanup.

Thanks for fixing the links.  That's exactly what I was hoping would come out of the review.

I hadn't intended, in this PR, to change any content (other than to satisfy linting errors).  I just transferred the content from google docs to markdown files.  While I agree with your issues, I propose we merge this and make a separate issue to fix the content?

2023-12-05 17:01 UTC, lparsons approved these changes
> I hadn't intended, in this PR, to change any content (other than to satisfy linting errors). I just transferred the content from google docs to markdown files. While I agree with your issues, I propose we merge this and make a separate issue to fix the content?

OK, we can do that. It just looked to me like some Google Docs were already converted to markdown and reorganized and this PR added duplicates. It'd be nice to avoid those, but if you create issues that indicate those duplicates we can tackle them individually.

2023-12-05 17:08 UTC, hepcat72 commented
> > I hadn't intended, in this PR, to change any content (other than to satisfy linting errors). I just transferred the content from google docs to markdown files. While I agree with your issues, I propose we merge this and make a separate issue to fix the content?
> 
> OK, we can do that. It just looked to me like some Google Docs were already converted to markdown and reorganized and this PR added duplicates. It'd be nice to avoid those, but if you create issues that indicate those duplicates we can tackle them individually.

Oh, well that may be?  I had just gone through every `docs.google.com` link in the files and assumed those pages had not been converted since the direct links to google existed in the docs.  In fact, I pondered changing things, like those pages that were 2 lines long - just incorporate them into the doc that linked them... but I decided I was getting too far down a rabbit hole.

I'll look to see if I can detect entire file duplicates and make an issue.  If I can't precisely identify them, I'll create a general issue linking this PR comment.

2023-12-05 17:27 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Download/Format of Downloaded Data.md
Created issue

2023-12-05 17:30 UTC, hepcat72 commented on TraceBaseDocs/TraceBaseDocs/Overview/TraceBase Terms and Definitions.md
Created issue #801

2023-12-05 17:32 UTC, hepcat72 commented
OK, I had inferred you were suggesting that the conversion had maybe ended up duplicating content in general, but I think I misinterpreted, so I just created issues for the 3 review issues you raised.

2023-12-05 17:32 UTC, merged