Archive File links to basic search (peak groups and data) fixed
Princeton-LSI-ResearchComputing/tracebase pull request #864
Opened 2024-02-19 20:42 UTC by hepcat72

## Summary Change Description

Fixed a bug in the advanced and basic search code then updated the archive file templates.

We had never linked using a model that is part of a composite view where that model had multiple "instances" before.  Doing so with `ArchiveFile` records revealed the bug.  Models that have multiple different ways it links to a composite view (e.g. the peak groups "format"), e.g. via a peak annotation file, an mzXML file, or even a RAW file.

Note, none of the links in the view had the name "ArchiveFile", so linking to the basic search using that model name correctly reported the error "Ambiguous model instance" because there were 3 different instances that you could search on.

But when you change it to any of the "correct" instance names, you still get an error.  That's because the code was supplying the model instance name ("PeakAnnotationFile", "RAWFile", or "MZFile") to the `get_model_by_name` function.

I added a new method `getModelByFromInstance` and supplied the result to `get_model_by_name`.

## Affected Issues/Pull Requests

- Resolves #843

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2024-02-19 20:46 UTC, hepcat72 commented on DataRepo/formats/dataformat_group.py
> +    def searchFieldToDisplayField(self, mdl_instance, fld, val, qry):
C. Tried to disambiguate the argument.  There are multiple places in the code that use "mdl" interchangeably with a "model instance".  E.g. "PeakAnnotationFile" is an "instance" of "ArchiveFile".  This is the mechanism used when constructing a "format" (i.e. composite view composed of fields from multiple models).  Both the PeakGroups and PeakData "formats" have 3 ArchiveFile "instances", each linked to the view via different relational paths.  Searching using one or the other leads to different results.

2024-02-19 20:47 UTC, hepcat72 commented on DataRepo/migrations/0034_alter_sample_time_collected.py
C. Whoops.  Leftover file from a different branch.  Ugh.  I'll remove it...

2024-02-20 18:46 UTC, lparsons requested changes
This looks good and seems to resolve the issue. There should probably be a test and an update to the CHANGELOG. In case it helps (and to help me understand the new method) I submitted a PR with suggested tests.

2024-02-20 20:49 UTC, lparsons approved these changes
LGTM

2024-02-20 20:54 UTC, merged