Stream excel download
Princeton-LSI-ResearchComputing/tracebase pull request #933
Opened 2024-03-31 15:21 UTC by hepcat72

## Summary Change Description

Added a conversion of the `dfs_dict` to an excel file and added the ability of the results page to automatically download the file.

**Note, I have not yet removed or hidden the errors/warnings section onn the resulting page.**  And I have a few other ideas for nice-to-have features:
- time- and/or date-stamp the file name
- Add a method to shortcut the processing when no animal/sample sheet is supplied to only grab data to be added
- If the study exists, automatically add all existing data to the spreadsheet (I realized in testing that sample names were not added on some example sets I'd tested with, because I'd already loaded them - so they weren't "missing")

## Affected Issues/Pull Requests

- Partially addresses #829
- Merges into PR #932

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [x] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2024-03-31 15:23 UTC, hepcat72 commented on DataRepo/tests/views/upload/test_validation.py
> +        dfs_dict = dvv.get_or_create_dfs_dict()
C. Renamed for accuracy, since I'd reverted the conversion to dataframes (since it was too early to do so).  It was easier to add data to the dicts than it was to work with the dataframes.

2024-03-31 15:23 UTC, hepcat72 commented on DataRepo/views/search/download.py
> +            res, _, _ = self.basv_metadata.getAllBrowseData(qry["selectedtemplate"])
C. Just happened to notice these variables were't used.

2024-03-31 15:27 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +import base64
C. I embed the excel file in the html and convert to a file download, with a file name given, in javascript.  The max animal/sample sheet we have is 115kb, so I think this is a perfectly adequate solution.  I tried all dat on Saturday to [implement a multipart stream](https://stackoverflow.com/questions/78246105/how-to-start-a-download-and-render-a-response-without-hitting-disk/78250386#78250386), but it was too complex and I couldn't get it to fully work.  Even if I had gotten it working, I didn't fully understand it, so it would have been difficult to fix if it broke.

2024-03-31 15:30 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +            self.treatments_loader = ProtocolsLoader(file=self.animal_sample_file)
C. I recreate the loader objects when an animal/sample sheet if provided so that the object contains the actual file name.  I could have set the data member, but I didn't want to take the time to test that the rest of the instance variables didn't get stale.

2024-03-31 15:30 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +            sample_filename=str(sample_file) if sample_file is not None else None,
C. This was a bug that was making the name of the downloaded file "None" when no sample sheet was uploaded.

2024-03-31 15:32 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +            study_filename = "study.xlsx"
C. I deleted the method I'd intended to put this code in, but things were changing as I learned how to work with `xlsxwriter`, so I decided to hold off on encapsulation until I better understood the ins and outs.

2024-03-31 15:32 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> -        return "TODO: Return study_dfs_dict once get_output_study_file is implemented"
C. This was moved into `form_valid`.  See comment above.

2024-03-31 15:33 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +        ]
C. This was my solution to specifying a custom sheet and column order.

2024-03-31 15:34 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> -        pl = ProtocolsLoader(file="dummy.xlsx")
C. Made into instance variables.

2024-03-31 15:34 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +        ]
C. These properties will go away after the loader refactors are done.

2024-04-01 20:49 UTC, hepcat72 commented
Not sure what caused the messy log...  Ugh.

2024-04-02 15:02 UTC, lparsons requested changes
This PR provides the ability to download a sample sheet with sample names filled in. Neat solution to using the JS download of an embedded file. In testing, I generated a `study.xlsx` file from an accucor, which worked well. 👍🏻 

Blocking issue: 
However, I then deleted a few lines and used it as an input file and I got an exception:
```
Traceback (most recent call last):
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/validation.py", line 170, in dispatch
    return super(DataValidationView, self).dispatch(request, *args, **kwargs)
  File "/home/lparsons/miniforge3/envs/tracebase/lib/python3.9/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/validation.py", line 202, in post
    return self.form_valid(form)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/validation.py", line 213, in form_valid
    self.extract_autofill_exceptions()
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/views/upload/validation.py", line 364, in extract_autofill_exceptions
    new_load_status_data.copy_constructor(self.load_status_data)
  File "/home/lparsons/Documents/projects/tracebase/DataRepo/utils/exceptions.py", line 745, in copy_constructor
    if len(instance.statuses[load_key]["aggregated_errors"].exceptions) > 0:

Exception Type: AttributeError at /DataRepo/validate
Exception Value: 'NoneType' object has no attribute 'exceptions'
```

Also, just a comment from testing it. When trying it out, it seems potentially confusing to me since it asks for two files and it wasn't obvious I didn't need to the second one. Also, it wasn't obvious that I would be adding to the study file I uploaded. Perhaps making it separate steps would help with that, but we can get further feedback and mock-up some ideas before developing.

2024-04-02 15:02 UTC, lparsons commented on DataRepo/views/upload/validation.py
> +        ]
C: I'd be in favor of simply having a single default order for columns for each sheet to simplify things, but this certainly works.

2024-04-02 15:33 UTC, hepcat72 commented
> This PR provides the ability to download a sample sheet with sample names filled in. Neat solution to using the JS download of an embedded file. In testing, I generated a `study.xlsx` file from an accucor, which worked well. 👍🏻
> 
> Blocking issue: However, I then deleted a few lines and used it as an input file and I got an exception:

That's a great test to have done!  However, I already encountered and fixed this in the work on the next PR which removes the errors when only adding data to a fully generated sample sheet.  Had I realized it existed in the previous PR, I'd have fixed it in that branch.  Sorry, I know you would prefer that to have been done in this PR.  I just simply didn't discover it until the next chunk of work.

> Also, just a comment from testing it. When trying it out, it seems potentially confusing to me since it asks for two files and it wasn't obvious I didn't need to the second one. Also, it wasn't obvious that I would be adding to the study file I uploaded. Perhaps making it separate steps would help with that, but we can get further feedback and mock-up some ideas before developing.

Yeah, the muted text probably won't get read.  That's a reasonable insight.  I think there's value in keeping it as a single step/form (but I'll make that case when it's later discussed).  Although, it could be handled by either presentation (e.g. a red asterisk on the peak annotation field and not on the animal/sample field, or a clever checkbox next to the default output file like:

Output file:
- [x] `study.xlsx`

And if they uncheck it, a file field is revealed below it.  Simple, but less ambiguous.

2024-04-02 15:37 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +import base64
That can definitely easily be done using the same mechanism used here.  The only reason it downloads immediately is because of the javascript that runs upon completion of the page load.  That could easily be transferred to a button.  In fact, that's what I had done with the initial lcms file implementation (only it was a link instead of a decorated button).

2024-04-02 15:46 UTC, hepcat72 commented on DataRepo/views/upload/validation.py
> +        ]
I'm unclear what distinction you're making.  This solution is precisely a "single default order for columns for each sheet".  Do you mean that you want that order specified separate from the loader classes and properties used here?  I did it this way so that the order for each sheet would live in only a single place.  This just references the places where each sheet's order is kept.  And, as I mentioned before, I retrieve the order from the loader classes using a method for 2 reasons:
1. due to an edge case I'd discovered where the order in `TableLoader.all_headers` had become stale.
2. The order exists in `LoaderTable.DataTableHeaders`, but since custom headers can be specified, a method is used to get the actual header names.

Perhaps it would be easier to understand if I made `get_ordered_display_headers` into a property named something like `all_headers`?

2024-04-02 15:48 UTC, hepcat72 commented
@lparsons Since the blocking issue is fixed in the next PR, I'll hold off on merging this until that PR is merged in here...  That will make "more to review" here, but since there are no other changes here, all you'll need to do is check that the exception isn't thrown upon re-review...

2024-04-03 21:50 UTC, hepcat72 commented
The exception checks were done in the child PR which was merged in here, so I am going to merge this.

2024-04-03 21:50 UTC, hepcat72 commented
...After the CI checks pass...

2024-04-03 22:03 UTC, merged