Improvements to settings for testing the archive directory.
Princeton-LSI-ResearchComputing/tracebase pull request #981
Opened 2024-05-30 23:10 UTC by hepcat72

## Summary Change Description

To be able to test actual file existence and the cleanup of the archive directory, I tweaked the settings to make it easier to use `override_settings` decorators to be able to test actual file creation/deletion.  I added a TraceBasetestCase class for the cleanup code, which I realize ATM, is separate from the settings changes, but the new class could be reverted if we want.

You cannot set a settings dict key value in a settings override, so creating separate settings variables to be able to change makes it more straightforward.

## Affected Issues/Pull Requests

- Resolves no issue

## Review Notes

See comments in-line.

## Checklist

This pull request will be merged once the following requirements are met.  The
author and/or reviewers should uncheck any unmet requirements:

- Review requirements
  - Minimum approvals: 1 
  - No changes requested
  - All blocking issues resolved by reviewers
  - Specific reviewers: @__add_username_here__
    
  - Review period: 2 days 
- Associated issue/pull request requirements:
  
  - [x] All requirements in affected issues marked "resolved" are satisfied
  - [x] All required pull requests are merged *(or none)*
- Basic requirements
  
  - [x] [All linters pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#linting)
  - [x] [All tests pass](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#quality-control)
  - [x] All conflicts resolved
- Overhead requirements
  
  - [x] [New/changed method tests implemented/updated *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#test-implementation)
  - [ ] [Updated *Unreleased* section of `changelog.md` *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/changelog.md)
  - [x] [Migrations created & committed *(or no change)*](https://github.com/Princeton-LSI-ResearchComputing/tracebase/blob/main/CONTRIBUTING.md#migration-process)

2024-05-30 23:15 UTC, hepcat72 commented on DataRepo/tests/tracebase_test_case.py
> +        super().tearDown()
C. This class can be used for testing file creations.  It cleans up after itself.  Hitting the disk is slower, so it shouldn't be used much - only for tests where we want to test files were created or not created..

2024-05-31 17:15 UTC, hepcat72 commented on DataRepo/tests/tracebase_test_case.py
> +TracebaseTransactionTestCase: TestCase = test_case_class_factory(TransactionTestCase)
C. Added type hints because mypy complains about the class below (even though it never complained about essentially the same issue in any of the test files.

2024-05-31 17:22 UTC, hepcat72 commented on TraceBase/settings.py
> +)
C. Made changes to the settings to make overrides simpler. You can't override a key to a settings dict variable in a decorator.  The strategy was:

1. Create `TEST_MEDIA_ROOT` so it could be changed in an `@override_settings` decorator with `MEDIA_ROOT=settings.TEST_MEDIA_ROOT` and the "archive_test" default would only exist in 1 place.
2. I created 3 copies of `STORAGES`: `DEFAULT_STORAGES`, `TEST_STORAGES` (for in-memory-storage [i.e. the bulk of the tests]), and `TEST_FILE_STORAGES` (for testing actual file creations/handling)

2024-05-31 17:25 UTC, hepcat72 commented on TraceBase/runner.py
> +        settings.STORAGES = settings.TEST_STORAGES
C. Using separate settings variables makes this a bit cleaner.

2024-05-31 20:55 UTC, lparsons requested changes
B: This should contain one commit to be be merged into `main` and not `get_sequence_improvement` since it is independent of the changes in that branch. 

C: Looks like a nice way to allow us to test file creation. I'd probably opt to move such a test a functional test that loads the example data as part of a separate action in CI, but this is OK too.

2024-05-31 21:10 UTC, hepcat72 commented
> B: This should contain one commit to be be merged into `main` and not `get_sequence_improvement` since it is independent of the changes in that branch.
> 
> C: Looks like a nice way to allow us to test file creation. I'd probably opt to move such a test a functional test that loads the example data as part of a separate action in CI, but this is OK too.

Mind if I ask what the purpose of the blocking issue is? Since the merge into the PR for `get_sequence_improvement` is approved, it seems honestly pointless. I could just merge that PR and then this one would automatically merge into main.  I haven't looked at the rest of the review issues yet, so if it's answered in there, you may ignore.

2024-05-31 21:18 UTC, lparsons approved these changes
> Mind if I ask what the purpose of the blocking issue is? Since the merge into the PR for `get_sequence_improvement` is approved, it seems honestly pointless. I could just merge that PR and then this one would automatically merge into main. I haven't looked at the rest of the review issues yet, so if it's answered in there, you may ignore.

Sure, I guess just go ahead and merge this along with that other PR.

2024-06-04 22:13 UTC, merged